### ISSUE TITLE
Build instructions for Fedora 27

### ISSUE THREAD

**Issue by hesdago** [gnif/LookingGlass#1]
Hi, I've just ran through the build instructions for Fedora 27 workstation, and the following corrections might be useful for a fresh install: 

Actual required package list for me was:
```
dnf groupinstall "Development Tools" "Development Libraries"
sudo dnf install git SDL2-devel SDL2_ttf-devel openssl-devel spice-protocol fontconfig-devel libX11-devel gnu-free-mono-fonts ivshmem-tools mesa-libGL-devel mesa-libGLU-devel
```

Without libGL and libGLU packages, make would error out with:
```
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gl', required by 'virtual:world', not found
Package 'glu', required by 'virtual:world', not found
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -ffast-math -fdata-sections -ffunction-sections  -DBUILD_VERSION='"a2-5-g2ae9b479f6"' -o .build/main.o main.c
In file included from lg-renderers.h:21:0,
                 from main.c:42:
lg-renderer.h:25:10: fatal error: SDL_ttf.h: No such file or directory
 #include <SDL_ttf.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:28: .build/main.o] Error 1
```

**Comment by tylerjwatson** [comment]
Beat me to it.  I had to do an additional Makefile patch to get it to recognize SDL2 and spice-protocol include dirs. Not sure if it's actually needed yet

**Comment by gnif** [comment]
I just fixed the include path, I missed that one sorry.

Is `mesa-libGL-devel mesa-libGLU-devel` correct for all configurations? On Debian we have NVIDIA and Mesa variants of this, among others.

**Comment by dsjstc** [comment]
Not worth opening a separate issue, but here's what I needed for Ubuntu 17.10.  It's certainly missing libraries, but it's a start for the next person coming this way:

`apt install build-essential git libsdl2-ttf-dev libsdl2-dev libssl-dev libspice-protocol-dev  libfontconfig1-dev`

**Comment by slis** [comment]
@gnif you can also add libva-devel, i just tried to build on fedora 27

**Comment by gnif** [comment]
@slis libva isn't used yet, please build a tagged release.

**Comment by Leooow** [comment]
I also got an error stating libconfig.h was missing. Maybe need to add libconfig-devel in the DNF list?

**Comment by gnif** [comment]
@Leooow please build the tagged release. libconfig is not in a tagged release yet as such the documentation will not be updated.

**Comment by Username123456765645** [comment]
I'm having a similar issue on KDE Neon 
 I was following your guide  and I could not make it this is the error message I got when I try to make it any help would be appreciated
Package libconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `libconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libconfig' found
Package libva was not found in the pkg-config search path.
Perhaps you should add the directory containing `libva.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libva' found
Package libva-glx was not found in the pkg-config search path.
Perhaps you should add the directory containing `libva-glx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libva-glx' found
cc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -Wfatal-errors  -DBUILD_VERSION='"a10-50-gfd8d4d3d38"' -o .build/main.o main.c
main.c:37:23: fatal error: libconfig.h: No such file or directory
compilation terminated.
Makefile:38: recipe for target '.build/main.o' failed
make: *** [.build/main.o] Error 1

**Comment by gnif** [comment]
@Username123456765645 use a tagged release.
