### ISSUE TITLE
UPS not going over 60

### ISSUE THREAD

**Issue by DreamerPlays** [gnif/LookingGlass#100]
### Required information

Host CPU: Ryzen 1600X @ 4.05 GHz
Host GPU: NVidia GTX 760 OEM
Guest GPU: NVidia GTX 1060 6Gb
Host Kernel version: 4.18.7-200.fc28.x86_64
Host QEMU version: 2.11.2

The command i started lookingglass with: ./looking-glass-client -K 144 -k -o opengl:vsync=0 -F -x 1920
I have a "video virtio"
On the VM I just double clicked the Host Application.
Everything is running fine except for the UPS not going over 60
1920x1080 monitor with 120 hz
The shared memory file is 32M
If i plug a cable into the guest graphics card i get the 120 hz
testufo.com also says 120hz

Is there a option to set the ups to a specific value and dont let the programm decide when to send a new frame?

Dreamer

**Comment by gnif** [comment]
UPS = Updates per second from the guest, to increase this you have to have the guest send updates faster then 60 FPS. To do this, you either have to run the guest with a higher refresh rate, or disable vsync in the guest.
