### ISSUE TITLE
935: glGenBuffers = 1281 (invalid value)

### ISSUE THREAD

**Issue by Topis** [gnif/LookingGlass#101]
### Required information

Host CPU: Ryzen 2700X
Host GPU: Radeon R7 240
Guest GPU: GeForce GTX 1060
Host Kernel version: 4.18.0-16.1-liquorix-amd64
Host QEMU version: 3.0.0

Commit https://github.com/gnif/LookingGlass/commit/961312716222e703704988980e3de190e3a613b2 breaks the client on Wayland for me. I get the following error and a black screen.

[I]               main.c:735  | run                            | Looking Glass (a11-98-g2692ccc7b3-dirty
)                                                                                                       
[I]               main.c:736  | run                            | Locking Method: Atomic                 
[I]               main.c:751  | run                            | Wayland detected                       
[I]               main.c:757  | run                            | SDL_VIDEODRIVER has been set to wayland
[I]               main.c:729  | try_renderer                   | Using Renderer: OpenGL                 
[I]               main.c:839  | run                            | Using: OpenGL                          
[I]               main.c:976  | run                            | Waiting for host to signal it's ready..
.                                                                                                       
[I]             opengl.c:455  | opengl_render_startup          | Vendor  : X.Org                        
[I]             opengl.c:456  | opengl_render_startup          | Renderer: AMD Radeon HD 8500 series (OL
AND, DRM 3.26.0, 4.18.0-16.1-liquorix-amd64, LLVM 6.0.1)                                                
[I]             opengl.c:457  | opengl_render_startup          | Version : 3.1 Mesa 18.1.9              
[I]             opengl.c:469  | opengl_render_startup          | Using GL_AMD_pinned_memory             
[I]               main.c:985  | run                            | Host ready, starting session           
[I]             opengl.c:890  | configure                      | Using decoder: NULL                    
[E]             opengl.c:859  | _check_gl_error                | 935: glGenBuffers = 1281 (invalid value
)                                                                                                       
[I]             opengl.c:890  | configure                      | Using decoder: NULL   

This is only on Wayland, Xorg works.

**Comment by gnif** [comment]
Wayland is not supported at this time. You may have better luck using the newer EGL renderer, to use it run with `looking-glass-client -g egl`

**Comment by Yardanico** [comment]
@gnif Same happens for me, however I don't use Wayland (I use LXQt which is Xorg-only).
Host CPU: i5-4460
Host GPU: Intel HD 4600
Guest GPU: NVIDIA GTX 750
Host Kernel version: 4.19.4
Host QEMU version: 3.0.0
Client built from https://github.com/gnif/LookingGlass/commit/4e7de236d371c3a1169885f8731fa2f2685916c9 works perfectly (even when using latest host from AppVeyor), https://github.com/gnif/LookingGlass/commit/961312716222e703704988980e3de190e3a613b2 fails:
```
[I]               main.c:735  | run                            | Looking Glass ()
[I]               main.c:736  | run                            | Locking Method: Atomic
[I]               main.c:729  | try_renderer                   | Using Renderer: OpenGL
[I]               main.c:839  | run                            | Using: OpenGL
[I]              spice.c:159  | spice_connect                  | Remote: 127.0.0.1:5900
[I]               main.c:976  | run                            | Waiting for host to signal it's ready...
[I]              spice.c:367  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]             opengl.c:455  | opengl_render_startup          | Vendor  : Intel Open Source Technology Center
[I]             opengl.c:456  | opengl_render_startup          | Renderer: Mesa DRI Intel(R) Haswell Desktop 
[I]             opengl.c:457  | opengl_render_startup          | Version : 3.0 Mesa 18.2.5
[I]               main.c:985  | run                            | Host ready, starting session
[I]             opengl.c:890  | configure                      | Using decoder: NULL
[E]             opengl.c:859  | _check_gl_error                | 935: glGenBuffers = 1281 (invalid value)
[I]             opengl.c:890  | configure                      | Using decoder: NULL
```

**Comment by ananace** [comment]
Same issue here as well on KDE Plasma 5 running under regular Xorg 1.20.3

Host: i7-7700K and a Radeon RX580 on Linux 4.18.19 and QEMU 3.0.0 - using Mesa 18.2.5
Guest: NVIDIA GTX 1070 using 417.22

And I can also verify that 4e7de23 works fine for me.
