### ISSUE TITLE
If the client window is not in focus, mouse cursor becomes permanently invisible in the guest OS

### ISSUE THREAD

**Issue by Lissanro** [gnif/LookingGlass#1014]
If the client windows is not in focus, mouse cursor becomes invisible, even if I use hardware mouse to move the cursor. The mouse cursor itself can be moved and I still can click on something, but obviously it is hard to aim if the cursor is completely invisible. It would be nice if it left the cursor as is instead of hiding it when the client window loses focus, or at least if there was an option to prevent this issue, to disable cursor hiding. Not sure if this intentional feature or a bug, but it interferes if I want to use hardware mouse or barrier software.

As one example, consider the following situation: in Windows, I use hardware tablet, and in Linux a touchpad, on one screen (Linux host) I have a browser and touchpad to navigate, but I still want to continue using my tablet normally to control mouse (in Windows guest), and if the cursor is invisible, this is hard to do. There are many other situations when this issue gets in the way as well.

Only option I have found in the client is input:hideCursor, but it controls hiding of host cursor, which works well with the defauld input:hideCursor=yes. But this issue is about unwanted hiding of the mouse cursor in the guest OS. If the user trying to move mouse cursor, they expect it to be visible by default.

The way to reproduce is easy. Move the mouse cursor out of the LG client windows, and switch focus to some other window in the host. Then try to control mouse in the Windows guest (either using hardware mouse/tablet or barrier software), the mouse cursor will be invisible, but normally mouse cursor is expected to be visibile.

**Comment by gnif** [comment]
`spice:alwaysShowCursor=yes`

**Comment by Lissanro** [comment]
Thank you. For some reason I overlooked this client option. It solved the issue.
