### ISSUE TITLE
Cursor position changes only when I click

### ISSUE THREAD

**Issue by PaddiM8** [gnif/LookingGlass#103]
### Required information

Host CPU: Intel Core i7-6700
Host GPU: Intel HD Graphics 530
Guest GPU: NVIDIA GTX 1060 6GB
Host Kernel version: 4.19.4
Host QEMU version: 3.0.0

One day when I started the VM and looking-glass, I noticed the mouse wasn't moving. Shortly after I realized it only updated its movement when I clicked. It worked fine when using just spice, in the virt-manager client. I'm using i3 window manager on arch linux. I have tried different versions of the software as well. I did not change any configurations, and it did work before. The cursor also tends to stick at the top for some reason.

**Comment by gnif** [comment]
Remove the tablet virtual device from your VM

**Comment by niecore** [comment]
Had the same issue. Maybe we could add this to the FAQ section.

**Comment by uberentwickelt** [comment]
Reporting that this fixed a similar issue I was having where once I entered capture mode wherever the mouse was when ScrlLk was pressed, that's where the mouse snapped back to. Cursor would move on screen but when an on-click event would happen it would go right back to where it was at capture mode init.

Removing the tablet device fixed this. Posting in case anyone else runs across this issue page with the same thing happening. I second @niecore suggestion related to adding it to the FAQ section.

**Comment by Jugulaire** [comment]
Could you explain WHERE do you you need to go for disabling this "virtual device" ? 
It's not clear and it break always my QXL control...

**Comment by gnif** [comment]
In libvirt, simply remove the "Tablet" device from the list.

**Comment by HiadaiHigashi** [comment]
> In libvirt, simply remove the "Tablet" device from the list in the GUI

why this is not in FAQ?

**Comment by gnif** [comment]
Because I have not had time to update the FAQ, and this is a QEMU bug.
