### ISSUE TITLE
Pipewire version not specified in docs

### ISSUE THREAD

**Issue by RianKatoen** [gnif/LookingGlass#1033]
### Issue
Compile time errors (see log below). Header mismatch for Pipewire, `PW_KEY_CONFIG_NAME` is undeclared.

The docs specify a list of required packages. Installing these is no issue but I can't really find a version mentioned anywhere. After some digging the default feed in Proxmox VE supplies an older version than the one this build relies on. This throws a compile time error as the headers are out of whack.

Anyways, might be handy to mention the required version, looking from the docs. Sifting through the Pipewire source it looks like `PW_KEY_CONFIG_NAME` is defined in `keys.h` since version `0.3.22` onwards. Of course this is no guarantee that `looking-glass-cllient` will compile/work as intended given this version.

## Current workaround
Build client without Pipewire: `cmake -DENABLE_PIPEWIRE=no ../`,

#### make
Below is output for `make` after following the docs to the letter.
```
Scanning dependencies of target audiodev_PipeWire
[ 85%] Building C object audiodevs/PipeWire/CMakeFiles/audiodev_PipeWire.dir/pipewire.c.o
/home/*/looking-glass/looking-glass-B6-rc1-source/client/audiodevs/PipeWire/pipewire.c: In function ‘pipewire_init’:
/home/*/looking-glass/looking-glass-B6-rc1-source/client/audiodevs/PipeWire/pipewire.c:141:7: error: ‘PW_KEY_CONFIG_NAME’ undeclared (first use in this function); did you mean ‘PW_KEY_CORE_NAME’?
  141 |       PW_KEY_CONFIG_NAME, "client-rt.conf",
      |       ^~~~~~~~~~~~~~~~~~
      |       PW_KEY_CORE_NAME
compilation terminated due to -Wfatal-errors.
make[2]: *** [audiodevs/PipeWire/CMakeFiles/audiodev_PipeWire.dir/build.make:82: audiodevs/PipeWire/CMakeFiles/audiodev_PipeWire.dir/pipewire.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:849: audiodevs/PipeWire/CMakeFiles/audiodev_PipeWire.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
#### pipewire
```
~/looking-glass/looking-glass-B6-rc1-source/client$ pipewire --version
pipewire
Compiled with libpipewire 0.3.19
Linked with libpipewire 0.3.19
```

**Comment by gnif** [comment]
Closing as wontfix, this report is now two years old and modern distros should be running the later version of PipeWire now it has seen a stable release.
