### ISSUE TITLE
[Feature request] Touch screen support

### ISSUE THREAD

**Issue by Midou36O** [gnif/LookingGlass#1036]
Looking glass seems to not support touch screen input, (the mouse doesn't even go to where i touch the screen. Is it possible to it implement it?

**Comment by gnif** [comment]
Sorry not at this time, perhaps in the future but right now the demand for such a feature is practically nonexistent.

**Comment by Xyene** [comment]
For what's it's worth, this should work on Wayland (insofar as basic touch input, not gestures or anything like that).
