### ISSUE TITLE
spice audio in b6 no documention how switch betwin pulseaudio and  pipewire

### ISSUE THREAD

**Issue by Maziar123** [gnif/LookingGlass#1044]
HI 

Thanks for audio for B6 !

Seems some problem in B6  (B6-rc1-18-gfa6f1abaac) spice audio 

First, don't document how to select between PulseAudio & pipewire

I have PulseAudio and don't have pipewire ...

Then seems no sound ??

 seems only work with pipewire : 

`[I]   7499660413              main.c:1785 | main                           | Looking Glass (B6-rc1-18-gfa6f1abaac)
[I]   7499660438              main.c:1786 | main                           | Locking Method: Atomic
[I]   7499660762           cpuinfo.c:37   | lgDebugCPU                     | CPU Model: 12th Gen Intel(R) Core(TM) i9-12900H
[I]   7499660768           cpuinfo.c:38   | lgDebugCPU                     | CPU: 1 sockets, 14 cores, 20 threads
[I]   7499664949            config.c:559  | config_load                    | Loading config from: /home/mz/.looking-glass-client.ini
[I]   7499670404              main.c:1162 | lg_run                         | Using font: /usr/share/fonts/TTF/DejaVuSansMono.ttf
[I]   7499670460           ivshmem.c:128  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
[I]   7499675848             audio.c:159  | audio_init                     | Using AudioDev: PipeWire
[I]   7499675864                ps.c:245  | purespice_connect              | Connecting to socket 127.0.0.1:5900
[I]   7499681038               rsa.c:178  | rsa_encryptPassword            | Using Nettle
[I]   7499681399                ps.c:268  | purespice_connect              | Connected
[I]   7499681433             agent.c:103  | agent_connect                  | Connected to the spice guest agent
[I]   7499681467      channel_main.c:167  | onMessage_mainName             | Guest name: Win10-Elec2-With-GPU_LG_Spice
[I]   7499681487      channel_main.c:183  | onMessage_mainUUID             | Guest UUID: 6530ef08-af69-4720-be5c-37ffdda3c3c3
[I]   7499687784                ps.c:644  | ps_connectChannel              | RECORD channel connected
[I]   7499697023                ps.c:644  | ps_connectChannel              | PLAYBACK channel connected
[I]   7499704359                ps.c:644  | ps_connectChannel              | INPUTS channel connected
[I]   7499704398           channel.c:312  | onMessage_notify               | [notify] keyboard channel is insecure
[I]   7499704423              main.c:1293 | lg_run                         | Trying forced renderer
[I]   7499704477               egl.c:267  | egl_initialize                 | Double buffering is off
[I]   7499704488              main.c:1116 | tryRenderer                    | Using Renderer: EGL
[I]   7499705176               x11.c:230  | x11CheckEWMHSupport            | EWMH-complient window manager detected: KWin
[I]   7499709570               x11.c:463  | x11Init                        | X11 XInput 2.0 in use
[I]   7499713134               x11.c:1433 | x11GetEGLDisplay               | Using eglGetPlatformDisplayEXT
[I]   7499756722               egl.c:745  | egl_renderStartup              | Multisampling enabled, max samples: 4
[I]   7499757689               egl.c:828  | egl_renderStartup              | Single buffer mode
[I]   7499760875               egl.c:855  | egl_renderStartup              | EGL     : 1.5
[I]   7499760892               egl.c:856  | egl_renderStartup              | Vendor  : Intel
[I]   7499760902               egl.c:857  | egl_renderStartup              | Renderer: Mesa Intel(R) Graphics (ADL GT2)
[I]   7499760913               egl.c:858  | egl_renderStartup              | Version : OpenGL ES 3.2 Mesa 22.2.3
[I]   7499760932               egl.c:859  | egl_renderStartup              | EGL APIs: OpenGL OpenGL_ES 
[I]   7499760953               egl.c:930  | egl_renderStartup              | Debug messages disabled, enable with egl:debug=true
[I]   7499783531           eglutil.c:35   | swapWithDamageInit             | Using EGL_KHR_swap_buffers_with_damage
[I]   7499981150              main.c:1566 | lg_run                         | Guest Information:
[I]   7499981236              main.c:1567 | lg_run                         | Version  : B6-rc1-18-fa6f1aba
[I]   7499981296              main.c:1588 | lg_run                         | UUID     : 6530ef08-af69-4720-be5c-37ffdda3c3c3
[I]   7499981434              main.c:1597 | lg_run                         | CPU Model: 12th Gen Intel(R) Core(TM) i9-12900H
[I]   7499981524              main.c:1598 | lg_run                         | CPU      : 1 sockets, 9 cores, 18 threads
[I]   7499981600              main.c:1600 | lg_run                         | Using    : DXGI Direct3D 11
[I]   7499981668              main.c:1636 | lg_run                         | OS       : Windows
[I]   7499981741              main.c:1638 | lg_run                         | OS Name  : Windows 10 Pro (Build: 19044) 
[I]   7499981817              main.c:1660 | lg_run                         | Starting session
[I]   7500671579              main.c:698  | main_frameThread               | Format: FRAME_TYPE_BGRA 3840x2160 stride:3840 pitch:15360 rotation:0
[I]   7500905905              main.c:698  | main_frameThread               | Format: FRAME_TYPE_BGRA 3840x2160 stride:3840 pitch:15360 rotation:0
`

**Comment by netboy3** [comment]
The audio back-end is not user selectable and as such there is nothing to document. Looking-Glass will try to use Pipewire first and if not present will fail back to PulseAudio.

```
[I] 7499675848 audio.c:159 | audio_init | Using AudioDev: PipeWire
```

You probably have a broken Pipewire service that causes LG to successfully connect to it, but not work. This is not a bug.

As you were reminded when you've initially opened this issue:

If you are looking for help or support please use one of the following methods

Create a New Topic on the Level1Tech's forum under the Looking Glass category:
* https://forum.level1techs.com/c/software/lookingGlass/142

Ask for help in the Looking Glass discord server
* https://discord.gg/52SMupxkvt

**Comment by Maziar123** [comment]
Hi

I don't need support for it, think user can select manually between pipewire & PulseAudio

and need PulseAudio, perhaps preferred for audio when available 

Also, nice if user can select manually it ...

**Comment by netboy3** [comment]
The vast majority of users do not need such functionality so such a request will have very low priority if at all considered. Pipewire and PulseAudio do not live well together as they compete over exclusive locks of ALSA devices. A properly installed Linux system will either have only native PulseAudio or only Pipewire. If a Pipewire user requires PulseAudio compatibility, Pipewire can emulate a PulseAudio server so there's no need for a separate, native PulseAudio server. PulseAudio emulation in Pipewire was done to allow backwards compatibility for applications that do not have native Pipewire support. As LG does have native support, a user with properly installed Pipewire will have no need to switch to PulseAudio.

**Comment by Maziar123** [comment]
See Manjaro KDE

Enable both service by default, but pipewire in default not work !

**Comment by netboy3** [comment]
Manjaro is known to make some bad decisions, and if it's installing PulseAudio together with a broken Pipewire by default, it sure is one of those bad decisions. LG can not be expected to fix problems caused by broken distributions. You might want to try to simply stop the broken Pipewire service so that applications (such as LG) will not try to use it.
