### ISSUE TITLE
Configuration file not found or invalid

### ISSUE THREAD

**Issue by Airmancooma** [gnif/LookingGlass#1046]
Hi this is my problem. How can I solve? 
Configuration file not found or invalid

![Capture](https://user-images.githubusercontent.com/107194958/203837337-dc31242d-cbc1-48c6-893a-9ad6e1707cc5.PNG)

**Comment by gnif** [comment]
1. This is not an error
2. Issues are not for support, join us on discord (https://looking-glass.io/discord) or Level1Techs.
