### ISSUE TITLE
Compilation error: FRAME_TYPE_H264 undeclared

### ISSUE THREAD

**Issue by capsensitive** [gnif/LookingGlass#105]
### Required information

Host CPU: Intel Core i7 7700HQ
Host GPU: Intel HD Graphics 630
Guest GPU: NVIDIA Quadro P4000 (mobile)
Host Kernel version: 4.19.4
Host QEMU version: 3.0.0

I'm trying to compile current `HEAD`, but I had the following error message:
```
/tmp/makepkg/looking-glass-git/src/looking-glass/client/main.c: In function ‘frameThread’:
/tmp/makepkg/looking-glass-git/src/looking-glass/client/main.c:397:12: error: ‘FRAME_TYPE_H264’ undeclared (first use in this function); did you mean ‘FRAME_TYPE_MAX’?
       case FRAME_TYPE_H264:
            ^~~~~~~~~~~~~~~
            FRAME_TYPE_MAX
```

**Comment by gnif** [comment]
Sorry about that, I will fix this. FRAME_TYPE_H264 has been removed for now
