### ISSUE TITLE
LookingGlass viewer does not go into full-screen mode with -F parameter

### ISSUE THREAD

**Issue by fubar-1** [gnif/LookingGlass#1050]
Starting looking-glass-viewer with -F parameter doesn't work correctly when the host is running the plasma-wayland desktop.  Instead it displays the window in the upper-left corner of the screen, about 1/6 the proper size.

Hitting scroll-lock-f twice (once to exit the broken full-screen mode, then again to re-enter full-screen mode) does resolve the problem, so it's just a minor irritation.

This is running the viewer built from git master (as of 12/2/2022) and the latest pre-built Windows guest (host) server as of 12/2/22 on Kubuntu 22.10 with plasma-workspace-wayland installed on a 12900K/iGPU motherboard HDMI 2.0 connected to an LG C1 display at 4K resolution.  Guest is set to 4K video output.

Nothing unusual is logged by the viewer.  Details available on request.

**Comment by gnif** [comment]
Not a LG fault, we properly set the hints and request the mode on startup. Please ask in future in the support channels before opening issues.
