### ISSUE TITLE
[FR] Add an fpsMax parameter for when vsync is disabled to prevent excessive resource usage.

### ISSUE THREAD

**Issue by Asmageddon** [gnif/LookingGlass#1053]
As per title. On my machine, with vsync off, LG uses up to 15% of my host CPU and presumably a measurable amount of GPU for no real benefit - my display is incapable of displaying >1000 FPS.

**Comment by gnif** [comment]
LG doesn't "generate frames", it captures the frames your title is making as it makes them, you need to limit the FPS of the title.

**Comment by gnif** [comment]
sorry just realised you're talking about the client app, not the host app.
