### ISSUE TITLE
Add automatic resolution setting based on window size via spice

### ISSUE THREAD

**Issue by marmeladapk** [gnif/LookingGlass#1059]
Potential use cases: 
- Moving LG window to another monitor with different resolution
- resizing window to fit another, native application on the same monitor

I work with a single CAD application on Windows and sometimes I need to switch between VM and linux applications. 

As a sidenote, thank you for your work on Looking Glass!

**Comment by gnif** [comment]
This has been requested and rejected multiple times.
https://github.com/gnif/LookingGlass/issues/567

Note that funding has been provided and a new version of the host is currently in the research stage that should be able to perform this.
