### ISSUE TITLE
Host application closing after changing resolution

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#106]
I have this weird issue where if i change the resolution then the host application refuses to run.
Pretty much just closes constantly, no crash dumps that i can see or know of.

I can run with the 1440x900@75hz resolution without issues.
Soon as i change to 1366x768@60hz it seems to cause the issue.
I'm not seeing anything out of the ordinary that i know of but here is the console log.

```
[I]     CaptureFactory.h:83   | CaptureFactory::DetectDevice   | Trying DXGI
[I]             DXGI.cpp:232  | Capture::DXGI::Initialize      | Device Descripion: NVIDIA GeForce GTX 1050
[I]             DXGI.cpp:233  | Capture::DXGI::Initialize      | Device Vendor ID : 0x10de
[I]             DXGI.cpp:234  | Capture::DXGI::Initialize      | Device Device ID : 0x1c81
[I]             DXGI.cpp:235  | Capture::DXGI::Initialize      | Device Video Mem : 1977 MB
[I]             DXGI.cpp:236  | Capture::DXGI::Initialize      | Device Sys Mem   : 0 MB
[I]             DXGI.cpp:237  | Capture::DXGI::Initialize      | Shared Sys Mem   : 3070 MB
[I]             DXGI.cpp:241  | Capture::DXGI::Initialize      | Capture Size     : 1440 x 900
[I]             DXGI.cpp:298  | Capture::DXGI::Initialize      | Feature Level    : 0xc100
[I]             DXGI.cpp:335  | Capture::DXGI::Initialize      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
[I]     CaptureFactory.h:86   | CaptureFactory::DetectDevice   | Using DXGI
[I]          Service.cpp:125  | Service::InitPointers          | Total Available :  32 MB
[I]          Service.cpp:126  | Service::InitPointers          | Max Cursor Size :   1 MB
[I]          Service.cpp:127  | Service::InitPointers          | Max Frame Size  :  15 MB
[I]          Service.cpp:128  | Service::InitPointers          | Cursor          : 00000227CDDE0080 (0x00000080)
[I]          Service.cpp:134  | Service::InitPointers          | Frame 0         : 00000227CDEE0080 (0x00100080)
[I]          Service.cpp:134  | Service::InitPointers          | Frame 1         : 00000227CEE60000 (0x01080000)
[I]             DXGI.cpp:654  | Capture::DXGI::Capture         | Pixel Format     : DXGI_FORMAT_B8G8R8A8_UNORM
```

**Host CPU:** AMD Ryzen 5 1600
**Host GPU:** AMD Radeon WX2100
**Guest GPU:** NVIDIA GeForce GTX 1050
**Host Kernel version:** 4.18.0-12-generic
**Host QEMU version:** 2.12.0

**Comment by gnif** [comment]
Thanks, looks like there is noting untoward in the log, I will try to replicate this and investigate.

**Comment by gnif** [comment]
Thanks, this is helpful, it is likely a padding/pitch issue with the memory copy. I am away for a few days so I will not be able to look into it just yet I am sorry.

**Comment by 8BallBomBom** [comment]
Just tested random ranges of resolutions from 800x600 all the way to 1920x1080
It would appear 1360x768 works no worries and everything else so far seems to work.
Only 1366x768 causing the host to die so far.

**Comment by gnif** [comment]
This is fixed, please be sure to update both the host and the client application.

**Comment by 8BallBomBom** [comment]
Thanks :+1:
