### ISSUE TITLE
Arguments do not apply in LG client

### ISSUE THREAD

**Issue by gimdh** [gnif/LookingGlass#1072]
### Environment
Proxmox VE hosts both Windows VM (LG host) and Debian 11 VM (LG client). I have built Linux client by following the guide, without pipewire support (Due to issue https://github.com/gnif/LookingGlass/issues/1033). I have installed looking-glass-client globally. 

### Issue
Launching looking-glass-client with arguments do not work. The log clearly states that it is ignoring invalid arguments, which is not. I can successfully launch LG client with following /etc/looking-glass-client.ini.

```
[app]
shmFile=/dev/kvmfr0

[spice]
host=10.0.0.1
port=11111
```

### Command input and output
```
» looking-glass-client -f /dev/kvmfr0 -c 10.0.0.1 -p 11111                                                                                   
[I]   1902084216              main.c:1837 | main                           | Looking Glass (B6-50-g9d66a68403)
[I]   1902084229              main.c:1838 | main                           | Locking Method: Atomic
[I]   1902084317           cpuinfo.c:37   | lgDebugCPU                     | CPU Model: 13th Gen Intel(R) Core(TM) i7-13700K
[I]   1902084321           cpuinfo.c:38   | lgDebugCPU                     | CPU: 1 sockets, 8 cores, 16 threads
[I]   1902087011            config.c:545  | config_load                    | Loading config from: /etc/looking-glass-client.ini
[W]   1902087109            option.c:377  | option_parse                   | Ignored invalid argument: /dev/kvmfr0
[W]   1902087113            option.c:377  | option_parse                   | Ignored invalid argument: 10.0.0.1
[W]   1902087115            option.c:377  | option_parse                   | Ignored invalid argument: 11111
[I]   1902089295              main.c:1164 | lg_run                         | Using font: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
[I]   1902089527           ivshmem.c:128  | ivshmemOpenDev                 | KVMFR Device     : -f
[E]   1902089539           ivshmem.c:149  | ivshmemOpenDev                 | Failed to stat: -f
[E]   1902089545           ivshmem.c:150  | ivshmemOpenDev                 | No such file or directory
[E]   1902089549              main.c:1232 | lg_run                         | Failed to map memory
```

**Comment by EvGem7** [comment]
There was a piece of work connected to the issue: https://github.com/gnif/LookingGlass/pull/1071
Not sure if this is already fixed.

**Comment by EvGem7** [comment]
You have a trailing space in the host option. Try to remove it.
![image](https://user-images.githubusercontent.com/33933105/235731183-d447a4d2-6a15-4805-8fae-40d7e33aafdc.png)

**Comment by gimdh** [comment]
> 

Thanks. I am on `B6-50-g9d66a68403` so I believe this is up to date main branch for now.

BTW, I want to clarify that the issue is not able to use arguments. In fact, ini file works just fine even with trailing space.

**Comment by EvGem7** [comment]
Oh. I misread something and thought you have an issue similar to mine. Sorry about that

**Comment by gimdh** [comment]
Never mind. I wonder if you are able to set shmem file with -f argument.

**Comment by gimdh** [comment]
Thanks! I'll leave the issue open for the record.

**Comment by gnif** [comment]
Fix applied, thanks @netboy3 .
Closing
