### ISSUE TITLE
Not building on Devuan (Debian) - ‘SPA_VIDEO_FORMAT_xBGR_210LE’ undeclared

### ISSUE THREAD

**Issue by aguythere** [gnif/LookingGlass#1079]
(C)Make Version:
```
cmake version 3.18.4
GNU Make 4.3
Built for x86_64-pc-linux-gnu
```

GCC Version:
```
gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
```

OS Version:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Devuan
Description:	Devuan GNU/Linux 4 (chimaera)
Release:	4
Codename:	chimaera
```
Kernel Version:
```
uname -r
5.10.0-23-amd64
```

CMake output:
```
/looking-glass-B6/host/build$ cmake -DENABLE_BACKTRACE=0 ../
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCH_X86_64_V2
-- Performing Test COMPILER_SUPPORTS_MARCH_X86_64_V2 - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'gio-2.0;gio-unix-2.0;libpipewire-0.3;libspa-0.2'
--   Found gio-2.0, version 2.66.8
--   Found gio-unix-2.0, version 2.66.8
--   Found libpipewire-0.3, version 0.3.19
--   Found libspa-0.2, version 0.2
-- The following features have been enabled:

 * USE_XCB, XCB/XSHM capture backend.
 * USE_PIPEWIRE, Pipewire Screencast capture backend.

-- The following features have been disabled:

 * OPTIMIZE_FOR_NATIVE, Optimized for x86-64-v2
 * ENABLE_BACKTRACE, Backtrace support.
 * ENABLE_ASAN, AddressSanitizer support.
 * ENABLE_UBSAN, UndefinedBehaviorSanitizer support.

-- Configuring done
-- Generating done
-- Build files have been written to: looking-glass-B6/host/build
```

Make output:
```
looking-glass-B6/host/build$ make
Scanning dependencies of target lg_common_platform_code
[  2%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/debug.c.o
[  4%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/crash.c.o
[  6%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/sysinfo.c.o
[  9%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/thread.c.o
[ 11%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/event.c.o
[ 13%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/ivshmem.c.o
[ 16%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/time.c.o
[ 18%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/paths.c.o
[ 20%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/open.c.o
[ 23%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/cpuinfo.c.o
[ 25%] Linking C static library liblg_common_platform_code.a
[ 25%] Built target lg_common_platform_code
Scanning dependencies of target lg_common
[ 27%] Building C object common/CMakeFiles/lg_common.dir/src/appstrings.c.o
[ 30%] Building C object common/CMakeFiles/lg_common.dir/src/stringutils.c.o
[ 32%] Building C object common/CMakeFiles/lg_common.dir/src/stringlist.c.o
[ 34%] Building C object common/CMakeFiles/lg_common.dir/src/option.c.o
[ 37%] Building C object common/CMakeFiles/lg_common.dir/src/framebuffer.c.o
[ 39%] Building C object common/CMakeFiles/lg_common.dir/src/KVMFR.c.o
[ 41%] Building C object common/CMakeFiles/lg_common.dir/src/countedbuffer.c.o
[ 44%] Building C object common/CMakeFiles/lg_common.dir/src/rects.c.o
[ 46%] Building C object common/CMakeFiles/lg_common.dir/src/runningavg.c.o
[ 48%] Building C object common/CMakeFiles/lg_common.dir/src/ringbuffer.c.o
[ 51%] Building C object common/CMakeFiles/lg_common.dir/src/vector.c.o
[ 53%] Building C object common/CMakeFiles/lg_common.dir/src/cpuinfo.c.o
[ 55%] Building C object common/CMakeFiles/lg_common.dir/src/debug.c.o
[ 58%] Building C object common/CMakeFiles/lg_common.dir/src/ll.c.o
[ 60%] Linking C static library liblg_common.a
[ 60%] Built target lg_common
Scanning dependencies of target capture_pipewire
[ 62%] Building C object platform/Linux/capture/pipewire/CMakeFiles/capture_pipewire.dir/src/pipewire.c.o
In file included from /usr/include/spa-0.2/spa/pod/builder.h:36,
                 from looking-glass-B6/host/platform/Linux/capture/pipewire/src/pipewire.c:32:
/looking-glass-B6/host/platform/Linux/capture/pipewire/src/pipewire.c: In function ‘startStream’:
/looking-glass-B6/host/platform/Linux/capture/pipewire/src/pipewire.c:99:7: error: ‘SPA_VIDEO_FORMAT_xBGR_210LE’ undeclared (first use in this function); did you mean ‘SPA_VIDEO_FORMAT_GBR_10LE’?
   99 |       SPA_VIDEO_FORMAT_xBGR_210LE, SPA_VIDEO_FORMAT_RGBA_F16),
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [platform/Linux/capture/pipewire/CMakeFiles/capture_pipewire.dir/build.make:82: platform/Linux/capture/pipewire/CMakeFiles/capture_pipewire.dir/src/pipewire.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:501: platform/Linux/capture/pipewire/CMakeFiles/capture_pipewire.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Not sure what to do....

**Comment by gnif** [comment]
Devuan is not Debian, it's a fork. This issue is because you're using a version of PipeWire that is too old. This project only officially supports Debian, if you need further help please ask the community on either the L1Tech forums or on the LG discord.

**Comment by aguythere** [comment]
Thanks for letting me know. You may want to do version checks in the future so people like me don't mistakenly make error reports.

To install on Chimaera, follow the instructions on building from host on the official site, but using the Daedalus repositories. Also, you'll have to install:
```
libxcb-shm0-dev
libxcb-xfixes0-dev
```
using those same  Daedalus repositories. Note this **will** upgrade libc so you're _**very**_ likely to have issues and glitches. I so far have encountered no issues myself, however.

Also, Devuan is simply Debian without the hard dependency on systemd (also they've been trying to decouple dependencies on udev though as far as I am aware have been unsuccessful thusfar). Otherwise it's entirely cross-compatible with Debian. In fact, if you really want/need to, you can install Debian packages on Devuan with little/no issue. Though it's obviously discouraged.

**Comment by gnif** [comment]
> You may want to do version checks in the future so people like me don't mistakenly make error reports

Noted

> Devuan is simply Debian without the hard dependency on systemd

If that is true, then the following statements are false.

> **Also, you'll have to install**

> **Otherwise** it's entirely cross-compatible with Debian

> you can install Debian packages on Devuan with little/no issue. Though it's obviously discouraged.

Ubuntu made the same claims early on. While I appreciate what you're saying, Devuan != Debian.

**Comment by aguythere** [comment]
> If that is true, then the following statements are false.
> 
> > **Also, you'll have to install**
Do you not have to do the same on Debian? I think I simply didn't have them installed or they didn't automatically get pulled. Synaptic showed them as uninstalled, but their non-dev counterparts were. This seems to be a common error even on Debian far as I'm aware.

**Comment by gnif** [comment]
Ah, sorry I just realised what I missed here, you're building the Linux host application which we have no official support for, which is why it's not documented at all. You do not need or want the Linux host app if you have a Windows guest, which is all we currently provide documentation and support for.

**Comment by gnif** [comment]
:shrug: this is why we run Windows in a VM.... this way it doesn't matter what they do.

> Steam is not longer allowing it's client to boot on anything older than win10 (which is just plain ludicrous)

I disagree, maintaining software for old releases of windows becomes harder as times progresses to the point where you're spending more time working around missing APIs in later windows releases, then actually writing your application.

**Comment by aguythere** [comment]
> shrug this is why we run Windows in a VM.... this way it doesn't matter what they do.
Indeed.

> I disagree, maintaining software for old releases of windows becomes harder as times progresses to the point where you're spending more time working around missing APIs in later windows releases, then actually writing your application.
At the very least, though, they could allow it to **boot**. I mean if it still doesn't boot, or it has issues, so be it. This is just like adobe and flash. If it's booting don't impound it.

**Comment by gnif** [comment]
> they could allow it to boot

Sorry but this is not how applications work on windows. If you link your application to a DLL with an export (API) you intend to use, the windows PE loader will refuse to run the application knowing it will break things. Dynamically detecting this at runtime and working around it (like I stated earlier) is possible, but dramatically increases the developer workload as you now have to add code to handle and cope with failures due to missing support from the OS.

**Comment by aguythere** [comment]
> Sorry but this is not how applications work on windows.
> 
Don't see why not. I have a firefox USB version from like 2009 I boot for giggles sometimes and with a little rejiggering it will run even on 8. Probably not 10 though.

Why not allow the user to **try**? It's not like you support it anymore. Worst case Windows tells them to F*** off and that's the end of it.

> In short there is no just "allow it to boot"
>
Suppose we'll have to agree to disagree on this.

**Comment by gnif** [comment]
> Don't see why not. I have a firefox USB version from like 2009 I boot for giggles sometimes and with a little rejiggering it will run even on 8. Probably not 10 though.

This is ENTIRELY different. You're talking about running OLD software on a NEW OS. Steam is NOT old software, it's continually updated and maintained and is NEW software always.

> Suppose we'll have to agree to disagree on this.

Or you can just learn how the windows PE loader works and understand that it's an impossibility for NEW software using NEW API calls in the OS to be allowed to "just work" without any additional work.
