### ISSUE TITLE
[client] RFE: Add minimize client window hotkey

### ISSUE THREAD

**Issue by Lanchon** [gnif/LookingGlass#1081]
hi,

when using LG client in full screen, it is awkward to switch back and forth to the host OS desktop.

right now i have to:
- disable capture (SCRLK)
- disable fullscreen (SCRLK+F)
- minimize the window

then:
- restore window
- enable fullscreen
- enable capture

with current software, it is just easier to `SCRLK+Q` and then relaunch the client when returning to the VM; less than ideal.

a new hotkey (maybe `SCRLK+Z`) could solve this by disabling capture if needed and minimizing, then full screening and restoring capture state when switching back to the window.

on the topic of capture, maybe a config option could be considered for auto capturing and restoring on entry and exit of full screen, as for many users capture is always preferred while in full screen.

btw, for these proposed automatic capture state changes (as well as for `captureOnStart=yes`), it seems a bit redundant to spam the user with OSD messages about these state changes.

oh and thanks for LG, it's working great!

**Comment by gnif** [comment]
We do not use issues for feature enhancement requests, please come into discord and discuss what you want there.
http://looking-glass.io/discord

> for many users capture is always preferred while in full screen.

This is the first time this has ever been requested, I wouldn't say "for many users".

**Comment by Lanchon** [comment]
well you need to update your issue template then. right now it says:

> ### Issues are for Bug Reports and Feature Requests Only!
>
> [...]
>
> *Issues that are not bug reports or feature requests will be closed & ignored*

btw, it was on discord that i started typing this as a new post, but then i checked around the project and came to the conclusion that the right place for RFEs was here. thanks anyway.

**Comment by gnif** [comment]
> well you need to update your issue template then. right now it says:

You are correct I am sorry. But as you are on Discord discuss what you would like changed with the community there. LG features are implemented based on level of demand and complexity of maintaining the features/changes.

**Comment by Lanchon** [comment]
sure thanks :)
