### ISSUE TITLE
[Request] Ability to NOT capture certain keys

### ISSUE THREAD

**Issue by Asmageddon** [gnif/LookingGlass#1084]
In my specific use case, the media keys, or ScrollLock remapped to act as Play/Pause with `.Xmodmap`.

**Comment by gnif** [comment]
the wayland and xorg APIs do not allow this, it is not possible.

**Comment by Asmageddon** [comment]
@gnif Would it be possible to instead un-capture input, fire an xorg/Wayland event for the key, and re-capture input?

**Comment by gnif** [comment]
In theory yes, but such a hack would never be accepted into this project I am sorry.

**Comment by Asmageddon** [comment]
I understand. In lieu of that, could I request the ability to reposition the "Capture enabled" popup, so that it is not obtrusive when capture is toggled?

**Comment by gnif** [comment]
If you like you can actually disable it with `win:alerts=no`
