### ISSUE TITLE
CPU performance hit

### ISSUE THREAD

**Issue by t0msk** [gnif/LookingGlass#109]
Hello, I'm very happy to see this project, it is awesome, because I would like to switch to Linux completely without dual boot, but I have question and suggestion about CPU performance hit.

I was asking some questions at https://forum.level1techs.com/t/questions-about-looking-glass/127078/6

And I was interested in CPU / RAM Performance hit too (I have i5 4670, so I don't know what is CPU load for my system) and one man answered me that:

> Expect to be able to dedicate one core to looking glass.

Is it true that LookingGlass is too CPU hungry that I whould dedicate whole CPU core only for frame coping?

And he replied this too:

> I’ve not experienced much more than 30% utilization between the Windows Agent and the Linux “Server”, but some people have experienced more.

In my opinion 30% CPU load for frame coping is too much, so there goes my suggestion.

As far as I know, GPU doesn't have direct access into RAM, but iGPU does, and let's be honest, most people use iGPU on host machine, so what if reading and displaying frame from shared memory would do iGPU insted of CPU? Maybe it could decrease CPU load.

**Comment by gnif** [comment]
This is not the place to ask these questions, please use the forum as instructed.
