### ISSUE TITLE
[Feature Request/Client] Do not wait for the server

### ISSUE THREAD

**Issue by awsms** [gnif/LookingGlass#1090]
I often use LG as a spice client only, and when I'm doing so I'm always facing the 2 pop-ups (triggered at https://github.com/gnif/LookingGlass/blob/82607a7d6f264761b8d514cd5c7354df01b23a21/client/src/main.c#L1478).
Could we have an optional flag, spice:exclusive or something like that, so LG won't ever wait for the server on the guest machine?

**Comment by gnif** [comment]
I am sorry but no, LG was never intended to be used in this manner, as such the spice video transport is very primitive and sub optimal in many ways, it's literally there as a fallback mechanism and not intended for daily use.
