### ISSUE TITLE
Fancy buffer mapping vs simple glTexImage2D

### ISSUE THREAD

**Issue by kiljacken** [gnif/LookingGlass#11]
Hey! Great work on the software, I've been needing something like this so bad.

As the default opengl code seems to bottleneck me quite heavily, I tried pulling out all the fancy persistent buffer mapping and replacing it with a simple glTextImage2D with a stride, like this:

```
glPixelStorei(GL_UNPACK_ROW_LENGTH, this->format.stride);
  glTexImage2D(
    GL_TEXTURE_2D,
    0,
    this->intFormat,
    this->format.width,
    this->format.height,
    0,
    this->vboFormat,
    GL_UNSIGNED_BYTE,
    data
  );
```

I thought I would share my findings, as it has increased the throughput of lookingglass a lot on my setup.

EDIT:
Thought it might be prudent to share what kind of hardware I'm running on to see these results. 

CPU: i5-6600k
RAM: 4x8GB Kingston HyperX Fury DDR4-2133
Host GPU: RX 580
VM GPU: GTX970

**Comment by gnif** [comment]
Thanks, but unfortunately that kills performance on NVidia GPUs, Vulkan should resolve this giving us the best of both.

**Comment by kiljacken** [comment]
Sure! I just wanted to share in case anybody was using a config like mine
and experiencing issues. My changes are public in a fork on my GitHub.

The amdgpu driver probably hits a fast path in this instance and directly
DMA's the data to GPU, saving the additional memcpy

**Comment by gnif** [comment]
You can now opt to use this method, it is based on your patch with a few minor alterations, like the continued use of `glTexSubImage2D` so that the texture is not re-created on each iteration.

**Comment by kiljacken** [comment]
Awesome. Thanks man, keep up the awesome work.
