### ISSUE TITLE
Mention G-Sync in documentation

### ISSUE THREAD

**Issue by Ste-Mich** [gnif/LookingGlass#1102]
I could not find any information regarding G-Sync in the Github issues here, the documentation nor could I get a response in the Discord channel. I think it would be useful to mention G-Sync support in the docs FAQ page.

Currently I'am running a VM with direct DisplayPort output from my graphics card into my G-Sync monitor. It works great, but I would like to use Looking Glass. Would G-Sync still work with Looking Glass?

**Comment by gnif** [comment]
1) GitHub issues are for issues, not general questions.
2) LG renders frame to the screen like any other application, it's up to your compositor or desktop environment to support things like gsync, it's completely out of scope for this application.
