### ISSUE TITLE
Release 2024

### ISSUE THREAD

**Issue by ShalokShalom** [gnif/LookingGlass#1109]
Is there a reason, to withhold a new release?

I realize, you had picked up the app after some while, and might be in a refactoring process, could you please say something about the next release date?

Seems like it would warrant at least a new beta 8.

**Comment by Dardrai** [comment]
It is actually in the pre release phase / tagged https://github.com/gnif/LookingGlass/releases/tag/B7-rc1 (2ddays ago!) 
Testing and fixing of the latest found bugs is needed but yeah thats the release candidate for b7 release!

**Comment by ShalokShalom** [comment]
Thanks a ton

**Comment by gnif** [comment]
Please note that while it may have appeared that the project had stalled due to lack of commits to the repository, months of R&D efforts have gone into the new code that has become the D12 capture interface. Lack of commits does not imply a lack of work on the project.

**Comment by ShalokShalom** [comment]
That could have been communicated!

**Comment by gnif** [comment]
This is an open source passion project with no corporation behind it. If you want to know the current state of things you could always have joined the LG discord server where all development and support is performed.
