### ISSUE TITLE
Failed to map segment from shared object when loading libSDL2_ttf-2.0.so.0

### ISSUE THREAD

**Issue by hypnomaki** [gnif/LookingGlass#111]
### Required information

Host CPU: `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`
Host GPU: `GeForce GTX 1080`
Guest GPU: `-`
Host Kernel `version: 4.18.0-13-generic`
Host QEMU version: `2.12.0`

Cannot start program, aborts with error `./looking-glass-client: error while loading shared libraries: libSDL2_ttf-2.0.so.0: failed to map segment from shared object`
(I cant even get to the help message output)

Executing with strace gives me the following output
`execve("./looking-glass-client", ["./looking-glass-client"], 0x7ffcf6df7e60 /* 88 vars */) = 0
brk(NULL)                               = 0x557c396e0000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=210347, ...}) = 0
mmap(NULL, 210347, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f3064629000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\32\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=31008, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3064627000
mmap(NULL, 2126176, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = -1 EACCES (Permission denied)
close(3)                                = 0
writev(2, [{iov_base="./looking-glass-client", iov_len=22}, {iov_base=": ", iov_len=2}, {iov_base="error while loading shared libra"..., iov_len=36}, {iov_base=": ", iov_len=2}, {iov_base="libSDL2_ttf-2.0.so.0", iov_len=20}, {iov_base=": ", iov_len=2}, {iov_base="failed to map segment from share"..., iov_len=40}, {iov_base="", iov_len=0}, {iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 10./looking-glass-client: error while loading shared libraries: libSDL2_ttf-2.0.so.0: failed to map segment from shared object
) = 125
exit_group(127)                         = ?
+++ exited with 127 +++
`

It looks like `mmap(NULL, 2126176, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0)` will not get the desired permissions but its not from the source code of looking-glass?

I guess this is some 3rd party issue but I dont know where to start. Please help!

Im using the lastest ubuntu `18.10` and have everything updated.
Also, Im using the latest code from the repository. 
When using the penultimate release `a11` I got the same error but with a different lib `librt.so.1`

On Ubuntu, apparmor is installed.
Thats why I introduced the rule which should recursively allow everything
`
profile looking-glass-client /opt/LookingGlass/client/build/looking-glass-client {
        /** rw,
}
`

**Comment by gnif** [comment]
You're crash is in libSDL2, this is not a LG issue.
