### ISSUE TITLE
Host sleep or hibernation causes looking-glass-client refresh rate to become extremely low

### ISSUE THREAD

**Issue by Mejituu** [gnif/LookingGlass#1111]
The host sleeps or hibernates, causing the refresh rate of looking-glass-client to become extremely low. Moving the mouse feels like the screen jumps, similar to ppt. But closing and reopening looking-glass-client returns to normal.

--------------------

主机睡眠或者休眠导致looking-glass-client刷新率变得极低，移动鼠标就跟画面跳跃一样，类似于ppt。不过关闭并重新打开looking-glass-client就恢复正常了。

--------------------

OS: Debian GNU/Linux trixie/sid x86_64
DE: Plasma 5.27.10
WM: KWin
CPU: Intel i7-10875H (16) @ 5.100GHz
GPU: Intel CometLake-H GT2 [UHD Graphics]
GPU: NVIDIA GeForce RTX 2060 Mobile
Memory: 23332MiB / 64054MiB

Server Name: PulseAudio (on PipeWire 1.0.3)
Default Sample Specification: float32le 2ch 48000Hz

**Comment by gnif** [comment]
We do not support hibernation and/or sleep. It causes timing jumps that we simply can not account for that breaks things, usually involving the guest GPU drivers.
