### ISSUE TITLE
'looking-glass-host-B7-rc1' detected as virus by Windows Defender and Virus Total

### ISSUE THREAD

**Issue by BentHaase** [gnif/LookingGlass#1118]
The latest RC version of the client `looking-glass-host-B7-rc1` (.zip) downloaded from the official downloads page (https://looking-glass.io/downloads) is being flagged by Windows defender upon launching `looking-glass-host-setup` as a virus as well as being detected by three independent sources on [Virustotal](https://www.virustotal.com/gui/file/18183f2f5932478c4f509bbb54f2b054a8aee95bb8c262905b83af8057983167):

![image](https://github.com/gnif/LookingGlass/assets/5788982/b783fe90-3adc-4c9c-aa8f-ddb56c6ce6e6)
![image](https://github.com/gnif/LookingGlass/assets/5788982/6de31060-a5d4-402b-b1d1-35c9f7773329)

Even though this is likely a false positive, this is highly concerning especially keeping all the recent security events in mind.

The same does not happen for the much older B6 version. There have been issues in the past regarding this topic but they are closed and been inactive for months / years which is why I am opening another similar issue.

How can we properly reassure that 'this is fine'?

EDIT: Host, Windows 11 Pro 23H2 (`OS Build 22631.3296`)

**Comment by gnif** [comment]
This is very strange, we are signing the binary to ensure that this doesn't false flag. As for how safe it is, 100%, we do not even build this binary on Windows.

**Comment by gnif** [comment]
As there is nothing we can do to resolve this, I am closing this as invalid. Please contact the AV vendors and complain, if enough people do they might actually fix their buggy detection definitions.
