### ISSUE TITLE
Key repeat does not work

### ISSUE THREAD

**Issue by KurokiTenma** [gnif/LookingGlass#1123]
Holding down a key on the keyboard does not make it repeat in the guest OS.
LG client configuration options releated to [input] are left on default.
If I remember corectly this worked in LG beta 5.0.1.

Host CPU: AMD Ryzen 5900X
Host GPU: AMD Radeon RX6600
Host kernel: 5.19.0-50-generic
QEMU version: 6.2.0
Guest GPU: Nvidia RTX 3060
Guest OS: Windows 10
Looking Glass version: B7-rc1

**Comment by gnif** [comment]
Add the virtio-keyboard to your VM configuration as per the LG documentation.
https://looking-glass.io/docs/B7-rc1/install_libvirt/#keyboard-mouse-display-audio

**Comment by gnif** [comment]
And you installed the drivers in windows for it? Check device manager.
Please though come to the LG discord for support, we do not provide support via GitHub issues.
