### ISSUE TITLE
Windows 11 guest randomly crashes

### ISSUE THREAD

**Issue by doonv** [gnif/LookingGlass#1128]
I use Looking Glass to run Rust via Windows 11. But I experience frequent crashes on the guest. When a crash happens, the game freezes for a split second, then I see a blank purple background with the looking glass logo.   `virt-manager` still shows the VM as running, and Windows does not automatically restart (I think, it may just be really slow).

Configuration: 
- OS: Arch Linux
- Kernel: 6.9.3-arch1-1
- CPU: 13th Gen Intel Core i5-13400
- Memory: 16GB (13GB allocated for VM)
- Host GPU: Intel UHD Graphics 730 (iGPU)
- Guest GPU: NVIDIA RTX 3060
- QEMU Version: 9.0.0

**Comment by netboy3** [comment]
Please note that GitHub issues here should only be used to report Looking-Glass bugs. VM slowness/crashes have nothing to do with LG but rather with your VM config and/or operation. Looking briefly at your host log:

`[I]   7047634   cpuinfo.c:38 | lgDebugCPU | CPU: 2 sockets, 10 cores, 10 threads`

This clearly shows your VM is mis-configured. You do not have 2 sockets and 10 single threaded cores. Such mis-configurations can easily cause slowness and frequent crashes. I suggest you to visit the VFIO forum and/or the VFIO discord and get some assistance with configuring your VM properly. Also, once you fixed your setup, upgrade LG to B7-rc1.

**Comment by doonv** [comment]
> I suggest you to visit the VFIO forum and/or the VFIO discord

I was not aware there was a VFIO discord, I'll ask there. thanks

**Comment by doonv** [comment]
> Also, once you fixed your setup, upgrade LG to B7-rc1.

Why?

**Comment by netboy3** [comment]
> Why?

B7 has literally hundreds of updates over B6 from both bug fixes and performance updates. It is currently the recommended version that should be used.

**Comment by doonv** [comment]
> B7 has literally hundreds of updates over B6 from both bug fixes and performance updates. It is currently the recommended version that should be used.

Ah ok, the website recommends B6 so that's why I was confused.

**Comment by doonv** [comment]
After fixing my CPU topology configuration (thanks VFIO discord), the crashes seem to have stopped.
