### ISSUE TITLE
looking-glass-client doesn't detect /dev/kvmfr0

### ISSUE THREAD

**Issue by PannaratWiriyaarritham** [gnif/LookingGlass#1130]
Here is the error

![image](https://github.com/user-attachments/assets/79eb0489-3003-4f88-aa4c-0871b38e3156)

File is found but looking glass not detect it 

![image](https://github.com/user-attachments/assets/0b84778a-ef2e-4033-a728-08e5c90ab940)

**Comment by netboy3** [comment]
Please note that GitHub issues in this project are reserved for discussions about verified bugs. You have a support issue. We are happy to assist users with such problems on the proper channels which are the looking-glass forum and the discord server (see the project website for details). With that in mind, the error you get is very clear. You have an invalid value of `app:shmFile` in your config file. You can quickly test this out by running `looking-glass-client -f /dev/kvmfr0` which will override whatever you have in your config. Your config file should contain the following:
```
[app]
shmFile = /dev/kvmfr0
```

**Comment by PannaratWiriyaarritham** [comment]
got it working thanks you so much.
