### ISSUE TITLE
[Question] What is Qemu Guest Tools Driver?

### ISSUE THREAD

**Issue by JunaidQrysh** [gnif/LookingGlass#1135]
This page https://looking-glass.io/docs/B7-rc1/troubleshooting/ says not to install Qemu Guest Tools Driver but what exactly is that.
Is it qemu guest agent?

Bonus question:
Should i install spice guest tools or virtio-win-guest tools.

**Comment by netboy3** [comment]
Have you read the new issue posting requirements when initially opening this issue? Please make sure to post such questions in the proper channels.

**Comment by JunaidQrysh** [comment]
> Have you read the new issue posting requirements when initially opening this issue? Please make sure to post such questions in the proper channels.

I'm sorry i didn't read it.
