### ISSUE TITLE
Build Error: and its all or any : trying to use B5 windows 10 but realize KVMFR was missing...:

### ISSUE THREAD

**Issue by fspkwon** [gnif/LookingGlass#1137]
Gentoo GNU/Linux Kernel 6.10.6-gentoo-x86_64

LookingGlass-B7-rc1/module/kvmfr.c:533:3: error: implicit declaration of function ‘vfree’; did you mean ‘kvfree’? [-Werror=implicit-function-declaration]

i will say though my VM is quite fast and i dont know why the all of a sudden speed increase <- im using a 2017 iMac with iris plus 640 the 7th generation card and first one that supports gvt-g im using rdp to correct any issues<- ive setup remote login and launch looking glass at startup but the service itself isnt showing anythings started just the tray applications there which it wasnt doing that until i switched to B5 the display drivers clean installed from intels website and the redhat ivshmem driver virtio driver is installed and another issue the Tianocore Bios when booting WindowsPE its fine , when booting Past either I think a generic driver starts to supplement something, Looking Glasses IVSHMEM driver gets installed or the display driver gets installed it doesnt function like a normal progression that i see happening on the videos the EFI text remains on the screen with the logo the spinner goes and then fades with the logo to black and just sticks with the efi text on the screen but i can RDP into the machine because i setup autologin and everything

ok im changing make.confs compile flags -Wall -Wextra -std=C11

and can confirm no matter what i do: 

error: implicit declaration of function ‘remap_vmalloc_range’; did you mean ‘ida_alloc_range’? [-Werror=implicit-function-declaration]
  163 |       return remap_vmalloc_range(vma, kbuf->kdev->addr + kbuf->offset,
      |              ^~~~~~~~~~~~~~~~~~~
      |              ida_alloc_range

and i think i get what its saying its used for the standard ivshmem driver is replaced by looking-glasses version
where you specify the file with the correct permissions all the works done for you and you have a ultra-low latency
video server but its actually a compositor...

and  this being the last of my error:
[I]   1117155706                ps.c:245  | purespice_connect              | Connecting to socket 127.0.0.1:5900
[E]   1117156023           channel.c:97   | channel_connect                | Socket connect failed
[E]   1117156042                ps.c:264  | purespice_connect              | channel connect failed
[E]   1117156081              main.c:1021 | spiceThread                    | Failed to connect to spice server
i dont know if thats libvirt related or not sometimes it says tls isnt compatible

**Comment by gnif** [comment]
Github issues are for bug reports, not general support. Please use the Discord server at http://looking-glass.io/discord

> error: implicit declaration of function ‘remap_vmalloc_range’; did you mean ‘ida_alloc_range’? [-Werror=implicit-function-declaration]

Fixed in bleeding edge already.

**Comment by fspkwon** [comment]
well thanks for the information , hey by chance have you ever heard of a VERY specific issue
i mean the reason why i wanted to do this is already being worked out on the linux end already Yes i will
admit its wine <- but uhhh where if you start ok for instance we have a mdev device and shmem working THEORETICALLY
i say theoretically because in my rdp session its as fast as snapping <- and it shows my device id perfectly fine
meaning the driver and all thats working ONE WOULD ASSUME however; when transitioning from efi to the second
stage initialization of windows drivers i assume the efi "TEXT" is overcasting what would be image if there was even one
there and the issues i would then assume to enter there with Tianocore meaning the text is resident where efi logo
should be standing still with the windows loader have you ever heard of this? i have a mdev , and spice graphics driver the video set to none , and when i press play i click the left monitor and thats how im using it any attempt to connect to looking-glass says it cant something what spice-protocol it cant connect to spice protocol and in some cases spice is saying either "no authentication protocol has been defined" or that "TLS support has been disabled"

**Comment by gnif** [comment]
Locked, github issues are NOT for support requests.
