### ISSUE TITLE
Kernel Module Documentation Small Improvement Proposal

### ISSUE THREAD

**Issue by Ununnilium** [gnif/LookingGlass#1139]
In the documentation https://github.com/gnif/LookingGlass/blob/e25492a3a36f7e1fde6e3c3014620525a712a64a/doc/ivshmem_kvmfr.rst?plain=1#L20 it is proposed to install `linux-headers-$(uname -r)`. `uname -r` returns the exact version (e.g. 6.8.0-47-generic). This means that on every kernel security update, the kvmfr module is not rebuilt because the  headers are missing. I think the correct package is `linux-headers-generic` which always depends on the latest `linux-headers-*-generic` package:
```bash
apt-get install linux-headers-generic dkms
```

**Comment by gnif** [comment]
If the user is using some other kernel (ie, realtime, zen, whatever) your suggested change would break things for them.
