### ISSUE TITLE
How to (full) remove/uninstall looking-glass-client from my debian 12?

### ISSUE THREAD

**Issue by isaias1010** [gnif/LookingGlass#1143]
Please !!
```

**Comment by gnif** [comment]
Issues are for Bug Reports and Feature Requests Only!

Create a New Topic on the Level1Tech's forum under the Looking Glass category:

https://forum.level1techs.com/c/software/lookingGlass/142

Ask for help in the Looking Glass discord server

https://discord.gg/52SMupxkvt

Issues that are not bug reports or feature requests will be closed & ignored
