### ISSUE TITLE
Incompatable with latest versions of QEMU

### ISSUE THREAD

**Issue by mbrumlow** [gnif/LookingGlass#1145]
Updated system to use QEMU 6.1 (Nixos 24.11) and now I get spice errors.  It seems to happen when the VM attempts to use audio. 

Steps to reproduce. 

1. Start Windows VM
2. Open browser. 
3. Navigate to a site that plays sound (youtube.com) in this case. 
4. Press play
5. Observe looking-glass-client exit with error 

I built locally modifying pure-spice to ignore double connect, but then would later hit another protocol error. 

Logs:
```
00:00:04.237 [I]           channel.c:269  | channel_internal_disconnect    | PLAYBACK channel disconnected
00:00:04.251 [I]                ps.c:644  | ps_connectChannel              | PLAYBACK channel connected
00:00:04.252 [I]           channel.c:269  | channel_internal_disconnect    | PLAYBACK channel disconnected
00:00:04.258 [I]                ps.c:644  | ps_connectChannel              | PLAYBACK channel connected
00:00:04.258 [I]           channel.c:269  | channel_internal_disconnect    | RECORD channel disconnected
00:00:04.258 [I]           channel.c:269  | channel_internal_disconnect    | PLAYBACK channel disconnected
00:00:04.258 [I]           channel.c:269  | channel_internal_disconnect    | INPUTS channel disconnected
00:00:04.258 [I]           channel.c:269  | channel_internal_disconnect    | MAIN channel disconnected
00:00:04.258 [I]                ps.c:330  | purespice_disconnect           | Disconnected
00:00:04.258 [E]      channel_main.c:221  | onMessage_mainChannelsList     | Protocol error. The server asked us to reconnect an already connected channel (PLAYBACK)
00:00:04.258 [E]                ps.c:519  | purespice_process              | MAIN: Handler reported read error
00:00:04.258 [E]              main.c:1056 | spiceThread                    | failed to process spice messages

```

**Comment by netboy3** [comment]
The latest version of QEMU is 9.1.2. Qemu 6.1 is over 3 years old. The issue you describe is due to a bug in QEMU 9.1.1 (which seems to be the version NixOS is currently providing). The bug was fixed in 9.1.2 so you need to either upgrade QEMU to 9.1.2, or downgrade to 9.1.0. This is not an LG issue.

**Comment by mbrumlow** [comment]
Sorry, I had a typo, it was 9.1

**Comment by mbrumlow** [comment]
I have confirmed that upgrading to qemu 9.1.2 has resolved this issue.
