### ISSUE TITLE
Linux Host still broken in Dec 2024?

### ISSUE THREAD

**Issue by tabletseeker** [gnif/LookingGlass#1147]
Goal: Linux VM (LG Host)

* Followed Documentation for Setup
* Compiled and installed looking-glass-host and kernel module on Linux Guest.
```
$ ls -l /dev/kvmfr1
crw-rw----+ 1 user 139, 0 Dec 19 16:36 /dev/kvmfr1
$ lspci -k -s 04:01.0
02:01.0 RAM memory: Red Hat, Inc. Inter-VM shared memory (rev 01)
	Subsystem: Red Hat, Inc. QEMU Virtual Machine
	Kernel modules: kvmfr
```
I've tried every single version from B7 - B4 without luck.
This scenario is stated to be unsupported but is there **anyone** who's at least got this working _somehow_?

**Comment by gnif** [comment]
Closing as invalid, it has been made exceptionally clear that the linux LG host application is incomplete and broken.

**Comment by tabletseeker** [comment]
> there are zero plans to improve this at this time.

Sorry for the invalid issue. I've been been supporting this project for a while and just wanted to ask what in particular is causing a problem with the Linux host (and whether I can help out)?

Since the LG host for Linux can be compiled I imagined that there would at least be some records of this _ever_ working under _any_ circumstances.

Is there even a single case?

**Comment by gnif** [comment]
It's extremely niche, very few people want this so it doesn't warrant the limited free time the dev team has to put effort into it.

Just because something compiles doesn't mean it's functional. Like I said, it's missing a lot of functionally because it's incomplete and not in a working state. It never once has been in a ready for general use working state.

**Comment by tabletseeker** [comment]
> Like I said, it's missing a lot of functionally because it's incomplete and not in a working state. 

Hmm ok then, I just wanted to mess around with it to see if I could grab some frames, not for any serious use case.

I understand there is no documentation for this, but are there possibly any resources or materials that could help me find out how to set up a stream between /dev/kvmfr1 and the IVSHMEM file?

**Comment by gnif** [comment]
no, because this can't be done. IVSHMEM is the virtual device in QEMU and is backed by shared memory. That shared memory can be EITHER `/dev/shm/something` or the memory provided by the KVMFR module.

I am locking this issue now as we do not support this and you seem to not quite get the hint here.
