### ISSUE TITLE
Using LookingGlass with Game Mode

### ISSUE THREAD

**Issue by t0msk** [gnif/LookingGlass#115]
Hello,

as far as I know Game Mode feature in WIndows 10 will allocate as much system resources to game, so it means that LookingGlass will run with less CPU cycles? So it means that it doesn't have to copy every frame (because of lag)?

I don't know if you understand me. But if you do something CPU intensive, then OS will allocate less CPU cycles to other applications (I mean OS scheduler), so can be LookingGlass performance affected by this?

**Comment by VoodaGod** [comment]
i remember when i first started to try looking glass, and noticed that it just would not work well at all with witcher 3, but did work sort of ok in some other games. i at some point then noticed that other cpu heavy games also wouldn't work properly with looking glass, and then one day while testing the effects of the game mode i realized that looking glass was working much better without it.  
so yes, looking glass will be affected by game mode, it would be great if there was a way to let game mode ignore certain programs, but i have simply disabled game mode for now. maybe if your cpu is strong enough you won't notice looking glass slowing down, however on my fx 8120 it is not usable with game mode and cpu heavy games

**Comment by cmdrkotori** [comment]
I don't have access to a windows 10 vm right now, but does setting [process priority to background services](https://www.tenforums.com/tutorials/89429-adjust-processor-resources-best-performance-windows-10-a.html) fix this? By default windows is set to use what's known as an unfair scheduler.

**Comment by t0msk** [comment]
@cmdrkotori It would be great if someone test it, because I use dual boot right now, I want to move to Linux completely in some weeks.

**Comment by gnif** [comment]
Again, not the place for questions, use the Triage thread.
