### ISSUE TITLE
LookingGlass Host crash on Windows login screen

### ISSUE THREAD

**Issue by robstolarz** [gnif/LookingGlass#116]
### Required information

Host CPU: Intel i5 6600k
Host GPU: AMD RX Vega 64
Guest GPU: AMD RX 480
Host Kernel version: 4.20.0-arch1-1-vfio
Host QEMU version: 3.1.0

### Description

Everything works fine if I keep `looking-glass-client` closed and log in to my account some other way. But logging in through `looking-glass-client` causes a host application crash. I do not have a dump but it crashes with the exception code `0xE06D7363`, unhandled exception, according to Event Viewer. The host application must then be restarted after login. `looking-glass-host` runs from a CurrentVersion\Run registry key.

**Comment by robstolarz** [comment]
This can be mitigated by [enabling auto-logon](https://www.cnet.com/how-to/how-to-log-on-to-windows-7-automatically/).

**Comment by gnif** [comment]
Closing this issue, it is very likely fixed as the host has gone through substantial changes since this issue was created.
