### ISSUE TITLE
High idle guest CPU usage when client not connected

### ISSUE THREAD

**Issue by maxpoulin64** [gnif/LookingGlass#121]
Since I upgraded to version a12, when I close the Looking Glass client, the guest uses 100% of two CPU cores constantly until the client is connected again. Once I open the client again, CPU usage of the guest drops back to under 2%. Killing the host application in Windows also resolves the CPU usage issue.

It also only happens when the guest is fully idle, on the desktop. If I leave Task Manager open for example to observe the CPU usage, the issue doesn't happen. If I open Task Manager using the physical display and keyboard however, I can see the two cores being pegged to 100%. It seems once it falls into its spinning state, the only way to recover is to connect the client or kill it.

Here is a screenshot of Task Manager. We can see the two cores being loaded and once I opened the client to take the screenshot, CPU usage drops to normal idle:
![screenshot_20190109_201759](https://user-images.githubusercontent.com/5481612/50939673-d62eba00-144b-11e9-8442-240b0b56b66a.png)

Downgrading back to a11 everything behaves normally, so I believe this is a regression.

### Required information

Host CPU: AMD Ryzen Threadripper 1950X
Host GPU: AMD Radeon RX 570
Guest GPU: AMD Radeon RX Vega 64
Host Kernel version: 4.20.0-zen1-1-zen (also happens on 4.18 and every other kernels I've used)
Host QEMU version: 3.1.0-1 (from Arch repo)

**Comment by gnif** [comment]
Thanks for the detailed report, I have managed to replicate this and I am investigating a fix.

**Comment by gnif** [comment]
This is fixed in the new `c-host` host application.
