### ISSUE TITLE
Implement spice audio playback (and/or recording)

### ISSUE THREAD

**Issue by JJRcop** [gnif/LookingGlass#122]
First off, this is most certainly a post-beta suggestion, you have much more important things to focus on right now.

----

I am happily using pulseaudio as my QEMU_AUDIO_DRV at the moment, but I feel that looking glass is lacking in regards to being a spice client: it's missing audio support. Even though I already have a working audio solution, I would prefer to use spice for this if possible. Also, supporting spice for audio will be convenient for new users, who won't have to specify QEMU env variables to get audio to work.

Spice supports both playback and recording, so you can also set up microphone support as well if you wish to.

I have noticed there there are two requests relating to audio in looking glass that you've closed before, #39, and #99. Please don't take this as a pestering for audio support, I believe this request is different than those issues, because I am specifically requesting the use of spice for audio support, rather than using IVSHMEM.

Since audio would be handled using spice, the looking-glass-host doesn't need to know about audio at all, and can focus on its task. Only the client needs to know about audio, and only about talking to spice (which it already does).

I hope you consider this suggestion in the future as a method for audio support.

Host CPU: Ryzen 5 2600
Host GPU: MSI Radeon RX 580 8G V1 8GB
Guest GPU: MSI GeForce GTX 970 4GD5T OC
Host Kernel version: Linux debian 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
Host QEMU version: QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-2+b1)

**Comment by gnif** [comment]
The spice client implementation I have written from scratch, LG would have to be very aware of it to make use of it, not only is it unnecessary it will further complicate LG. I am sorry but this is not a feature I will be adding.

**Comment by JJRcop** [comment]
If I may entertain a little bit of discussion. From my understanding, only the looking glass client needs any changes. I had the conception of the client simply reading the spice playback channel and then using SDL to play it, since SDL has an audio subsystem. It needs to initialize the SDL audio subsystem and open up an audio device (SDL can auto-choose), with a callback to read the next bit of spice playback from a buffer (probably a small ringbuffer). 

Is it more complex than what I'm thinking? Nonetheless I understand your decision.

**Comment by gnif** [comment]
Since LG's primary goal is low latency, hopefully to the point of being in-perceivable, sending audio over TCP/IP, and the additional processing required will introduce both complexity and latency that can be avoided simply by letting QEMU output directly via ALSA or some other system directly.

Adding this to LG is not only additional complexity to maintain, but completely useless when there is already a far better alternative available.

Spice's audio support is designed for remote management of a VM over a network, or even WAN. It is in complete conflict with the goals of LG and as such we will not be implementing this into LG unless things drastically change in the future, which is very unlikely.

**Comment by JJRcop** [comment]
Thank you for your explanation. This suggestion was purely for convenience sake, but I understand now that implementing spice audio may mean LG has super low latency video, but not so low latency audio. And in order to get that super low latency audio you'd have to do it yourself, which doesn't make sense when QEMU does that already.

To clarify, implementing the audio capture, transport, and playback yourself was **absolutely _not_** what I had in mind with this suggestion. I now understand the problem of LG's super low latency image being tainted by spice audio that may not share the same goal, so forcing people to use the QEMU's low latency native audio is a good idea.
