### ISSUE TITLE
Wayland mouse problems

### ISSUE THREAD

**Issue by HoshiYamazaki** [gnif/LookingGlass#124]
### Required information

Host CPU: i5-6600
Host GPU: hd530
Guest GPU: rx480 4gb
Host Kernel version: 4.20.3
Host QEMU version: 3.0.0-6

Looking glass mouse capture is working badly under wayland - even if capture mode is enabled there is area where I can't move cursor (right/top part of screen). Also mouse scroll to top is scrolling to bottom.

I got two screens:
FullHD (left) and 2560x1440 on right without scaling. Looking is running under borderless mode on right screen with VM running under FullHD (I use upscaling).

**Comment by HoshiYamazaki** [comment]
Ok, this was tested on outdated qemu version, I will compile new qemu in hour. I use this AUR:
https://aur.archlinux.org/packages/qemu-patched/

**Comment by HoshiYamazaki** [comment]
This bug still appears in qemu-patched 3.1.0-2.

**Comment by gnif** [comment]
up-scaling is likely the issue. Can you please try running 1:1 and see if the problem persists?

**Comment by gnif** [comment]
Closing due to lack of information
