### ISSUE TITLE
SDL_CreateWindow fails with `Couldn't find matching GLX visual`

### ISSUE THREAD

**Issue by rLinks234** [gnif/LookingGlass#128]
### Required information

Host CPU: i9 9900k
Host GPU: i9 9900k (UHD 630 - Device ID `0x3e98` per [Intel Ark](https://ark.intel.com/products/186605/Intel-Core-i9-9900K-Processor-16M-Cache-up-to-5-00-GHz-))
Guest GPU: Zotac 1050 Ti Mini
Host Kernel version: `4.20-4-200.fc29.x86_64`
Host QEMU version: `3.0.0`

#### Additional info

Host GPU drivers: MESA 18.2.8

---

When trying to run the `looking-glass-client` on my machine, I could not get an SDL2 window to open (using either EGL or OpenGL renderers). It kept complaining about not being able to find a matching GLX visual (this was the error message returned by `SDL_GetError()`).

After digging through the source code, I was able to get an SDL2 window (with a matching GLX visual) by removing multisampling from [egl.c](https://github.com/gnif/LookingGlass/blob/e4ae9134ae53bfedfdf604a90d22a4643a43a368/client/renderers/egl.c#L139-L140) (_i.e._, just commented out those two lines).

`glxinfo` surprisingly showed me that I have no GLX visuals which support multisampling, period. I will admit that I haven't looked through the mesa3d bug tracker/changelogs just yet to see if this is a missing feature yet to come for my iGPU.

I understand this is an issue tracker (and not a feature request tracker), but perhaps it may make sense to add an option to disable multisampling, given some GPUs apparently don't have support just yet through mesa3d for it. If you would approve a pull request adding such feature, I would be happy to implement it myself.

**Comment by gnif** [comment]
Rather then an option to disable it, it would be better if we can detect if support is available. A PR implementing this would be accepted provided it follows the coding style of the project.

**Comment by LordZiru** [comment]
I getting this error
Could not create an SDL window: 
Couldn't find matching GLX visual
with intel i7 7700k

 what can i do?

**Comment by rLinks234** [comment]
I've forked this repo and worked around this issue. You can just cherry pick the commit from [here](https://github.com/rLinks234/LookingGlass/commit/4ac781b4516678b6c59d9ecf4a61df64a01ec8c1) if you need a quick workaround, @LordZiru . I haven't opened a PR yet because I haven't checked to see if it matches @gnif 's code style of the project, etc.

**Comment by gnif** [comment]
It looks good but I don't think that `lg-renderer.c` is the right place to put it, code in there should be generic to all renderers and in the future I hope to get a Vulkan renderer in there. I would suggest making a `renderers/gl-utils.c` or similar.
