### ISSUE TITLE
Regression between a11 and a12 : "Could not configure a capture device"

### ISSUE THREAD

**Issue by tscs37** [gnif/LookingGlass#130]
### Required information

Host CPU: AMD Ryzen 1700x
Host GPU: AMD Radeon 460
Guest GPU: AMD Vega 56
Host Kernel version: 4.20.6-arch1-1-bcachefs-git-31102-g17769a43257c-dirty
Host QEMU version: 3.1.0 (qemu-patched from AUR, present without patched version)

### Issue

Using version a11 of the looking glass host works without issue, using a12 leads to the host process crashing with an error saying the capture device could not be captured (specifically the DXGI device), this might possibly be related to commit 3cd152c9d59fc45a609fba4cb77958d01d6c8800 but I cannot be certain as I haven't gotten the host process to compile.

**Comment by gnif** [comment]
There is nothing in 3cd152c that would explain the failure. Please provide the output of the host process.

**Comment by tscs37** [comment]
```
[I] CaptureFactory.h:83 | CaptureFactory::DetectDevice | Trying DXGI
[E] DXGI.cpp:225        | Capture::DXGI::Initiailize   | Failed to get IDXGIOutput1
[E] CaptureFactory.h:92 | CaptureFactory::DetectDevice | Failed to initialize a capture device
Unable to configure a capture device
```

**Comment by gnif** [comment]
Please ensure you have installed the Windows 10 Creators Update, the error text is wrong as we are now using `IDXGIOutput5` which is a late addition to W10.

**Comment by gnif** [comment]
Added fallback behaviour in 18634fa8 for backwards compatibility.

**Comment by tscs37** [comment]
I do have all updates installed that Win10 is offering to me, but thanks for including the fallback.

**Comment by gnif** [comment]
It also could be that the Vega doesn't implement this feature. Can you please confirm that the fallback corrected the problem for you?

**Comment by tscs37** [comment]
Yup, problem fixed.

Thank you very much!
