### ISSUE TITLE
Feature request: Clipboard sync.

### ISSUE THREAD

**Issue by the-eater** [gnif/LookingGlass#131]
Would it be possible to add clipboard sync in LookingGlass? I know it's a feature in spice but this client doesn't seem to support it.

Connecting a different spice client only for this is kinda of a hassle, or using a 3rd party program for it.

**Comment by TerminatorNL** [comment]
I would love to see clipboard sync, but it _might_ be out of Looking Glass' scope. Maybe an API which tells us when the Looking Glass client switches focus and/or the cursor is within the looking glass window and let another program take care of clipboard management using Looking Glass' API? This would take less time to write for Geoffrey, and someone else can take on the task of writing advanced clipboard management. Maybe even extending it to file drag and drop.

**Comment by gnif** [comment]
This has been on the list of improvements for LG for some time, however until LG hits beta, enhancements like this are out of scope.

**Comment by the-eater** [comment]
Cool, I may have some time this weekend and since I kind of need this to code reliable on Windows, I will try to make a PR

**Comment by JJRcop** [comment]
I would consider only syncing the clipboard while LG has focus.

**Comment by gnif** [comment]
I am working on this at current, lastest master now has guest->host text clipboard sync. The semantics of it's operation are still yet to be determined.

**Comment by gnif** [comment]
This feature is complete as of c7666b314bde2622328b5ddd7f16c7493c552d01
You must have the spice-agent installed in windows and have setup the spice serial port for communications as described here:

https://www.spice-space.org/agent-protocol.html
