### ISSUE TITLE
Output Selection

### ISSUE THREAD

**Issue by dawsers** [gnif/LookingGlass#132]
I have made a very simple modification to `DXGI.cpp` to be able to select another device or output of the host. Looking Glass by default selects the first adapter and its first output. This code just changes that. Please, have a look at it and use it or throw it away.

I am using the code to be able to output my secondary monitor through Looking Glass
`-o output=DISPLAY2` while my primary is a physical device. It adds two options, `adapter` and `output`,
and the value of those options is compared while `Initialize()` enumerates the devices and outputs. If any
of the host's adapters or outputs (or both) includes the value(s), it is used as capture target. It may be useful for people with more than one card allocated to the host, or several monitors attached to it.

I am sure you already had something like this planned, but I couldn't wait!

Thank you for your work, this is a very cool application.

[output-selection.zip](https://github.com/gnif/LookingGlass/files/2848389/output-selection.zip)

**Comment by gnif** [comment]
It has been planned but is low priority as it's such a niche requirement. Thank you for your effort in adding this, however the way in which it has been provided is not suitable for use. Please fork this repository, make your changes and commit them to your fork, when you are happy with them please issue a Pull Request and I will review for commit.

This way you receive attribution for your work in the git history, and I am able to see a diff of the exact changes you have made for review before accepting them.

**Comment by dawsers** [comment]
The .zip contains a patch file which you can apply to your local copy of the repository (`git am`) and then do a `git difftool` to view the differences. I don't need any attribution, it is just a hack I sent in case you can reuse some of the code when you implement it in the future. Thanks!

**Comment by gnif** [comment]
For licensing reasons the patch requires attribution. I can not apply a patch from a third party that has no "origin" as it may taint the project. I also can already see a few issues with your patch which a PR would allow me to directly comment on,

**Comment by MyNameIsCosmo** [comment]
Github has an excellent guide on forking a project and submitting a pull request: https://guides.github.com/activities/forking/

**Comment by gnif** [comment]
This is windows platform dependent for the `c-host` and as such this information should not be passed to the app thread at all. The `c-host` is a work in progress and I am working on an agnostic API to pass parameters into the various modules I should have ready soon.

**Comment by gnif** [comment]
This has been done using the new `option` API.

Usage is simple: `looking-glass-host.exe dxgi:adapter=XXX dxgi:output=YYY`

**Comment by theretohere** [comment]
Where do we get the possible options on our systems for XXX and YYY? Is there a tool that enumerates all the adapters and outputs on a system for input here?
