### ISSUE TITLE
Remote looking glass

### ISSUE THREAD

**Issue by markg85** [gnif/LookingGlass#133]
Hi,

Most of the examples i find is where you run a pc, on that pc you use linux and on the same pc you also have a dedicated second gpu + kvm for windows. In that case everything is still within the same case and everything works smoothly! Really smoothly! I had that working and was honestly impressed!

Now my hardware setup changed a little. I have 2 computers. Both are running Linux.
My linux desktop has a simple low-spec gpu. It's meant as quiet pc. The other machine is a "beast" and hosts a heavy GPU card and a kvm instance in which windows is running. If i hook up a screen on that machine i actually have a smooth running windows there, so the setup locally does work.

Now on my linux desktop (lets call it Host X) i want to run looking glass over my network to the beast pc (lets call it Host Y).

So the config is:
Host X: linux host, light gpu. Meant to be quiet and used as work pc.
Host Y: linux server, kvm instance with Windows 10 on it and a heavy GPU. Meant for remote heavy gpu work.

Now i want to run looking glass on Host X to the Windows 10 on Host Y.
For that i have a couple of issues.
1. It wants a /dev/shm/looking-glass. I "guess" that should live on the server itself (so Host Y, not X).
2. Spice should definitely be on Host Y

Point 2 is easy to fix, just give Host Y as spice host.
Point 1 is tricky. I tried:
- using an SSH link (to link the  /dev/shm/looking-glass from Host Y to a local place on Host X) then running looking-glass-client on Host X with -f pointing to that link. It didn't work, it gives a "Failed to open the shared memory file". I did also compile the code manually and debugged which errno it gives, it's 6 with the description: "No such device or address". Might make sense as the kernel driver (the dkms module) has nothing to do with it.
- While trying to be smart i thought: "ohh, i can do X over SSH, that probably works" so i ran: "ssh -Y <host y>" and then the looking glass client. That doesn't work due to this error: "Could not create an SDL window: Couldn't find matching GLX visual". Things like glxgears, opera, other apps.. All do work fine with that method so the configuration seems to be somewhat oke.

Any clue what i might need to change to get this working?

Cheers,
Mark

**Comment by gnif** [comment]
No, look to other projects for this (try Parsec), Looking Glass is not designed to operate over a network, nor will it ever be

**Comment by dogtopus** [comment]
Moonlight is still somewhat Nvidia only and needs GeForce Experience which has intrusive force login bs (unless you talk about sunshine but that project is half dead the last time I checked). OTOH it could be possible (and makes sense since IIRC there's only 1 fully open source game streaming solution available and it's an academic project that has worse activity than sunshine) to have an alternative client for LookingGlass that interacts with the IVSHMEM, encodes the frames and streams them with some protocol (could even reuse what Moonlight already have)

**Comment by gnif** [comment]
If one is to just stream over a network IVSHMEM is about the worst way one could go about this. Just encode in the guest GPU using it's hardware and stream directly from the guest. LG is not the project for this.
