### ISSUE TITLE
Official support for intel GVT -g

### ISSUE THREAD

**Issue by rmerrorlog** [gnif/LookingGlass#137]
### Required information

Host CPU: i7-5500U
Host GPU:   hd5500
Guest GPU: hd5500
Host Kernel version: 4.18.0-15
Host QEMU version:2.11.1

Looking glass work well(mouse little glitchy). Dont require iommu/vt-d/SR-IOV/compilation(ubuntu18.04). Work with libvirt / virt-manager. So maybe worth to support.
**Reports that do no include this information will be ignored and closed**

**Comment by gnif** [comment]
What exactly is this issue about?

**Comment by gnif** [comment]
Closing as you have not provided any information.
