### ISSUE TITLE
Feature suggestion: switch client window to fullscreen

### ISSUE THREAD

**Issue by trying-lg1** [gnif/LookingGlass#139]
Host CPU: AMD Ryzen 7 2700X
Host GPU: MSI Nvidia 1030 2GB GDDR5, GP108
Guest GPU: Sapphire AMD Radeon R9 380X 4GB GDDR5
Host Kernel version: 4.19, manjaro/arch
Host QEMU version: 3.1.0.1

LG client suggestion:
Could the client support switch from window to fullscreen and back? Not just maximize but really a fullscreen.

**Comment by aalhitennf** [comment]
very much needed :+1:

**Comment by JJRcop** [comment]
I think it could be a keybind that involves the screen grab key which could be renamed to `escapeKey` instead of `captureKey`. Maybe `escapeKey`+F
https://github.com/gnif/LookingGlass/blob/d1c0d2b5f80cea156c18b956024b84b17736d62a/client/main.c#L117

**Comment by gnif** [comment]
`escapeKey+F` has been implemented :)
