### ISSUE TITLE
Feature suggestion: nvEncDXGIOutputDuplication

### ISSUE THREAD

**Issue by happy2046** [gnif/LookingGlass#140]
HI
I find NVIDIA release a new sample to capture dxgi desktop and encode it by nvenc without copy gpu data to cpu.
NVFBC is planned to be deprecated on Windows 10 starting with Windows 10 October 2019 Update for reasons explained in this document.
Windows 10 provides native capture APIs that can be considered as alternatives to NVFBC. Explore this option (Github Sample)

https://github.com/NVIDIA/video-sdk-samples/tree/master/nvEncDXGIOutputDuplicationSample

**Comment by gnif** [comment]
This doesn't help us in any way, we do not need to use compression, nor do we want to.
