### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [gnif/LookingGlass#142]
Greetings @gnif, I'm here today to offer my services. As a graphic designer in development and an open source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process (of course) is totally free and we would be working together to create the design that fits best with your project. Of course, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colours, shapes, etc. 

Sorry for disturbing if this is not the proper channel for this, best regards.

**Comment by gnif** [comment]
Hi @jorlogicus, thank you for the kind offer however at this time the Looking Glass logo that we are currently using was designed by L1Tech. This is a community project as as such I would suggest you create a new thread over there on the L1Tech forums and discuss it with the community. If the general consensus is to use the logo that you have created I would be more then happy to use it. I am a mod over there and would be happy to setup a vote after a period of submissions has elapsed for the best logo.
