### ISSUE TITLE
Possible solution to mouse position issues

### ISSUE THREAD

**Issue by jonpas** [gnif/LookingGlass#143]
Related to #73 #27 and #17.

Despite running 1:1 resolution of guest to host (full-screen) and Windows mouse acceleration being disabled, running multiple monitors still seems to cause issues with "invisible borders" on the guest (even just on single monitor in my case), until you capture and un-capture or move it far enough to the opposite border.

Capture key is good, but slow when you want to quickly move around. Additionally, resizing the client window breaks it right away.

I have however noticed your videos on YouTube, where you seem to have a perfectly working mouse, but I am not sure if you are just running 1:1 resolution there or not (doesn't look like it) and also don't seem to be getting issues with "invisible walls".

---

I am aware of the restrictions Spice/QEMU set, so I implemented a system where mouse is automatically captured as soon as it enters some pixels into the view-port (~10 px from edge), and released as soon as it touches the edge (1px).

It works pretty well for windowed usage, resizing and snapping it around in a tiling window manager (using i3), however there are some problems with my current implementation:
- Full-screen causes hitching on the sides:
  - Captures and un-captures constantly on the side where the monitor ends and there is no secondary monitor.
  - Lots of hitching back and forth before finally releasing on the side where second monitor is.
- Guest and Host cursors are not aligned on enter/exit _(could probably solve this by setting it to same edge position as the window has, instead of just going off of view-port)_.

Code is currently on my repository ([diff](https://github.com/gnif/LookingGlass/compare/master...jonpas:autocapture)), didn't want to make a pull request as it is largely experimental and may not be suitable at all. At the end of the day it might be configuration-specific.

Thank you for reading.

**Comment by gnif** [comment]
I am sorry but while your idea is novel it is more of a workaround then a fix. You need to understand a little more about how the client and host share cursor information and how the client draws the cursor where the host reports. This is a bug I intend to work on and fix but as it's more of a nuance rather then a critical or performance issue it's low priority.

**Comment by jonpas** [comment]
Yes, it is closer to a workaround, but it works rather well for my current use-case, maybe for someone else as well in the meantime. 

I am very well aware I don't understand nearly enough at this time, but I will continue to research and learn of the inner workings (out of pure interest). My goal is seamless "simultaneous" OS usage, and Looking Glass comes really close with a few bugs or nuances, impressive for alpha software. :) 

Thank you.

**Comment by gnif** [comment]
> My goal is seamless "simultaneous" OS usage,

That is LG's goal also as I use it this way too. Thanks for the support, I will close this issue but will refer people to it as an interim workaround, thanks for your efforts.
