### ISSUE TITLE
Update windows regedit docs

### ISSUE THREAD

**Issue by luqasz** [gnif/LookingGlass#145]
### Required information

Host CPU: AMD A10-5800K
Host GPU: Radeon HD 7660D
Guest GPU: Radeon HD 7660D
Host Kernel version: 4.18.0-16-generic
Host QEMU version: 1:2.12+dfsg-0~18

### Docs update (registry)
I've noticed that (on windows 10) it is best to provide a `REG_EXPAND_SZ` key with `%ProgramFiles%\looking-glass-host.exe` as value. This is more "flexible" even if end user changes program files path.

Can you please update docs. I had a bit of trouble figuring out which type of key I should use.

**Comment by gnif** [comment]
Sorry but this is user preference specific, the documentation does not suggest placing the executable in the Program Files directory.

**Comment by luqasz** [comment]
> Sorry but this is user preference specific, the documentation does not suggest placing the executable in the Program Files directory.

Even as a example ? Sorry I am not a windows expert and IMO a simple example would be better than nothing.

**Comment by gnif** [comment]
Perhaps so, but at this time I do not suggest people place the host application into their Program Files directory as this is Alpha software and is not managed by an installer. When it reaches B1 we will be looking towards building a installer to deploy and configure the LG host application to start with windows which will resolve this issue.

**Comment by luqasz** [comment]
Ok. Thx
