### ISSUE TITLE
Can't scroll up, it scrolls down either way

### ISSUE THREAD

**Issue by PaddiM8** [gnif/LookingGlass#147]
### Required information

Host CPU: Intel Core i7-6700
Host GPU: Intel HD Graphics 540
Guest GPU: NVIDIA GTX 1060 6GB
Host Kernel version: 4.19.20-1
Host QEMU version: 3.1.0

I'm using Wayland(Sway) on Arch Linux. When scrolling up on the host, it scrolls down instead. So basically, it only works to scroll down. It works perfectly when passing through the mouse, confirming that it is not an issue with Windows. I have tried both the latest *release* and the newest commit to master, and I the issue persisted after reinstalling my host OS(for unrelated issues).

**Comment by gnif** [comment]
At this time Wayland is not officially supported. However that said, all input, including mouse scroll relies on SDL2 for input events. If SDL2 is mis-reporting the scroll direction this would cause the behaviour you are describing. If you find this is occurring in other SDL2 applications please open a ticket with the SDL2 team regarding this behaviour.

**Comment by PaddiM8** [comment]
Oh, I see! Thanks.

**Comment by PaddiM8** [comment]
This appears to only be an issue with looking glass.

**Comment by gnif** [comment]
Are you able to confirm if it is only on wayland?

**Comment by PaddiM8** [comment]
I am not able to test that at the moment, because it crashes in X11 (Could not initialize EGL, probably because of Wayland specific things? Haven't been able to find why it does this). But it was the first thing I noticed when switching to Wayland, and it always worked on X11 before. I will try to do some more digging

**Comment by gnif** [comment]
Closed pending further information.
