### ISSUE TITLE
Feature request: Add DKMS config for kvmfr.io module

### ISSUE THREAD

**Issue by ducdigital** [gnif/LookingGlass#148]
Host CPU: AMD Ryzen 7 2950X
Guest GPU: NVIDIA 1080Ti
Guest GPU: NVIDIA 1660Ti
Guest Kernel version: 5.0.6-arch1-1-ARCH
2nd Guest: Win 10

Hi @gnif, would it be possible to add a dkms config for the kvmfr.io module so we can automatically build this module whenever there's a kernel update?

The VM->VM works really well!

Thanks!

**Comment by gnif** [comment]
Great idea! Feel free to provide a PR for this, I am not up to speed on DKMS and what is required.
