### ISSUE TITLE
Opening spice just show logo. Host seems connected

### ISSUE THREAD

**Issue by 3kynox** [gnif/LookingGlass#150]
Hello folks.

Everything was working before, everything looks like correct ... except I don't have display output of the host anymore. I just see the logo.
I suspect the host (windows) login screen to be in fault here. A,d I got no external screen today.

Here is the results on the client:

```
./looking-glass-client -w 1920 -b 1080 -MSd
[I]               main.c:757  | run                            | Looking Glass ()
[I]               main.c:758  | run                            | Locking Method: Atomic
[I]               main.c:751  | try_renderer                   | Using Renderer: EGL
[I]               main.c:824  | run                            | Using: EGL
[I]              spice.c:159  | spice_connect                  | Remote: 127.0.0.1:5900
[I]               main.c:961  | run                            | Waiting for host to signal it's ready...
[I]              spice.c:367  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]                egl.c:351  | egl_render_startup             | Vendor  : Intel Open Source Technology Center
[I]                egl.c:352  | egl_render_startup             | Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
[I]                egl.c:353  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 18.2.8
[I]               main.c:970  | run                            | Host ready, starting session
```

At some point before I had the login screen output, non responsive keyboard+mouse and a message at some point saying "streaming stopped". But since, no output.

Thanks for help!

**Comment by gnif** [comment]
This is a documented limitation of Looking Glass
See: https://looking-glass.hostfission.com/quickstart/readme

**Comment by 3kynox** [comment]
Sorry to give an answer that long after your reply.

I don't get where it is a limitation of looking glass on your README.
My problem seems only related when I've no monitors attached to the graphic card I'm passing through.

The main goal of looking glass is to have the display inside a window while I don't have any monitor plugged.

School exams incoming soon, and have to travel (I hope without a monitor). This could be cool if I get Looking Glass working without a screen (only on my laptop screen).

Thanks a lot :)

**Comment by gnif** [comment]
You must have a monitor or a dummy plug attached, it's a limitation of Windows.

**Comment by 3kynox** [comment]
Thanks a lot for your answer.
I'll take care of this.
