### ISSUE TITLE
"Building the Client" page needs an update

### ISSUE THREAD

**Issue by lilianmoraru** [gnif/LookingGlass#151]
### Required information
Host OS: Pop!_OS 18.10(Ubuntu 18.10)

[The docs](https://looking-glass.hostfission.com/quickstart/linux/build) suggest making an unoptimized build:
```
mkdir client/build
cd client/build
cmake ../ # this should probably suggest: cmake -DCMAKE_BUILD_TYPE=Release ..
make # this could be: make -j $(nproc)
```

Also, the build from the `master`(not a tag but just mentioning it) branch also requires the `binutils-dev` package.

**Comment by gnif** [comment]
> The docs suggest making an optimised build:

Incorrect, when unspecified the default build is `Release`

> Also, the build from the master(not a tag but just mentioning it) branch also requires the binutils-dev package.

Correct as of a few days ago, but the documentation is not for the master build but the A12 release.
