### ISSUE TITLE
Feature Request: Allow EGL brightness to be set via cli

### ISSUE THREAD

**Issue by tadly** [gnif/LookingGlass#153]
### Required information

Host CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Host GPU: Intel® HD Graphics 530
Guest GPU: MSI Armor GTX 1660TI
Host Kernel version: 4.14.106
Host QEMU version: 3.1.0

Basically what the title says.
Even though levels 2, 3 and 4 feel quite over exposed, 2 is actually a life saver for me.

It'd be nice to either specify one of the the four levels or maybe even better (if possible) a custom value (percentage or however it is handled internally) through the cli allowing me to add it to my automation :)

**Comment by gnif** [comment]
Agreed, this is an incoming feature :)
