### ISSUE TITLE
DOCS: Missing package to build under Ubuntu 19.04

### ISSUE THREAD

**Issue by jfturcot** [gnif/LookingGlass#155]
I only wanted to let everyone know that under Ubuntu 19.04, I had to install the following package to build or I would get an error about a missing header bfd.h

```
apt-get install binutils-dev
```

I hope this helps anyone else.

**Comment by gnif** [comment]
This is not the place to report such things. The master build has zero support, please wait until B1 has been released at which point the build documentation will be updated.
