### ISSUE TITLE
Freeze on sigint or on guest shutdown

### ISSUE THREAD

**Issue by FallingSnow** [gnif/LookingGlass#156]
### Required information

Host CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Host GPU: Intel Corporation Iris Plus Graphics 655
Guest GPU: Intel Corporation Iris Plus Graphics 655
Host Kernel version: Linux 5.1.0-rc6-mainline #1 SMP PREEMPT Fri Apr 26 10:35:40 PDT 2019 x86_64 GNU/Linux
Host QEMU version: QEMU emulator version 4.0.0

Running a Windows 10 guest on Arch Linux host. Currently using LookingGlass master branch.

When the guest is shutdown or looking-glass-client is killed by sigint it fails to clean up the screen. A still frame of the Windows 10 guest is stuck plastered over my screen. You can click through it too to get the desktop contextual menu.

**Comment by gnif** [comment]
This is not something that can be resolved with the current method we use to share the frame with the client, nor is it a priority fix at this time.
