### ISSUE TITLE
Question: Can we make LookingGlass work at winlogon like UltraVNC by running it as a service?

### ISSUE THREAD

**Issue by ssaavedra** [gnif/LookingGlass#159]
I was thinking that UltraVNC is (with all its differences) also a free software app that seems to be using the same Desktop Duplication API that LookingGlass leverages. However, while running it as a service, I'm able to work with the winlogon screen and "secure desktop" UAC prompts, which are not possible to handle in LookingGlass when running as a user-level application.

It may be due to UltraVNC bundling a mirror driver that is signed with a Microsoft-signed certificate, but I was thinking: as the driver is open source, could it be bundled and used from LookingGlass?

License-wise, both projects are GPL, so the only restrictions should be in the technical realm.

My current setup  (for others who may be interested) involves running a Windows installation that was previously installed in the metal (i.e., libvirt has some /dev/sdX as a real disk attached), and since I don't want to lose the login screen for other security implications (somebody managing to connect to the Spice port, or cold-booting from the disk itself) I'm relying on UltraVNC for logging in. After that, I start the LG client on Linux and everything runs great. If I need to do things that are slow via VNC, I left a secondary virtual QXL card connected via Spice (which is usually off; looking-glass cannot use that one as a backend), and I switch from the "real screen" (actually, an HDMI head terminator) to the Spice one and connect via Spice.

**Comment by gnif** [comment]
No.. this has been answered many many times, please read the FAQ.
