### ISSUE TITLE
Newest looking-glass-host crash

### ISSUE THREAD

**Issue by lunainvictum** [gnif/LookingGlass#160]
Host CPU: TR 1950x
Host GPU: AMD Radeon Pro WX3100
Guest GPU: ASUS Strix 1080Ti
Host Kernel version: 5.1
Host QEMU version: latest stable

Hello! 

i use the latest looking glass client because of wayland. Because with A12 i get a "Speicherzugriffsfehler" (it means segmention fault i think?). But i cant use the latest client, with the A12 looking-glass-host because it say it expect version 8 but got 6 (what ever this means). 

So i use the latest client and this clients works. But on the VM side, the virtual-glass-host dont work. it dont start and creates everytime a file named looking-glass-host.dump.

I dont know why, but github says everytime i want to upload a zip: "Something went really wrong, and we cant process that file.", so here is a link: https://www.file-upload.net/download-13607363/looking-glass-host.dump.html 

This are the detailed specs:

Host CPU: TR 1950x
Host GPU: AMD Radeon Pro WX3100
Guest GPU: ASUS Strix 1080Ti
Host Kernel version: 5.1
Host QEMU version: latest stable

Hello! 

i use the latest looking glass client because of wayland. Because with A12 i get a "Speicherzugriffsfehler" (it means segmention fault i think?). But i cant use the latest client, with the A12 looking-glass-host because it say it expect version 8 but got 6 (what ever this means). 

So i use the latest client and this clients works. But on the VM side, the virtual-glass-host dont work. it dont start and creates everytime a file named looking-glass-host.dump.

I dont know why, but github says everytime i want to upload a zip: "Something went really wrong, and we cant process that file.", so here is a link: https://www.file-upload.net/download-13607363/looking-glass-host.dump.html 

This are the detailed specs:
```

System:    Host: archlinux Kernel: 5.1.2-arch1-1-ARCH x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Gnome 3.32.2 
           Distro: Arch Linux 
Machine:   Type: Desktop Mobo: ASUSTeK model: ROG ZENITH EXTREME v: Rev 1.xx serial: <filter> UEFI: American Megatrends 
           v: 1701 date: 01/09/2019 
CPU:       Topology: 16-Core (2-Die) model: AMD Ryzen Threadripper 1950X bits: 64 type: MT MCP MCM arch: Zen rev: 1 
           L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 217648 
           Speed: 1966 MHz min/max: 2200/3400 MHz Core speeds (MHz): 1: 2292 2: 2533 3: 1972 4: 2338 5: 1852 6: 1886 7: 2106 
           8: 3719 9: 2719 10: 2647 11: 1900 12: 1998 13: 1835 14: 1999 15: 2634 16: 2796 17: 1997 18: 1994 19: 2799 20: 1997 
           21: 2794 22: 1961 23: 1952 24: 2000 25: 2113 26: 3696 27: 2000 28: 2343 29: 2558 30: 1999 31: 1752 32: 2340 
Graphics:  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] vendor: ASUSTeK driver: vfio-pci v: 0.2 bus ID: 08:00.0 
           Device-2: Advanced Micro Devices [AMD/ATI] Lexa XT [Radeon PRO WX 3100] driver: amdgpu v: kernel bus ID: 42:00.0 
           Device-3: NVIDIA GP102 [GeForce GTX 1080 Ti] vendor: ASUSTeK driver: vfio-pci v: 0.2 bus ID: 43:00.0 
           Display: wayland server: X.Org 1.20.4 driver: vfio-pci tty: N/A 
           OpenGL: renderer: AMD Radeon Pro WX3100 (POLARIS12 DRM 3.30.0 5.1.2-arch1-1-ARCH LLVM 8.0.0) v: 4.5 Mesa 19.0.4 
           direct render: Yes 
Audio:     Device-1: NVIDIA GP102 HDMI Audio vendor: ASUSTeK driver: vfio-pci v: 0.2 bus ID: 08:00.1 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 0a:00.3 
           Device-3: AMD Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] driver: snd_hda_intel v: kernel 
           bus ID: 42:00.1 
           Device-4: NVIDIA GP102 HDMI Audio vendor: ASUSTeK driver: vfio-pci v: 0.2 bus ID: 43:00.1 
           Sound Server: ALSA v: k5.1.2-arch1-1-ARCH 
Network:   Device-1: Intel I211 Gigabit Network vendor: ASUSTeK driver: igb v: 5.6.0-k port: 2000 bus ID: 03:00.0 
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Aquantia AQC107 NBase-T/IEEE 802.3bz Ethernet [AQtion] vendor: ASUSTeK driver: atlantic v: 2.0.4.0-kern 
           port: 2000 bus ID: 05:00.0 
           IF: enp5s0 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-1: macvtap0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-2: macvtap1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 2.73 TiB used: 271.98 GiB (9.7%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO 1TB size: 931.51 GiB 
           ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO 1TB size: 931.51 GiB 
           ID-3: /dev/sda vendor: Western Digital model: WD10EADS-42P6B0 size: 931.51 GiB 
           ID-4: /dev/sdb vendor: Apple model: HDD WD10EZES-40UFAA0 size: 931.51 GiB 
Partition: ID-1: / size: 915.60 GiB used: 271.92 GiB (29.7%) fs: ext4 dev: /dev/nvme1n1p2 
           ID-2: /boot size: 299.4 MiB used: 57.2 MiB (19.1%) fs: vfat dev: /dev/nvme1n1p1 
Sensors:   System Temperatures: cpu: 34.9 C mobo: N/A gpu: amdgpu temp: 56 C 
           Fan Speeds (RPM): cpu: 0 gpu: amdgpu fan: 1999 
Info:      Processes: 506 Uptime: 47m Memory: 62.83 GiB used: 20.26 GiB (32.3%) Init: systemd Compilers: gcc: 8.3.0 
           clang: 8.0.0 Shell: bash v: 5.0.7 inxi: 3.0.34 
```

**Comment by gnif** [comment]
> But i cant use the latest client, with the A12 looking-glass-host because it say it expect version 8 but got 6 (what ever this means).

Because you need to upgrade the looking glass host application AND the client application.

Please wait for B1 to be released, the host application has been overhauled along with hundreds of changes to the client application that improve many things, and fix many bugs.

**Comment by lunainvictum** [comment]
Yes i know. 

When is the release of B1? Because like i said, the latest looking glass host crash at start.

**Comment by gnif** [comment]
When it's ready
