### ISSUE TITLE
[feature request] "Cohesive" mode for non-gaming/productivity workflows

### ISSUE THREAD

**Issue by wis** [gnif/LookingGlass#163]
Hi, I appreciate the awesome work you're doing.
have you seen [Parallels' Cohesive mode](https://youtu.be/NRHQsHeOMKc?t=25) before?
I am more reasoning by analogy than first principles here, but I believe you can use the API [OBS](https://github.com/obsproject/obs-studio) uses to capture windows, I believe it's a different, less performant capture API than [DXGI desktop duplication](https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/desktop-dup-api), but since the use case is non-gaming it's not an issue.
instead of one shared memory buffer, you'll need one for each window on the guest, and a window on the host side for each one, instead of one window.

by the way, you should enable the [sponsor button](https://help.github.com/articles/displaying-a-sponsor-button-in-your-repository), like the OBS-studio repo I linked.

**Comment by csnewman** [comment]
OBS is using the GDI capture API, its older api, but as long as you are careful when creating the bitmaps you can get decent performance.

**Comment by wis** [comment]
it [looks like](https://github.com/obsproject/obs-studio/search?q=GetDC&unscoped_q=GetDC) OBS uses [`GetDC(handle)`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getdc) from the GDI API to capture windows and DXGI to capture screens.
it doesn't work with UWP apps, Chrome, Firefox and every other program rendered with a technique that bypasses GDI, and there's no alternative Windows API.
sources: [OBS author comment on Reddit](https://www.reddit.com/r/Twitch/comments/82vixd/how_to_capture_calculator_in_obs_window_capture/dvdc1a3/) , [Jim's reply to a OBS' issue tracker issue](https://obsproject.com/mantis/view.php?id=1128#c3086)

I can think of ways of getting around this Windows API issue, and how  they make the job more complicated.

**Comment by csnewman** [comment]
Another implementation is instead to send window metadata along with each frame, such as the regions of each windows, and what order they are in. And then get the client to handle the rendering of them separately without the host having to handle it.

**Comment by wis** [comment]
I should mention that I'm only talking about non-minimized windows,
the `GetDC` API can capture windows that are _overlayed by_/_under_ other windows.

you're talking about getting each programs' window's dimensions ([RECT](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowrect)) to capture an area of that dimensions from the DXGI desktop duplication screen capture API?

I believe screen area window capturing/"cropping" is better being done on the guest.

the issues I was talking about that need getting around are capturing multiple problematic programs' windows that can't be on top of each other (to capture and display the whole window of both) and can't fit on the screen's real estate. I believe both APIs should be used, `GetDC` and screen area capturing for problematic programs' windows, problematic programs' windows should always be on top of non-problematic (`GetDC` capturable) programs' windows and side by side to and never on top of other problematic programs' windows.

I propose using blacklisting programs that are not `GetDC` capturable by program name and optionally its [window class name/s](https://docs.microsoft.com/en-us/windows/desktop/winmsg/about-window-classes#class-name), only if there's no way of programatically figuring out if the program is `GetDC` capturable, and I believe there is.
there are heuristics to check if the window is a UWP window (by it's handle, IIRC), I have done it before, 2 years ago, what's left are all of the other non-UWP programs published out there that bypass GDI when rendering, like Chromium and Firefox, they can start off with `GetDC` capturing, detect if the captured output is blank black for a few seconds and try to fail over to screen area window capturing, if output remains blank black go back to `GetDC` capturing, because it's likely the real output and not an API issue ...for a few seconds and if the output remains blank black cycle back to screen area window capture, etc...

**Comment by gnif** [comment]
What you're asking for is normally called "Seamless Mode", it is something i'd like to investigate in the future but at this time it is not one of LG's goals.
