### ISSUE TITLE
Feature request: Method to send alt+ctrl+Fx and alt-ctrl-del

### ISSUE THREAD

**Issue by cmdrkotori** [gnif/LookingGlass#165]
### Required information

Host CPU: AMD Ryzen 7 2700X
Host GPU: Sapphire RX580
Guest GPU: Sapphire RX560
Host Kernel version: 5.1.5-arch1-2-ARCH 
Host QEMU version: QEMU emulator version 4.0.0
Looking-glass version: a12.r106.g182c475-1

I was running a debian vm and wanted to switch to a virtual terminal.

**Comment by gnif** [comment]
Did you try capturing the keyboard first?

**Comment by cmdrkotori** [comment]
Yes, it switched the virtual terminal on the host.

**Comment by gnif** [comment]
Ah, I see. Perhaps a <kbd>ScrLck</kbd>+<kbd>Fn</kbd> keybind would be appropriate?

**Comment by cmdrkotori** [comment]
Yes that would be fine.
