### ISSUE TITLE
Looking Glass blocking desktop after terminating in fullscreen

### ISSUE THREAD

**Issue by Ex0danify** [gnif/LookingGlass#172]
### Required information

Host CPU: AMD Threadripper 2950X
Host GPU: AMD RX560
Guest GPU: Nvidia RTX 2070
Host Kernel version: 4.20.17-1-MANJARO
Host QEMU version: QEMU emulator version 4.0.0
LookingGlass Version: B1-rc5

I run looking-glass-client with options -s -F. Once I kill the application in terminal with strg+c the last picture it showed freezes and blocks the entire desktop. It is always on top. I'm running a gnome Desktop on Wayland. This only seems to happen when I run the -F option.

Console output:
[Ex0@SkyFire ~]$ looking-glass
[I]               main.c:966  | run                            | Looking Glass (B1-rc4-0-g026bdb00f2+1)
[I]               main.c:967  | run                            | Locking Method: Atomic
[I]               main.c:986  | run                            | Wayland detected
[I]               main.c:993  | run                            | SDL_VIDEODRIVER has been set to wayland
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1204 | run                            | Waiting for host to signal it's ready...
[I]                egl.c:450  | egl_render_startup             | Vendor  : X.Org
[I]                egl.c:451  | egl_render_startup             | Renderer: Radeon RX 560 Series (POLARIS11, DRM 3.27.0, 4.20.17-1-MANJARO, LLVM 8.0.0)
[I]                egl.c:452  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.0.6
^C[I]               main.c:845  | int_handler                    | Caught signal, shutting down...

**Comment by gnif** [comment]
You're using Wayland and it's likely the cause. At this time Wayland is not officially supported, if you choose to use it under Wayland it is up to you to debug and diagnose this issue.
