### ISSUE TITLE
lookinglass host crashes when using windows snipping tool 

### ISSUE THREAD

**Issue by stevwills** [gnif/LookingGlass#175]
### Required information

Host CPU: i7 4790k
Host GPU: gtx 770
Guest GPU: gtx 970
Host Kernel version: Linux 5.1.4-arch1-1-vfio
Host QEMU version: qemu-4.0.0-2

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

Using windows snipping tool causes the looking glass host to crash  the moment i select what i want to snip.
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/3316000/looking-glass-host.txt)

**Reports that do no include this information will be ignored and closed**

**Comment by gnif** [comment]
Please update the host, you're running a very old version.

**Comment by stevwills** [comment]
oh ok.. turns out using the latest ''bleeding edge'' fixes the issue.  just thought the other releases where more stable or something. thanks for the reply. :) and keep on the good work. this software is amazing. :)
