### ISSUE TITLE
No output or apparent option support from looking-glass-host.exe

### ISSUE THREAD

**Issue by atobenzo** [gnif/LookingGlass#180]
Hello,

I am trying to use the IVSHMEM device selection support with looking-glass-host.exe B1-rc6 / 607539a2 but I am not having any luck. It seems that whatever arguments I specify on the command line are ignored, and nothing is output on the terminal (tried in command prompt and powershell) nor in looking-glass-host.txt. Shouldn't there be some kind of output if a command-line option is not processed?

p.s. thank you for Looking Glass, it's part of what makes it possible for me to play games on my Optimus laptop without booting into Windows, I've made a small paypal donation to show my appreciation

**Edit:** my VM is Windows 10

**Comment by gnif** [comment]
The host at this time can only output to a posix style terminal (ie, gitbash) or a log file directly.

**Comment by Ameb** [comment]
As a workaround you can disable the other IVSHMEM Device before starting LG, then reenable afterwards. Worked for my while using scream.
