### ISSUE TITLE
Newer versions of looking-glass-host don't return any error information with -f flag

### ISSUE THREAD

**Issue by seeker25** [gnif/LookingGlass#181]
### Required information

Host CPU: Ryzen 2600x
Host GPU:GTX 1060 
Guest GPU:GTX 1060
Host Kernel version: 5.1.16
Host QEMU version:3.1
Windows 10 version 1809

My guest for example would have a bad GPU driver, and when I run the release from 
B1-rc6, looking-glass-host.exe just closes immediately with no feedback even with the -f flag enabled. 

If I run the old a11 looking-glass-host.exe it tells me the issue inside of the console. 

This can be quite confusing for new users that don't have their system properly configured.

**Comment by gnif** [comment]
Not a bug, see the readme file, a log file is produced.

**Comment by seeker25** [comment]
Can we get some documentation around this logfile? I could be wrong, but I didn't see mention of it anywhere while setting up.

**Comment by Ameb** [comment]
[on the c-host README](https://github.com/gnif/LookingGlass/tree/master/c-host#where-is-the-log)

**Comment by seeker25** [comment]
That's pretty buried, put it on the site itself. 

https://looking-glass.hostfission.com/quickstart/win/host

**Comment by gnif** [comment]
You are using a pre-release version, the website documentation is for A12. When B1 is released it will be updated.
