### ISSUE TITLE
Mouse doesn't work if clipboard synch is working

### ISSUE THREAD

**Issue by iehgit** [gnif/LookingGlass#182]
### Required information

Host CPU: Ryzen7
Host GPU: RadeonHD7900
Guest GPU: AMD Vega64
Host Kernel version: 5.0.2
Host QEMU version: 3.1

I'm using version B1. If I add an spice channel to the vm (as such: https://www.spice-space.org/agent-protocol.html), the clipboard synchronization starts working, but the guests mouse cursor gets no longer updated through the looking glass window and no guest cursor is shown in the looking glass window. If I remove the spice channel, clipboard synch no longer works, but the mouse cursor works seamlessly through the looking glass window as it should.
Is it possible to use mouse and clipboard at the same time?

**Comment by gnif** [comment]
It certainly is, it's how it's intended to work, if there is an issue here please double check your VM configuration. This is not a LG bug.
