### ISSUE TITLE
[client] Missing make dependency Ubuntu

### ISSUE THREAD

**Issue by ahorn42** [gnif/LookingGlass#183]
### Required information

Host CPU: I9 9900K
Host GPU: Intel CPU internal
Guest GPU: AMD Radeon Pro Duo Polaris
Host Kernel version: 5.0.0-21-generic
Host QEMU version: 3.1.0 (Debian 1:3.1+dfsg-2ubuntu3.2)

When following the build instructions on https://looking-glass.hostfission.com/quickstart/linux/build I found that the package `binutils-dev` was missing to run the make file on Kubuntu 19.04

Maybe this should be included in the list :)

best regards!

**Comment by gnif** [comment]
Read the release information
