### ISSUE TITLE
Remark on Apparmor configuration to allow the host to access shm device

### ISSUE THREAD

**Issue by ahorn42** [gnif/LookingGlass#184]
### Required information

Host CPU: I9 9900K
Host GPU: Intel CPU internal
Guest GPU: AMD Radeon Pro Duo Polaris
Host Kernel version: 5.0.0-21-generic
Host QEMU version: 3.1.0 (Debian 1:3.1+dfsg-2ubuntu3.2)

While following the instructions on https://looking-glass.hostfission.com/quickstart/linux/libvirt I had the problem that I/virtmanager did not get access to `/dev/shm/looking-glass`

I found a post on reddit that helped me to solve the issue: https://www.reddit.com/r/VFIO/comments/8o13i4/cant_start_vm_with_lookingglass_shared_memory/

In the end it was necessary to add an additional rule to apparmor. 

Add `/{dev,run}/shm/lookingglass rw,` to `/etc/apparmor.d/abstractions/libvirt-qemu` and restart Apparmor with `systemctl restart apparmor.service`

I think I would help some people to put a note at the install instructions about this :)

best regards!

**Comment by gnif** [comment]
Issues are for bug reports only.

**Comment by ahorn42** [comment]
Well - where would be the place to report things like that? As Apparmor seems to be installed on ubuntu by default I think many people will encounter this problem.

By the way looking-glass is really awesome! Got it running quite fast and till now everything seems to work well :-)

**Comment by Noext** [comment]
this fix dont work on manjaro
