### ISSUE TITLE
Failed to create EGL surface (eglError: 0x3005)

### ISSUE THREAD

**Issue by thandlovsky** [gnif/LookingGlass#186]
### Required information

Host CPU: AMD Ryzen 2700
Host GPU: AMD RX 550
Host GPU Drivers: 19.20-812932
Guest GPU: Nvidia P1000
Guest GPU Drivers: 431.70
Host Kernel version: 5.0.0-23
Host QEMU version: 1:2.11+dfsg-1ubuntu7.1

Looking Glass Client Version: B1-rc6-5-g8ad2d5f949+1
Looking Glass Host Version:  B1-rc6-6-gb979752989+1

Failure on start of Looking Glass
```
[I]          main.c:996  | run                              | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]          main.c:997  | run                              | Locking Method: Atomic
[I]          egl.c:187  | egl_initialize                   | Double buffering is on
[I]          egl.c:201  | egl_initialize                   | Multsampling enabled, max samples: 4
[I]          main.c:902  | try_renderer               | Using Renderer: EGL
[I]          main.c:1183 | run                             | Using Clipboard: X11
[I]          main.c:1259 | run                             | Waiting for host to signal it's ready...
[E]         egl.c:428  | egl_render_startup        | Failed to create EGL surface (eglError: 0x3005)
```
When run under gdb with cmake -DCMAKE_BUILD_TYPE=Debug ../
```
(gdb) r
Starting program: /home/hostadm/Documents/LookingGlass-B1/client/build/looking-glass-client -s -a -k -n
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[W]               main.c:1031 | run                            | ================================================================================
[W]               main.c:1032 | run                            | WARNING: The FPS display causes microstutters, this is a known issue
[W]               main.c:1033 | run                            | ================================================================================
[New Thread 0x7fffe89ff700 (LWP 17369)]
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[New Thread 0x7fffe59ff700 (LWP 17370)]
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...
[Thread 0x7fffe89ff700 (LWP 17369) exited]
[E]                egl.c:428  | egl_render_startup             | Failed to create EGL surface (eglError: 0x3005)
[Thread 0x7fffe59ff700 (LWP 17370) exited]
[Inferior 1 (process 17365) exited normally]
```

Output of 
```
(gdb) bt
No stack.

```
Log from Host Looking Glass
```
[I]                app.c:292  | captureStart                   | ==== [ Capture  Start ] ====
[I]                app.c:65   | pointerThread                  | Pointer thread started
[I]                app.c:160  | frameThread                    | Frame thread started
[I]                app.c:350  | app_main                       | Looking Glass Host (B1-rc6-6-gb979752989+1)
[I]                app.c:351  | app_main                       | IVSHMEM Size     : 32 MiB
[I]                app.c:357  | app_main                       | IVSHMEM Address  : 0x2CC0000
[I]                app.c:366  | app_main                       | Max Cursor Size  : 1 MiB
[I]                app.c:367  | app_main                       | Max Frame Size   : 15 MiB
[I]                app.c:368  | app_main                       | Cursor           : 0x2CC0080 (0x00000080)
[I]                app.c:374  | app_main                       | Frame 0          : 0x2DC0080 (0x00100080)
[I]                app.c:374  | app_main                       | Frame 1          : 0x3D40000 (0x01080000)
[I]                app.c:381  | app_main                       | Trying           : NVFBC (NVidia Frame Buffer Capture)
[I]          wrapper.cpp:88   | NvFBCInit                      | NvFBC SDK Version: 112
[I]                app.c:381  | app_main                       | Trying           : DXGI
[I]               dxgi.c:322  | dxgi_init                      | Device Descripion: NVIDIA Quadro P1000
[I]               dxgi.c:323  | dxgi_init                      | Device Vendor ID : 0x10de
[I]               dxgi.c:324  | dxgi_init                      | Device Device ID : 0x1cb1
[I]               dxgi.c:325  | dxgi_init                      | Device Video Mem : 4019 MiB
[I]               dxgi.c:326  | dxgi_init                      | Device Sys Mem   : 0 MiB
[I]               dxgi.c:327  | dxgi_init                      | Shared Sys Mem   : 4094 MiB
[I]               dxgi.c:328  | dxgi_init                      | Feature Level    : 0xc100
[I]               dxgi.c:329  | dxgi_init                      | Capture Size     : 1920 x 1080
[I]               dxgi.c:418  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
[I]                app.c:282  | captureStart                   | Using            : DXGI
[I]                app.c:290  | captureStart                   | Capture Size     : 7 MiB (8294400)
[I]                app.c:292  | captureStart                   | ==== [ Capture  Start ] ====
[I]                app.c:65   | pointerThread                  | Pointer thread started
[I]                app.c:160  | frameThread                    | Frame thread started
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
[I]                app.c:426  | app_main                       | Client restarted
```

This is a fresh install of Ubuntu 18.04.3 so it might be a configuration issue since I am still getting used to Looking Glass and have only set it up a couple times.

**Comment by thandlovsky** [comment]
So it looks as though the amdgpu-pro drivers were at fault. Uninstalling and using opensource amdgpu drivers works and gives following:

[I]               main.c:996  | run                            | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[I]              spice.c:197  | spice_connect                  | Remote: 127.0.0.1:5900
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...
[I]              spice.c:409  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]                egl.c:447  | egl_render_startup             | Vendor  : X.Org
[I]                egl.c:448  | egl_render_startup             | Renderer: Radeon 550 Series (POLARIS12, DRM 3.27.0, 5.0.0-23-generic, LLVM 8.0.0)
[I]                egl.c:449  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.0.2
[I]               main.c:1268 | run                            | Host ready, starting session

**Comment by compucat** [comment]
Duplicated this. I'd argue this should be reopened - if the answer to "I use amdgpu-pro drivers" is "switch your drivers, AMD's official driver isn't supported", this creates issues for anyone who can't switch away from amdgpu-pro. For example, I am currently stuck unable to use FOSS amdgpu drivers because a nasty Mesa bug in the current stable and dev releases causes certain applications - notably, OBS Studio - to leak kernel memory hundreds of MB/s, crashing my system within seconds.

Are we sure this is a bug in amdgpu-pro itself, or can Looking Glass be modified to work correctly on both pro and FOSS drivers?

**Comment by gnif** [comment]
Looking Glass conforms to the OpenGL ES Native Platform Graphics Interface, even if there is a workaround, we will not include workarounds for driver bugs that can and should be fixed upstream

Please be aware that AMD are no longer maintaining the amdpro kernel module or mesa libraries, all efforts are going into the open drivers. The only still maintained part of amdgpu is the opencv shared objects.

Also please note that I am using the FOSS amdgpu module(both on Vega and Navi) with the amdpro userspace libraries with zero issues.

**Comment by compucat** [comment]
What distro are you using? I'm using that same config: FOSS amdgpu module with amdgpu-pro userspace on multiple Vega cards. This is to avoid a GL bug in latest upstream (and Ubuntu 19.10's version of) Mesa userspace with OBS; the pro drivers don't have the bug. (That said, they introduce other issues as well, so I'm considering reverting to an old version of Mesa instead.)

https://gitlab.freedesktop.org/mesa/mesa/issues/1426

**Comment by gnif** [comment]
Debian 10 with mesa and libva, etc from sid. Currently, I am running a kernel I built from the AMD git repository so as to obtain 5700XT support, however, I was using the standard 5.3 official kernel from Debian on the Vega 56 with no issue for months before changing.
