### ISSUE TITLE
Feature request: Grab mouse?

### ISSUE THREAD

**Issue by original-dotexe** [gnif/LookingGlass#187]
It would be nice to have a feature to grab the mouse (for use when gaming). Something like in VirtualBox where you can click into the window to grab the mouse, and then press super+ctrl to un-grab it. Looks like we already have the functionality to grab the keyboard, so I don't imagine it would be that hard to add the same thing for the mouse?

**Comment by gnif** [comment]
It already has that feature, please read the documentation. Press Screen Lock.

**Comment by original-dotexe** [comment]
alright. sorry bout that. thanks for the info :)
