### ISSUE TITLE
Secret int magic[] to enable NvFBC on GeForce

### ISSUE THREAD

**Issue by ValZapod** [gnif/LookingGlass#188]
Have you seen this patch? 
https://pastebin.pl/view/raw/45421e05

It can activate NvFBC on GeForce... I suppose it should be applied on top of https://github.com/gnif/LookingGlass/blob/163a2e5d0a1168637da2524717b1328165c3c0b0/c-host/platform/Windows/capture/NVFBC/src/wrapper.cpp#L117

**Comment by gnif** [comment]
I am sorry but you will get no support or information from here on how to bypass NVidia's non pro card NvFBC policy, or if it's even possible.

**Comment by ValZapod** [comment]
@gnif 
Whatever, it is possible for me.

**Comment by gnif** [comment]
I have edited your post because you are sharing information on this project that could get this project in legal jeopardy. I am bound by the NVIDIA SDK EULA to not provide methods to work around/enable pro features on consumer cards.

https://developer.nvidia.com/capture-sdk-software-license-agreement

> 1.1                License Grant. Subject to the terms of this Agreement, NVIDIA hereby grants you a nonexclusive, non-transferable, worldwide, revocable, limited, royalty-free, fully paid-up license to during the term of this Agreement:
>
> (i)                   install, use and reproduce the software delivered by NVIDIA, make modifications and create derivative works of sample source code software delivered by NVIDIA and use documentation delivered by NVIDIA, **provided that the software is executed only in NVIDIA GRID, Tesla or Quadro 2000+ hardware products** that you separately obtain from NVIDIA or its affiliates, all to develop, test and service your products (each, a “Customer Product”) that are interoperable with NVIDIA GRID, Tesla or Quadro 2000+ hardware products;

> You are liable for the distribution and the use of distributed software if you failed to comply or enforce the distribution requirements of this Agreement. You agree to notify NVIDIA in writing of any known or suspected use or distribution of the Licensed Software that are not in compliance with the terms of this Agreement.

**Comment by ValZapod** [comment]
FYI, you did not hide it entirely. Githib provides ability to show edited text. 


And besides that if you did not sign anything with Nvidia affiliation in your country (NDA or anything like this), your are not bound by anything. Besides that Nvidia obviously violated international laws by this. So any NDA becomes invalid. DMCA does not work either (your main concern, I hope). So do not be afraid.

**Comment by gnif** [comment]
How do you know what I did or did not sign?
