### ISSUE TITLE
Cannot make latest release of looking glass client due to missing file bfd.h

### ISSUE THREAD

**Issue by wk32** [gnif/LookingGlass#189]
Hi, 

I was trying to build the latest official release of the client, and encountered this error:

```
LookingGlass-Release-B1/common/src/bfd.inc.h:5:14: fatal error: bfd.h: No such file or directory
     #include <bfd.h>
              ^~~~~~~
compilation terminated.
common/CMakeFiles/lg_common.dir/build.make:101: recipe for target 'common/CMakeFiles/lg_common.dir/src/crash.linux.c.o' failed
make[2]: *** [common/CMakeFiles/lg_common.dir/src/crash.linux.c.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'common/CMakeFiles/lg_common.dir/all' failed
make[1]: *** [common/CMakeFiles/lg_common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

I solved it by installing binutils-dev on Ubuntu 18.04 Pop OS
### Required information

Host CPU: Ryzen 3700x
Host GPU: Nvidia RTX 2060 Super
Guest GPU: Nvidia GT 1030
Host Kernel version: 5.1.21
Host QEMU version: 4.0.0

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do no include this information will be ignored and closed**

**Comment by gnif** [comment]
https://github.com/gnif/LookingGlass/blob/master/client/README.md

**Comment by wk32** [comment]
i was following instructions from https://looking-glass.hostfission.com/quickstart/linux/build and it wasn't listed there. Maybe you could just link it to the readme you provided to avoid the confusion

**Comment by gnif** [comment]
Yes, I have been trying to find time to update the website to point to these as the new authority for information. Thanks :)
