### ISSUE TITLE
Add option to specify IVSHMEM device in Windows host.

### ISSUE THREAD

**Issue by misiut** [gnif/LookingGlass#190]
Please consider adding possibility to specify f.e. bus and device for host software or something similar. 
I'm asking this, because i found another project at https://github.com/duncanthrax/scream that is doing similar thing You doing but for sound through IVSHMEM.

Both solutions work great on their own. Picture is good with Looking Glass and sound is flawless with Scream, unlike qemu's solutions. However when I try to use them both then somehow Looking Glass is always trying to grab Scream's IVSHMEM 2MB device, instead its own. 

Of course I tried changing order of devices, qemu slots, etc. but somehow only one works or the other. I managed to get them to work together once, by removing IVSHMEM device of Scream and restarting. Then seems like Looking Glass got hold of its device before Screams one enumerated after VM restart, but its wonky and unreliable.

**Comment by JJRcop** [comment]
In a `looking-glass-host.ini` file in the same directory as the windows host. In it, you can use the os:shmDevice option like so:
```ini
[os]
shmDevice=1
```

The numbers start at 0. 0 is the first device, 1 is the second, 2 is the third, et cetera. By default it chooses the first device.

**Comment by misiut** [comment]
Thank you. 
Should change title to "Update documentation" then, because I was looking before I asked. Also tried looking-glass-host.exe -h , /?, --help and got nothing. Also spent like hour looking through source of c-host to find some hints with no luck...
