### ISSUE TITLE
Can I provide a parameter to switch the screen cursor capture mode to server mode when the look-glass-client is running?

### ISSUE THREAD

**Issue by daiaji** [gnif/LookingGlass#191]
My mouse provides multiple function keys.
I want to use mouse macros to make these buttons available to run Looking Glass or switch between screen cursor capture mode and application window switching.😀

**Comment by gnif** [comment]
The capture key is configurable, if you can map a mouse button to a scancode in X, you should be able to do it.

Please note that github issues are for bug reports only, if you want further help please see the L1Tech forums.

**Comment by daiaji** [comment]
But I found that the SDL Scancode Lookup Table does not include my mouse button...
SDL_MouseButtonEvent may be more useful.

And when I tried to map the mouse button to the Scroll Lock key using xbindkeys and xdotool, I found that once the server mode was turned on, my mouse button event was hijacked and I couldn't use the mouse button to exit server mode.

```
$ xev
KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  4294967241 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

ButtonRelease event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x5200002, time 8006549, (23,48), root:(23,77),
    state 0x10, button 11, same_screen YES

LeaveNotify event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x0, time 8006549, (23,48), root:(23,77),
    mode NotifyUngrab, detail NotifyInferior, same_screen YES,
    focus YES, state 16

ButtonPress event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x5200002, time 8006637, (23,48), root:(23,77),
    state 0x10, button 11, same_screen YES

EnterNotify event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x0, time 8006637, (23,48), root:(23,77),
    mode NotifyGrab, detail NotifyInferior, same_screen YES,
    focus YES, state 16

KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  4294967241 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

ButtonRelease event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x5200002, time 8006741, (23,48), root:(23,77),
    state 0x10, button 11, same_screen YES

LeaveNotify event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x0, time 8006741, (23,48), root:(23,77),
    mode NotifyUngrab, detail NotifyInferior, same_screen YES,
    focus YES, state 16

ButtonPress event, serial 37, synthetic NO, window 0x5200001,
    root 0x6c9, subw 0x5200002, time 8006829, (23,48), root:(23,77),
    state 0x10, button 11, same_screen YES

```

**Comment by gnif** [comment]
Because scan codes are not mouse events. There is no simple way to implement this nor is it wanted by the majority of people. I am sorry but unless there is sufficient motivation to implement this you will either need to find an alternative solution or implement it yourself.

**Comment by daiaji** [comment]
Can understand, but it seems very difficult to map the mouse button to the keyboard button, or can you set a white list for button hijacking? This way at least my mouse button will not be hijacked.🙏
