### ISSUE TITLE
Request for 40-bit RGBA Support

### ISSUE THREAD

**Issue by minmossi** [gnif/LookingGlass#192]
If the both GPUs on Windows side and on Linux side support 40-bit RGBA on DirectX/OpenGL draw, can you make the screen through Looking Glass SPICE display produce 40-bit RGBA? Currently the Looking Glass homepage specifically mentions, "... all frames are transferred to the viewer (client application) in 32-bit RGBA without any transformations or modifications".

This addition will be great for playback of 10-bit(40-bit) color format video or using Photoshop, Premiere, etc.

**Comment by gnif** [comment]
It already supports this.

https://github.com/gnif/LookingGlass/blob/6d2c46443683c1dfe68601c80a35faf43020ff8c/c-host/platform/Windows/capture/DXGI/src/dxgi.c#L424

https://github.com/gnif/LookingGlass/blob/6d2c46443683c1dfe68601c80a35faf43020ff8c/client/renderers/EGL/desktop.c#L201
