### ISSUE TITLE
Stream captured video

### ISSUE THREAD

**Issue by luqasz** [gnif/LookingGlass#193]
Hi.

Do you plan to support streaming video through LAN connection ? This can open many use cases etc. Simmilar "thing" exists in steam but it is reduced to only stream games.

**Comment by r4m0n** [comment]
There is no interest in streaming though this app, though there were plans on using it as a source for OBS if you really want to do that. But you're wrong on your second point, you CAN stream anything using Steam, just add it as an external game and it'll happily stream it to any devices on your LAN.

**Comment by luqasz** [comment]
> There is no interest in streaming though this app

I am interested 😄 

Seriusly though, it would be possible to use a separate PC and even place it in other room etc. Maybe even use same PC with multiple GPUs and VMs.

**Comment by gnif** [comment]
There are other solutions to this, Looking Glass does not intend to support streaming over LAN, it defets the entire purpose of this application which is to be extremely low latency.
