### ISSUE TITLE
eglError: 0x3005

### ISSUE THREAD

**Issue by BayleyPap** [gnif/LookingGlass#194]
Host CPU: Ryzen 7 1700x
Host GPU: GeForce GT 1030
Guest GPU: GeForce GTX 970
Host Kernel version: 5.2.13-200.fc30.x86_64
Host QEMU version: EMU emulator version 3.1.1 (qemu-3.1.1-2.fc30)

Upon running a newly compiled client I get the error:
Failed to create EGL surface (eglError: 0x3005)
Note that looking glass was working fine previously.

**Comment by gnif** [comment]
Are you using nouveau or Nvidia's driver?
Also, please show the full client output, just just what you think is important.

**Comment by BayleyPap** [comment]
I am using the Nvidia driver, and how would I go about getting the output?

Thanks.

**Comment by gnif** [comment]
> Upon running a newly compiled client I get the error:

Just the entire output, not just the one line you selected.

**Comment by gnif** [comment]
Closing due to lack of information.
