### ISSUE TITLE
P2P DMA to Linux-side GPU's frame buffer?

### ISSUE THREAD

**Issue by minmossi** [gnif/LookingGlass#195]
I have some but limited knowledge of GPU hardware structure and programming. 

Anyway what I wanted to say is that, there are two facts: 1. "At least" between two Nvidia GPU, PCIe peer-to-peer direct memory access to each VRAM is possible. 2. NvENC ASIC can, of course, get data from main VRAM to encode(native memory buffer support).

So, it's possible that, Windows-side NVENC ASIC encodes Windows-side GPU's frame buffer to the resolution you want to show on Linux-side screen, and then, sends that from Windows-side video memory to Linux-sides, of which address is the each start of the scan line of Windows screen printed on Linux.

What I concern is that, since we passthrough-ed Windows-side GPU, it isn't going to be work like this but there can be possible alternation like NvLINK bridge which directly connects two separate GPUs.

**Comment by gnif** [comment]
It is not possible without SR-IOV support, IOMMU is designed specifically to prevent RAM access outside of the VM, even if DMA can be set up and started, it couldn't see the other PCIe device to perform the transfer to.
