### ISSUE TITLE
Why is there no Windows client?

### ISSUE THREAD

**Issue by makedir** [gnif/LookingGlass#196]
Why is this whole thing also not build in mind as a streaming solution (without encapsuled VM), also for Windows to Windows (and over network)? Other streaming solutions like Steam OnStream or Nvidias crap dont work properly and are a joke for several reasons.

A simple low latency good quality network streaming solution for Windows to Windows AND Linux would be simple and apreciated by way more people than just Windows to Linux only.

**Comment by mjarkk** [comment]
gnif has sad something about this in a similar issue that might give you the answer..  
> There are other solutions to this, Looking Glass does not intend to support streaming over LAN, it defets the entire purpose of this application which is to be extremely low latency.

**Comment by gnif** [comment]
@mjarkk is correct. And there is no Windows Client because nobody has needed one yet.
