### ISSUE TITLE
KDE Plasma dashboard uggly on quit 

### ISSUE THREAD

**Issue by JeromeL63** [gnif/LookingGlass#197]
(host : mycomputer
guest : the VM)

Hello,
What a great job you've done !!! it rock's
But i've got a little bug when I close looking-glass window.
I have two screens, Looking-glass is launched on screen 1, and on screen 2 when i close the window, the dashboard is quite uggly 
![Screenshot_20190922_151655](https://user-images.githubusercontent.com/16070808/65388324-4cf6b380-dd4c-11e9-9500-a472e2fa33e4.png)
So, if I restart looking-glass, the dashboard become normal.... Oh, another thing, my screen 2 is linked to the guest gpu with HDMI, and to the host gpu with DVI.... because looking glass can't start if no screen is linked on the guest gpu( known issue, and i understand that)

Host CPU: RYZEN 7 2700+
Host GPU: ATI Radeon HD 5830
Guest GPU: NVIDIA GTX 970
Host Kernel version: 4.19.0-6-amd64
Host QEMU version:QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u2)

**Comment by gnif** [comment]
This is not a fault or problem with LG, it's a Linux driver or Window manager fault.
