### ISSUE TITLE
Constant "Stream Paused" notification

### ISSUE THREAD

**Issue by r3t0x** [gnif/LookingGlass#198]
Host CPU: Intel i7-7700K
Host GPU: Intel HD Graphics 630
Guest GPU: NVIDIA GeForce GTX 1080 Ti
Host Kernel version: 5.3.1-arch1-1-ARCH 
Host QEMU version: 4.1.0

The "Stream Paused" notification is always present since upgrading to the official B1 release.  I downloaded and installed the bleeding edge release, but the issue is still there.  I am using Wayland, but it was not an issue in the previous release.

Please let me know how I can help.

![Screenshot of the log file in the Windows 10 Guest](https://user-images.githubusercontent.com/6479335/65555417-1a2df600-ded9-11e9-94e1-e55c2ca3b100.png)

Woops - forgot to add the output from the Host.
```
λ ~ → looking-glass-client 
[I]               main.c:1004 | run                            | Looking Glass (fetch-4-ge93bd7a3bf+1)
[I]               main.c:1005 | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]               main.c:910  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1191 | run                            | Using Clipboard: X11
[I]              spice.c:197  | spice_connect                  | Remote: 127.0.0.1:5900
[I]                egl.c:447  | egl_render_startup             | Vendor  : Intel Open Source Technology Center
[I]                egl.c:448  | egl_render_startup             | Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
[I]                egl.c:449  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.1.7
[I]               main.c:1266 | run                            | Waiting for host to signal it's ready...
[I]              spice.c:409  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]               main.c:1275 | run                            | Host ready, starting session
```

**Comment by gnif** [comment]
The new c-host client doesn't ever set the PAUSE flag, it's not yet implemented to do so. If it's getting set something else is doing it. Either you have faulty RAM or someone else like Scream Audio is in use and is causing the problem.

**Comment by r3t0x** [comment]
I ran memtest86 and everything passed, but it got me thinking about how I'm allocating hugepages in my script.  Perhaps there was some faulty data left behind in the ram allocated for the vm?  Either way, after running the memtest the issue is not there anymore.  Closing issue - thanks for your help!

**Comment by gnif** [comment]
No worries, however, it is strange and you should be on the lookout for any other issues with your system even still as LookingGlass initializes the shared ram at startup.
