### ISSUE TITLE
Mouse input stops working after toggling Capture (related to spice agent)

### ISSUE THREAD

**Issue by brandon3055** [gnif/LookingGlass#199]
### Required information

Host CPU: 2950x
Host GPU: GTX 1080
Guest GPU: Radeon R9 290
Host Kernel version: 5.0.0
Host QEMU version: 3.1.0

I am using the latest bleeding edge versions of both the host and client. I'm not looking for support. Just letting you know about a potential bug.  

When i start the VM and lookingglass everything works fine. I can move my cursor in and out of the lg window and it works as expected.
If i then use enable capture via Scroll Lock my mouse and keyboard are locked to the VM and everything works as expected.
The issue starts when i then disable capture. After disabling capture if i move my mouse into the vm window id disappears (as it should)
but the cursor on the vm side remains stationary. I can still re-enable capture which works as expected but i can no longer use my mouse
in the VM with capture disabled.     

This issue seems to be directly related to the spice guest agent i have running on the VM because restarting that fixes the issue.  
At least until i enable capture again.

**Comment by gnif** [comment]
This is not a LookingGlass issue, LG feeds cursor input to the spice server running in Qemu which in turn feeds hardware events to the VM to emulate cursor movement. If there is an issue here, it's with Qemu, not LG.

**Comment by karpfediem** [comment]
Stumbled across the same issue.
I think the default behavior of turning off "Capture Mode" with Scroll Lock should be **stopping the mouse/focus constraints** on the looking-glass window.
Currently however it disables any inputs from being passed to the VM (from what i can see as looking-glass user) until "Capture Mode" is enabled again.

**Comment by gnif** [comment]
@karpfediem without any version information, logs from Looking Glass or OS configuration there is nothing that I nor anyone else can do.

**Comment by karpfediem** [comment]
Host CPU: Ryzen 2600x
Host GPU: GT1030
Guest GPU: GTX 1080
Host Kernel version: Linux version 5.6.6-arch1-1 (linux@archlinux) (gcc version 9.3.0 (Arch Linux 9.3.0-1))
Host QEMU version: 4.2.0

I dont know where i can find looking-glass logs, but would be happy to provide, or run with debug options if there are any

**Comment by gnif** [comment]
Are you using Wayland by any chance? And have you tested on `master` to see if this has already been fixed?

**Comment by karpfediem** [comment]
Im using xorg-server.
I also tried the latest commit on master (both client + host) just now and the problem still occurs.
