### ISSUE TITLE
LookingGlass Host crashes on UAC Prompt

### ISSUE THREAD

**Issue by intdel** [gnif/LookingGlass#20]
Hello,

As far as I understand, it is normal that looking glass client looks unresponsive during UAC prompt. However, with the Keyboard (through spice) I could still somehow hit yes, or is that not possible?
If I hit the left arrow and then enter, then it seems to accept the UAC prompt (I double check with remote-viewer on the spice port).

However, looking glass host has crashed and I have to manually restart after every UAC prompt.

Is there any temporary workaround?

Thanks

**Comment by gnif** [comment]
No work around, please read the forum thread before opening issues like this. Issues are for confirmed bug reports, not "As far as I understand".

To answer your question though, UAC is on the "Secure Desktop" and by definition we can not interact with it or screen capture it.

**Comment by intdel** [comment]
Yes, but why does the process crash? Can it not just keep living until the Secure Desktop State is over?

**Comment by Verequies** [comment]
I have actually added an option to the host code to automatically restart on crash. Will cleanup the code and submit a pull request. It's also really handy when switching between multiple users. Couple of issues so have to figure my way around but after that it should be alright.

**Comment by intdel** [comment]
@Verequies Thanks. That should solve the issue!

**Comment by gnif** [comment]
restarts on crash will not be accepted as it will end up being used as a way to ignore a real problem. It is supposed to already handle the UAC dialog and wait for it to finish, debug that code before hacks are added please.

**Comment by Verequies** [comment]
Well pretty much what happens is that when it can't grab the screen, it does a re-initialisation request. However after a failed re-initialisation, it just quits saying that the re-initialisation fails. If you're fast enough with the UAC Prompts & CTRL+ALT+DELETE, you can get around it, else you have to restart the application. All I've done is add a -w option to the host executable that on crash, it just restarts WinMain. Which is pretty much what you're doing anyhow. The only way I can see to fix the current code is if you just keep requesting a re-initialisation. I will have a further look at it, however my fix was just a temporary solution I suppose.

**Comment by r4m0n** [comment]
I'd suggest removing all the "returns" on the main loop, and adding a block to wait for something like 200~500ms and continue back to the start in case of !ok. That should keep it in the main loop except when something really goes bad.

**Comment by Verequies** [comment]
Yeah, thats pretty much what I'm doing. Except if watchdog is true, it calls WinMain (at the very end of the loop before the application exits) again.

**Comment by gnif** [comment]
Please do not post unofficial builds here, we can not verify their integrity.

**Comment by gnif** [comment]
> Please next time take your time to understand my issue and not just search it for keywords and give a "default answer."

@intdel Please next time take the time to read the details on how to post a bug report, I do not have the time to deal with reports that do not follow a consistent format and/or do not provide enough information to diagnose and debug.

**Comment by gnif** [comment]
>  pretty much what you're doing anyhow.

@Verequies No I am not, it restarts only the capture layer, this only affects DXGI as NvFBC is fully capable of capturing the UAC prompts. The change yesterday to prevent stall when a client connects to a host that is not sending frames may have broken this logic, it is supposed to sit in a poll loop infinitely until it recovers, calling `OpenDesktop` until it scceeds.

**Comment by Verequies** [comment]
Yes, I realise it only affects DXGI (Having to deal with it as I'm on an older Quadro card (K1100M). What I'm saying is that yes, you're re-initialising the capture layer, however after once or twice it just bombs out. Have to decide whether to continue trying or to just exit after a couple of tries. Maybe we could pass an option through in the capture options where if specified it continues trying instead of bombing out. Anyhow, if you comment out https://github.com/gnif/LookingGlass/blob/287b983d27db29413abf18000dad025349e4255a/host/Capture/DXGI.cpp#L352

Then I found that it will continue capturing after UAC, CTRL+ALT+DELETE & Screen Locking events occur. I just the following instead:
`DEBUG_ERROR("Lost access to desktop");`

This does not fix the crash when switching users though. So I'll keep looking for a fix for that.

**Comment by gnif** [comment]
@Verequies Please open an issue for the switch users problem, while it exhibits the same behavior it is an entirely different issue.

**Comment by Verequies** [comment]
Just tested that commit, works just as well :) - much better fix than I did. Yep, I will open an issue for that, however I will also try to come up with a proper fix than just calling the ReInitialize until it succeeds. Thought I might hack around with this stuff as I will be doing a lot of stuff similar in CS next year.

**Comment by gnif** [comment]
CS? You mean C#? If so have fun :), C# hides all the fun memory stuff from you.

**Comment by Verequies** [comment]
Ah, I mean Computer Science. But yeah I've done some C# as well as C this year when helping a friend create a terminal based stick figure game lol. Anyhow I like C++, its just a little difficult to get your head around when looking at it for the first time.

**Comment by intdel** [comment]
@gnif Can confirm that your commit https://github.com/gnif/LookingGlass/commit/b77a34b8b6dcc143f47857d3c0103f12b6ca5fdb fixed the issue!

Thanks
