### ISSUE TITLE
Client/Server does not properly support cursors which invert pixels

### ISSUE THREAD

**Issue by kode54** [gnif/LookingGlass#200]
### Required information

Host CPU: AMD Ryzen 7 2700
Host GPU: Asus ROG Strix GeForce GTX 960
Guest GPU: Asus ROG Strix AMD RX 480 O8G
Host Kernel version: 5.3.1-arch1-1-ARCH *1
Host QEMU version: 4.1.0

*1: Custom build from official ABS, with two patch sets applied:

1: https://patchwork.freedesktop.org/series/64505/
2: https://gist.github.com/kode54/bdfedc26a08df3f5ed9dc831660e57f0 (mirroed from https://clbin.com/VCiYJ)

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

The Looking Glass client was built with the stable AUR package. It is being run as:

```
sudo -E looking-glass-client -s -F -S
```

It works perfectly, except for one minor issue so far:

Cursors such as Windows' default I-beam text selection cursor, which are 100% white pixels designed to be XOR-d against the underlying image, is rendered as a solid white I-beam, and becomes almost invisible on white text boxes. I can work around this by changing my mouse cursor, I hope, but it would be nice to see this supported in the server or client or possibly both, if this is something that needs to be done at both ends of the chain.

**Reports that do no include this information will be ignored and closed**

E: I just realized, Linux desktops likely don't support invert color cursors, so the workaround is probably just for me to use a cursor scheme on my guest that doesn't use inverted cursors.

**Comment by gnif** [comment]
XOR cursors are supported and implemented, the cursor is drawn by the LG client and doesn't rely on the Linux desktop.

https://github.com/gnif/LookingGlass/blob/6d2c46443683c1dfe68601c80a35faf43020ff8c/client/renderers/EGL/cursor.c#L237-260

Are you using Wayland or Xorg?

**Comment by kode54** [comment]
I am using Xorg, and looking-glass-client appears to be using the EGL renderer. Do I need to send you a Windows 10 cross or I-beam cursor for examination? It appears to be 2px thick, unlike the one you show above. Maybe affected by my use of 150% magnification? It’s connected to a 2160p monitor.

**Comment by gnif** [comment]
Can you please add the following line to `cursor.c` on a new line before 217, I think you might be using a color masked cursor, which is rare today (this is the first instance I have seen one in the wild).

`DEBUG_INFO("LG_CURSOR_MASKED_COLOR");`

Then run the client and move the cursor around, when it becomes an I-Beam this message should appear in the output.

**Comment by kode54** [comment]
Yes, it is indeed a masked color cursor.

**Comment by gnif** [comment]
Ok, exactly what/how have you set up your windows system to produce this? I need to replicate it on my end to fix the issue. I need the desktop resolution, cursor set (if custom) and zoom level (since you said that's a factor).

**Comment by kode54** [comment]
I am running Windows 10 Pro for Workstations, 1903, with updates up to KB4515384. Default cursor set. Guest GPU is an AMD RX 480 with the current Windows Update drivers. A 2160p monitor is connected via hdmi and zoom is at the default 150% for that resolution, or so I’d guess since it thinks it’s a 27” monitor, because that’s what the EDID says. I am using the latest B1 host from the download site.

**Comment by gnif** [comment]
Excellent, thanks for the detailed information, when I get a chance I will attempt to replicate this and correct it.
