### ISSUE TITLE
Changes on latest master (2019-10-9) causing client to exit with segfault.

### ISSUE THREAD

**Issue by XenonPK** [gnif/LookingGlass#201]
Host CPU: AMD Ryzen 7 1700 Eight-Core Processor
Host GPU: Radeon RX 560 Series (POLARIS11, DRM 3.33.0, 5.3.4-1-default, LLVM 8.0.1)
Guest GPU: NVIDIA GTX 1070
Host Kernel version: 5.3.4-1-default
Host QEMU version: 4.1.0

Running the latest prebuilt host application + latest master build of client is causing a segfault.

client launch flags:
`looking-glass-client -f /dev/shm/looking-glass-<vm_name> -p 0 -c /tmp/looking-glass-<vm_name>.sock -F`

Strace attached: [looking-glass-strace.txt](https://github.com/gnif/LookingGlass/files/3720864/looking-glass-strace.txt)

Client Output: [looking-glass-output.txt](https://github.com/gnif/LookingGlass/files/3720869/looking-glass-output.txt)

Client Build Log: https://build.opensuse.org/package/live_build_log/home:xenonpk/looking-glass-client/openSUSE_Tumbleweed/x86_64

Everything was working properly with the version from commit: 6d2c46443683c1dfe68601c80a35faf43020ff8c

**Comment by gnif** [comment]
Your git version tag is incorrect and I have no idea what version you are building from. If you're using the latest version from master have you selected the "Bleeding Edge" host application?

Also please build with debug flags enabled and provide a gdb backtrace.

**Comment by XenonPK** [comment]
Disregard this report, I was using the wrong version of the host application, sorry for the inconvenience.
