### ISSUE TITLE
KVMFR version missmatch, expected 9 but got 8

### ISSUE THREAD

**Issue by stefanleh** [gnif/LookingGlass#202]
### Required information

Host CPU: Ryzen 7 1700
Host GPU: Renderer: Radeon RX 550 Series (POLARIS11, DRM 3.33.0, 5.3.4-300.agesa.fc31.x86_64, LLVM 9.0.0) Version : OpenGL ES 3.2 Mesa 19.2.0
Guest GPU: RTX 2080
Host Kernel version: 5.3.4-300.agesa.fc31.x86_64 (Custom Kernel with AGESA Patch)
Host QEMU version: QEMU emulator version 4.1.0 (qemu-4.1.0-2.fc31)

Guess something is outdated, right? But what?
"This is not a bug, ensure you have the right version of looking-glass-host.exe on the guest."

Best regards, Stefan

**Reports that do no include this information will be ignored and closed**

**Comment by gnif** [comment]
not a bug, exactly as the message states, get the latest build of the looking-glass host application. Since you're building from git master, you need to get the latest bleeding-edge version.
