### ISSUE TITLE
enhancement: Hostprocess should start even when VM is accessed via RDP

### ISSUE THREAD

**Issue by stefanleh** [gnif/LookingGlass#203]
### Required information

Host CPU: AMD Ryzen 1700
Host GPU: AMD RX 550
Guest GPU: Nvidia RTX 2080
Host Kernel version: 5.3.4-300.agesa.fc31.x86_64 (Custom Kernel with AGESA Patch)
Host QEMU version: QEMU emulator version 4.1.0 (qemu-4.1.0-2.fc31)

When i access my VM via RDP i cant start the Host process which is a little inconvenient as i dont own a proper KVM switch. Guess RDP confuses the host process.

**Reports that do no include this information will be ignored and closed**

**Comment by gnif** [comment]
not a bug, RDP uses a completely different video pipeline and is incompatible with DXGI desktop duplication. Please before opening issues like this ask on the support forum or on discord.
