### ISSUE TITLE
Hard CMake dependency on wayland?

### ISSUE THREAD

**Issue by lierdakil** [gnif/LookingGlass#204]
https://github.com/gnif/LookingGlass/blob/b9797529893a819307b0758fddae4d38d27802a3/client/renderers/EGL/CMakeLists.txt#L5-L9

`client/renderers/EGL/CMakeLists.txt` has a hard requirement for `wayland-egl` package, which is not available in non-Wayland distros. Frankly, I have no idea what it is, but building the client fails because of it. Now, the experiment shows it's not in fact a strict requirement, simply removing it from the CMakeLists works fine. But why is it declared as a hard requirement in the first place?

**Comment by gnif** [comment]
It is an oversight, Wayland in the past was required but after adding ifdefs for the related code it no-longer is.
