### ISSUE TITLE
Image stops updating in 2-3 seconds, old/no image on further reconnects

### ISSUE THREAD

**Issue by hg** [gnif/LookingGlass#205]
### Required information

Host CPU: i5-4460
Host GPU: Integrated HD4600
Guest GPU: Sapphire RX 580 4 GB (driver: Adrenalin 2019 Edition 19.10.2)
Host Kernel version: 5.3.6-200.fc30.x86_64
Host QEMU version: qemu-3.1.1-2.fc30

More info on hardware: https://git.io/JeEKD

Client log: https://git.io/JeEKB (all variations of configuration options resulted in similar output without any errors)
Host log: https://git.io/JeEKg
QEMU config: https://git.io/JeEKW
Packages used to build the client: https://git.io/JeEK1

Host OS: fully updated Fedora 30, X11/i3, no compositor, SELinux disabled.
Guest OS: Windows 10 LTSC
Guest resolution: 1920x1080

### Description

When I first connect to a Looking Glass host (on a freshly rebooted VM), it works fine for a couple of seconds, and then the image stops updating. Further reconnects result either in the same frozen image, or in a purple splash screen.

Furthermore, if I type `ScrollLock+F`, the client goes black for a few seconds and then the window disappears (the process itself continues running).

The guest system continues to work normally. I can reconnect the monitor to the GPU and there seem to be no problems with the guest (this includes the LG host process -- it is still running and there are no errors in its log). Restarting the host process doesn't help.

What I tried, in many possible combinations:

* running the latest stable version (`163a2e5d`) and two of the latest builds from CI (`0e7e918e`, `1d7a2ccf`), always using the same version for both host and client.
* varying shmem size from 32 to 256 MiB;
* `chmod`ing it to 777 before starting the VM;
* switching renderers between `egl` and `opengl`, trying various configuration options for both;
* using a compositor (`compton`).

No dice.

Is there any other information I can provide?

This is great stuff, thanks so much for your work on this! I am hoping to get it to work on my capricious system.

**Comment by gnif** [comment]
Can you please verify that windows capture works using another application such as OBS? Everything looks fine to me, it might be a driver/vm issue.

**Comment by hg** [comment]
Oops, it must really have been a driver problem. Looking Glass is working fine for me now after countless reboots and reinstalling the driver half a dozen times.

This should have gone to a support forum. I apologize for the inconvenience!
