### ISSUE TITLE
2px vertical line at the right side of screen on latest client

### ISSUE THREAD

**Issue by thejavascriptman** [gnif/LookingGlass#207]
### Required information

Host CPU: Ryzen 2700
Host GPU: RX 590
Guest GPU: RTX 2070
Host Kernel version: 5.3.8
Host QEMU version: 4.1.0

Issue discovered after building and running the latest client version (at fe7d611fb924f5a6577a6552f47eac2db322cda3). Windows host application did not crash.

The problem happens immediately after running Looking Glass client, although Chrome is shown in the screenshots, the issue happens even if there is no other application running.

See vertical line at the right side
![2019-11-13_22-01](https://user-images.githubusercontent.com/46071365/68766461-3d1b9180-0662-11ea-8a85-caab0bd7d885.png)

![2019-11-13_22-11](https://user-images.githubusercontent.com/46071365/68766625-8f5cb280-0662-11ea-80c0-c0f98989c327.png)

**Comment by gnif** [comment]
Is this the looking glass client's view of the VM?, And if so, is your windows desktop background also purple? and if you change it, does the color change of the 2px edge?

**Comment by thejavascriptman** [comment]
Yes, screenshots were taken from the host while Looking Glass client was running at fullscreen.

The desktop background is purple, the line color changes according to the wallpaper color. The problem also happens even with picture backgrounds.

**Comment by gnif** [comment]
What resolution are you running for the guest?

**Comment by thejavascriptman** [comment]
Both host and guest are running at 3840x2160, the issue is not happening when running release B1

**Comment by thejavascriptman** [comment]
No longer happening with latest version, thanks
