### ISSUE TITLE
Ignore ALT+F4

### ISSUE THREAD

**Issue by intdel** [gnif/LookingGlass#21]
Qemu has a "no-quit" parameter. If passed, clicking on X or ALT+F4 are ignored.

It would be nice if the client could ignore ALT+F4 (or pass it to the guest) so that if I quit games, the game gets closed and not the looking client!

**Comment by gnif** [comment]
I will look into this one at some point, for now you can work around this by unbinding the left or right alt as a mod key in your X session.

**Comment by mcd1992** [comment]
Passing through alt+tab would be useful as well.

**Comment by gnif** [comment]
While I believe we can deal with ALT+F4 simply by ignoring the SDL_QUIT message, I don't think that we can do anything about ALT+TAB or any other hot key combination bound by the user's window manager.

**Comment by intdel** [comment]
Is it not possible to grab input like Qemu or even Spice (remote-viewer) does?

**Comment by gnif** [comment]
Not that I am aware of at this time, I will keep an eye out for this though as it would be a nice enhancement. For now I will patch in a fix for the ALT+F4 issue as described and put this on my enhancement list.
