### ISSUE TITLE
Looking Glass Host crashes. Black Screens

### ISSUE THREAD

**Issue by D1Ck3n** [gnif/LookingGlass#215]
### Required information

Host CPU: Ryzen 5 2600X
Host GPU:Geforce GTX 1060
Guest GPU: AMD RX 570 4G
Host Kernel version: 5.3
Host QEMU version: 4.1.0-5

Hi,

I have the problem that Looking Glass Host crashes regularly and all my 3 screens turn black. I still hear that the VM is running, but I can't see anything anymore. I have to switch the input of my monitor to the guest GPU to restart the VM Looking Glass host.

Greetings
Merlin

**Comment by gnif** [comment]
Without logs there is nothing I can do.

**Comment by D1Ck3n** [comment]
oh sorry, i'll post it this evening

**Comment by D1Ck3n** [comment]
Stupid question: how do i see the log on windows client?

**Comment by gnif** [comment]
Unfortunately the log is now showing anything obvious. I have also seen the host application crash in recent revisions but I am yet to find the trigger, it's rare for me. If you could run the host application under a debugger (gdb) and provide a full backtrace (`thread apply all bt`) when it crashes it would be extremely helpful.

**Comment by D1Ck3n** [comment]
mhh okay, i do everyting to help!

but i'm not so into coding. could you tell me how to debug the host application on windows 10?

i follow this [wiki](https://rpg.hamsterrepublic.com/ohrrpgce/GDB_on_Windows) but i dont see any debug logs

**Comment by gnif** [comment]
That's the correct method, it doesn't generate any logs though, you need to wait for it to crash and when it does, in the debugger type:

`thread apply all bt`

Copy and paste the results here :)

**Comment by D1Ck3n** [comment]
i debugged it now with visual studio (was easier for me). I hope that's enough.

`"looking-glass-host.exe" (Win32): "C: \ Users \ Merlin \ Documents \ Looking_Glass \ looking-glass-host.exe" loaded. The module was created without symbols.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ntdll.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ kernel32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ KernelBase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ apphelp.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ msvcrt.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ dxgi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ setupapi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ win32u.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ cfgmgr32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ gdi32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ucrtbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ gdi32full.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ rpcrt4.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ msvcp_win.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ user32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ bcrypt.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ shell32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ SHCore.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DXCore.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ combase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ combase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ combase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ bcryptprimitives.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ windows.storage.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \echsost.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ advapi32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ profapi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ powrprof.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ umpdc.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ shlwapi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ kernel.appcore.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ cryptsp.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ d3d11.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ imm32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ uxtheme.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ devobj.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ wintrust.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ msasn1.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ crypt32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ResourcePolicyClient.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ResourcePolicyClient.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ aticfx64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ version.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmm.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ dwmapi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ dwmapi.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atiuxp64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atidxx64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ole32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ amdihk64.dll" loaded. The module was created without symbols.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ D3DSCache.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ twinapi.appcore.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ userenv.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ rmclient.dll" loaded.
Thread 0x1f70 ended with code 0 (0x0).
Thread 0x1394 ended with code 0 (0x0).
Thread 0x2c6c ended with code 0 (0x0).
Thread 0x1834 ended with code 0 (0x0).
Thread 0x9c8 ended with code 0 (0x0).
Thread 0x14c4 ended with code 0 (0x0).
Thread 0x1fcc ended with code 0 (0x0).
Thread 0x9cc ended with code 0 (0x0).
Thread 0x2cb4 ended with code 0 (0x0).
Thread 0x23c8 ended with code 0 (0x0).
Thread 0xd60 ended with code 0 (0x0).
Thread 0x31c8 ended with code 0 (0x0).
Thread 0x4bc ended with code 0 (0x0).
Thread 0x2404 ended with code 0 (0x0).
Thread 0x12c8 ended with code 0 (0x0).
Thread 0x2054 ended with code 0 (0x0).
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ amdihk64.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ole32.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atidxx64.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atiuxp64.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ version.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmm.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ aticfx64.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ aticfx64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ version.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmm.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ winmmbase.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ dwmapi.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ dwmapi.dll" has been unloaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atiuxp64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ DriverStore \ FileRepository \ u0348309.inf_amd64_23535cba806b80cc \ B348293 \ atidxx64.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ ole32.dll" loaded.
"looking-glass-host.exe" (Win32): "C: \ Windows \ System32 \ amdihk64.dll" loaded. The module was created without symbols.
Thread 0xfa8 ended with code 0 (0x0).
Thread 0x336c ended with code 0 (0x0).
Thread 0x14e4 ended with code 0 (0x0).
Thread 0x54c ended with code 0 (0x0).
Thread 0xec ended with code 0 (0x0).
Thread 0xb58 ended with code 0 (0x0).
Thread 0x1470 ended with code 0 (0x0).
Thread 0xebc ended with code 0 (0x0).
Thread 0x2c58 ended with code 0 (0x0).
Thread 0x37f4 ended with code 0 (0x0).
Thread 0x31d4 ended with code 0 (0x0).
The program "[12416] looking-glass-host.exe" was ended with code 0 (0x0).`

**Comment by gnif** [comment]
I am sorry but as this is not a Visual Studio project the debugged output from VS is useless. You need to debug the program with GDB as stated originally.

**Comment by D1Ck3n** [comment]
so I tried to start looking glass host with debugger, but somehow it doesn't start:

(gdb) run looking-glass-host.exe
Starting program:  looking-glass-host.exe
No executable specified, use `target exec'.
(gdb)

I have also tried it as it is described in the Wiki:

C:\Windows\system32>cd C:\Users\Merlin\Documents\Looking_Glass

C:\Users\Merlin\Documents\Looking_Glass>c:\mingw\bin\gdb.exe looking-glass-host.exe
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
"C:\Users\Merlin\Documents\Looking_Glass/looking-glass-host.exe": not in executable format: File format not recognized
(gdb)

**Comment by gnif** [comment]
the debugger should drop to a command line if the application crashes, from the looks of this the application isn't crashing but properly shutting down.

Can you please detail everything about your setup such as Windows Version, Video Card, The game, Resolution and refresh rate?

**Comment by D1Ck3n** [comment]
oh okay, give you all the information you need :)

Windows Version: Windows 10 1903 (Build 18362.535)
Video Card: Radeon RX 570 4GB
Video Driver Version: 19.11.1
Game i've tested: Football Manager 2020 (Steam),  The Outer Worlds (Microsoft Game Pass), Age of Empires (Game Pass)
Resolution 1920 x 1080 60Hz

**Comment by D1Ck3n** [comment]
Happy New Year! I hope you had a relaxing holiday!

I tried something else, but unfortunately it did not get better.

i installed the latest AMD driver for the graphics card (19.12.3) and tried to use only one screen, but unfortunately the Host Exe still stops after 30 minutes. Unfortunately now a micro-stuttering can be detected. Without Looking Glass I don't have the stuttering.

**Comment by gnif** [comment]
This may have been fixed in the latest master, can you please update and try it out.

**Comment by D1Ck3n** [comment]
Hi, I think I found the solution to my problem! It was so obvious I missed it: The power management was set to turn off the monitors if there was no input for 30 minutes. I had previously only turned off the screensaver without thinking to look at the power setting.

I also thaught that the Looking Glass Client would keep the system awake.

so much trouble to something so simple :D

**Comment by gnif** [comment]
> I also thaught that the Looking Glass Client would keep the system awake.

No, but that isn't a bad idea, I think there is an API to stop windows from going to sleep... hrmm.
