### ISSUE TITLE
jitter when re-connecting client

### ISSUE THREAD

**Issue by Francesco149** [gnif/LookingGlass#216]
Host CPU: i7-4790k
Host GPU: rx570
Guest GPU: rx570
Host Kernel version: 5.4.2 with tkg patches
Host QEMU version: 4.1.1

when I start the client for the first time on the host everything works fine. if I close the client and re-open it the video is noticeably jittery and the problem persists until i restart the looking glass host in the vm. this needs to be done every time i reconnect.

sometimes other weird issues pop up on reconnects such as mouse cursors not updating unless i click

I am using the latest bleeding edge release from https://looking-glass.hostfission.com/downloads

I guess this might end up fixed with the new rewritten host but I thought I'd let you know

**Comment by Francesco149** [comment]
log file: 

https://gist.github.com/1c27a23e389dd5cbd752cb09176059ed

**Comment by gnif** [comment]
Can you please ensure your guest GPU is set to performance mode and report back. The AMD drivers are known not to properly performance scale when capture is in use.

**Comment by Francesco149** [comment]
hm, I can't seem to reproduce this anymore, interesting. might actually be the frequency scaling acting up randomly. the thing is, it was jittering even simple desktop animations like opening the start menu in an idle situation.

well, I'll reopen if i manage to capture it on video
