### ISSUE TITLE
Windows 8.1 DXGI Support

### ISSUE THREAD

**Issue by foxlet** [gnif/LookingGlass#218]
### Required information

Host CPU: Ryzen 5 2600
Host GPU: R9 270X
Guest GPU: GeForce 9800 GTX+
Host Kernel version: 5.3.16_1
Host QEMU version: 4.1.1

`looking-glass-host.exe` exits when ran under Windows 8.1, with the following written to the log. There is no client output or activity. The same configuration works under Windows 10 (November 2019 Update).
```
[I]                app.c:381  | app_main                       | Trying           : DXGI
[E]               dxgi.c:313  | dxgi_init                      | Failed to create D3D11 device: 0x80070057 (The parameter is incorrect.)
[E]                app.c:398  | app_main                       | Failed to find a supported capture interface
```

**Comment by gnif** [comment]
Thanks, if I get a chance I will spin up a 8.1 VM and debug this later if someone else doesn't beat me to it.

**Comment by foxlet** [comment]
Culprit is in `dxgi.c`, `E_INVALIDARG` is returned when runtimes not supported by the OS are passed. https://github.com/gnif/LookingGlass/blob/45ee79014dc8e12ba71c660caf26e033b1113ee6/c-host/platform/Windows/capture/DXGI/src/dxgi.c#L312-L313
