### ISSUE TITLE
Switching users causes crash

### ISSUE THREAD

**Issue by Verequies** [gnif/LookingGlass#22]
Host CPU: i7-4800MQ
Host GPU: Intel HD Graphics 4600
Guest GPU: Quadro K1100M
Host Kernel version: 4.14.6-xanmod9
Host QEMU version: QEMU 2.11.0

When trying to switch users, and then returning to the user from which the Looking Glass host was started, Looking Glass will crash with:

> [I]     CaptureFactory.h:83   | CaptureFactory::DetectDevice   | Trying NvFBC
[E]            NvFBC.cpp:130  | Capture::NvFBC::Initialize     | Failed to create an instance of NvFBC
[I]     CaptureFactory.h:83   | CaptureFactory::DetectDevice   | Trying DXGI
[I]     CaptureFactory.h:86   | CaptureFactory::DetectDevice   | Using DXGI
[I]          Service.cpp:235  | Service::Process               | ReInitialize Requested
[E]             DXGI.cpp:100  | Capture::DXGI::Initialize      | Failed to locate a valid output device
[E]          Service.cpp:238  | Service::Process               | ReInitialize Failed

Tried to provide the dump file however it was not created?

**Comment by gnif** [comment]
Thanks, dump files are only produced on an actual crash, not a clean shutdown, which is seen here.

**Comment by Verequies** [comment]
Ah I see, good to know.
