### ISSUE TITLE
Starting looking-glass-host from Task Scheduler doesn't work anymore

### ISSUE THREAD

**Issue by llitz** [gnif/LookingGlass#221]
Win10

I am trying to identify which update broke the looking-glass-host.exe from being started from the Task Scheduler.

It is not working for me with any of the currently available development binaries but B1 still works fine.

The powershell script calling the program is stuck and it never finishes.

Is there a way to access the old looking-glass-host.exe binaries? I don't really have a cross-compile/windows environment ready to compile.

For reference this is how I am doing it (quite sure I copied from someone else).
I have two simple Powershell scripts, one of them is what task scheduler calls:

restartlgh.ps1
```powershell
$lgh = "looking-glass-host"

Foreach-Object -InputObject($lgh) {
	$myproc = Get-Process $_ -ErrorAction SilentlyContinue
	if ($myproc) {
		$myproc.CloseMainWindow()
		$myproc | Stop-Process -Force
		if (!$myproc.HasExited) {
			Write-Output "fail"
		}
	} else {
		Write-Output "$_ is not running"
	}
	Write-Output "Starting $_"
	Start-Process "$HOME\Downloads\$lgh\$lgh.exe"
}
```

The other one calls the task scheduler task with privileged perms:
ts-lgh.ps1
```powershell
Start-ScheduledTask -TaskName "Restart Looking Glass" -TaskPath \Personal
```

On task scheduler, this is configured to run with the highest privileges at logon and on event "Power-Tourbleshooter:1".

I also have a shortcut at the desktop:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command C:\Users\mb\Documents\powershell\ts-lgh.ps1
```
This can be called with ctrl+shift+f7

**Comment by gnif** [comment]
Not a bug, please ask this on the Level1Tech Looking Glass forum category.
