### ISSUE TITLE
Window resize without black bars?

### ISSUE THREAD

**Issue by DocMAX** [gnif/LookingGlass#225]
Maybe you can enhance the client a bit and keep the window resize "locked" with the aspect ratio of the host  to avoid the black bars?

**Comment by gnif** [comment]
Isn't this what you're looking for?
`./looking-glass-client win:allowResize=no win:keepAspect=yes`

**Comment by DocMAX** [comment]
No, the window should be resizable but the window should keep aspect ratio. compared to this at the end of the clip: https://www.youtube.com/watch?v=KztbLYd55KE
