### ISSUE TITLE
LG Window is 'raw' under Gnome Wayland, but normal under Gnome X11

### ISSUE THREAD

**Issue by TitusLabienus** [gnif/LookingGlass#227]
I use LookingGlass together with Intel gvt-g. When I start LookingGlass under Gnome with Wayland, the window is shown 'raw', i.e. without title bar etc. Thus, I cannot move/resize/maximize the window. On Gnome X11 the window is shown normally.

### Required information

Host CPU: Coffee Lake (i7-8750H)
Host GPU: UHD Graphics 630
Guest GPU: UHD Graphics 630
Host Kernel version: 5.4.7.arch1-1
Host QEMU version: 4.2.0-1

**Comment by gnif** [comment]
Wayland is not officially supported at this time.
