### ISSUE TITLE
[client] Shuts down when another spice client captures

### ISSUE THREAD

**Issue by JJRcop** [gnif/LookingGlass#228]
### Required information

Host CPU: Ryzen 5 2600
Host GPU: Radeon RX580
Guest GPU: GeForce GTX 970
Host Kernel version: Linux debian 5.3.0-3-amd64 #1 SMP Debian 5.3.15-1 (2019-12-07) x86_64 GNU/Linux
Host QEMU version: QEMU emulator version 4.2.0 (Debian 1:4.2-1)

LookingGlass version: B1-56-gb8203bec53+1 (8caa220)

When another spice client captures spice while the LG client is still trying to use it, the client will shut down with these messages:
```
[E]              spice.c:1306 | spice_read_nl                  | remote end closd connection after 0 byte(s)
[E]              spice.c:320  | spice_on_common_read           | read failure
[E]              spice.c:642  | spice_on_inputs_channel_read   | read failure
[E]              spice.c:290  | spice_process                  | failed to perform read on inputs channel
[E]               main.c:471  | spiceThread                    | failed to process spice messages
```

This is currently intended behavior:
https://github.com/gnif/LookingGlass/blob/8caa220ad5ee79474e95712f93dc83bbfd4066a5/client/src/main.c#L463-L478

However, the client should probably still provide video and even try to reclaim the spice connection when the window is re-focused, this would make it play nice with say, virt-manager, which reattempts the spice connection if the libvirt domain is edited at runtime.

**Comment by gnif** [comment]
This is a libvirt issue, please file a bug with them to have them provide a way to prevent libvirt from assuming you want spice control.

**Comment by JJRcop** [comment]
You're correct, this is not a bug with Looking Glass, my apologies. It does appear to instead be a bug with virt-manager, rather than libvirt.
