### ISSUE TITLE
Better support for wayland

### ISSUE THREAD

**Issue by epsilontheta** [gnif/LookingGlass#229]
### Required information
I'm running looking glass under wayland and the mouse movement is limited by the resolution of the monitor in 3D applications.
This also happens if I enable capture mode (scroll lock).
The screen resolution of the guest matches the resolution of the host and I ran looking glass with `-F`.
If I understood correctly from other issues that is an issue with wayland and it also works fine under X11.
Since e.g. Fedora uses wayland as default and it is now in a pretty usable state I think it would be nice to have better support for it.

Used version for both client and server: `B1`

Host CPU: AMD Ryzen 7 3700X
Host GPU: Radeon RX 550
Guest GPU: NVIDIA GeForce 1060
Host Kernel version: 5.4.7
Host QEMU version: 4.1.1

I was running a DX11 application within windows guest and tried to do a 360° rotation by moving the mouse.

**Comment by gnif** [comment]
> This also happens if I enable capture mode (scroll lock).

How are you handing input to your VM? Evdev, USB Passthrough or SPICE?
If SPICE then make sure your VM does not have a virtual tablet device as this will cause this problem.

As we are using SDL2 for input events even under Wayland, if there is a problem here it will be a SDL2 bug.

**Comment by epsilontheta** [comment]
I use SPICE. OK thanks for the pointer in the right direction. Just FYI: when I set `SDL_VIDEODRIVER=x11` as a environment variable it works fine under wayland.
