### ISSUE TITLE
LGMP error on cmake client

### ISSUE THREAD

**Issue by JeromeL63** [gnif/LookingGlass#235]
Hello,
I'm unable to build current git version, cmake says :
```
CMake Error at CMakeLists.txt:92 (add_subdirectory):
  add_subdirectory given source
  "/home/jerome/Applications/LookingGlass_sources/LGMP/lgmp" which is not an
  existing directory.
```

It's on a debian testing/unstable daily updated.
I have to build this version because LG said
` E]               main.c:1279 | run                            | KVMFR version missmatch, expected 8 but got 9`
and after install latest host .exe 
`[E]               main.c:1273 | run                            | Invalid header magic, is the host running?`

So I need to recompile the latest client

**Comment by JeromeL63** [comment]
Ok I've download lgmp from :
[https://github.com/gnif/LGMP/tree/d85bba9c4895e99f7c0d06d597325a26e19dbee8](url)
and put it on my LGMP folder, it works know

**Comment by gnif** [comment]
Correct, it's a sub-module, you have to run `git submodule update --init` after checkout, or `git clone --recurse-submodules` when you clone the project.

This is not an error but a failure to understand git.

**Comment by Skeen** [comment]
I get the same issue, but from the release zip. It is not an option there to git clone, as it would defeat the purpose of having a release, the release should be freestanding and self contained, no?

**Comment by gnif** [comment]
Github releases do no include submodules. Please download the source from the LG website unless you intend to do development as this is freestanding and self-contained.

https://looking-glass.io/downloads
