### ISSUE TITLE
looking-glass-host B1 exits immediately

### ISSUE THREAD

**Issue by MartyBrn** [gnif/LookingGlass#236]
### Required information
Host CPU: TR 3970X
Host GPU: RTX 2080
Guest GPU: GTX 1070
Host Kernel version: 5.2.0
Host QEMU version: 4.2

When starting looking-glass-host.exe, it exits immediately. From the host perspective, this means that running the client just results in a window with the Lookingglass logo on a purple background. I included the output from gdb below. This is an ubuntu 19.10 host on a 3970X. The guest is Windows 10 Enterprise, with pasthrough of USB ports and GTX1070.

> Reading symbols from looking-glass-host.exe...(no debugging symbols found)...done.
> (gdb) run
> Starting program: C:\Users\XXXX\looking-glass-host-163a2e5d\looking-glass-host.exe
> [New Thread 4896.0x2684]
> [New Thread 4896.0x22c]
> [New Thread 4896.0xb8c]
> [New Thread 4896.0x2118]
> [New Thread 4896.0x1854]
> [Thread 4896.0x1854 exited with code 0]
> [Thread 4896.0xb8c exited with code 4294967295]
> [Thread 4896.0x2118 exited with code 4294967295]
> [Thread 4896.0x22c exited with code 4294967295]
> [Inferior 1 (process 4896) exited with code 037777777777]

**Comment by gnif** [comment]
What does the host log say? `%TEMP%\looking-glass-host.exe`

**Comment by MartyBrn** [comment]
I checked the log. It just repeats, about 30 times the following:

> [E] platform.c:306 | app_init | Unable to enumerate the device, it is attached?: 0x00000103 (no more data available.)

**Comment by gnif** [comment]
You have not added the IVSHMEM device to the VM or installed the driver. Please ask for help on the L1 tech forums or in Discord as this is not a LG bug.
