### ISSUE TITLE
Can't run looking glass client

### ISSUE THREAD

**Issue by rmb938** [gnif/LookingGlass#237]
### Required information

Host CPU:  AMD 2700X
Host GPU: AMD Radeon RX 570
Guest GPU: Nvidia 1080
Host Kernel version: 5.4.18-200.fc31.x86_64
Host QEMU version: qemu-4.1.1-1.fc31

I am trying to run the looking glass client on a new fedora 31 installation. The Windows 10 guest starts up fine and seems to run the host application fine.

When running the client I get the following error:

```
./looking-glass-client 
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-6-gb979752989+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib64/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib64/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  112
  Current serial number in output stream:  111
```

Looking in `/usr/lib64/dri` I do see radeon drivers so I'm not too sure why it's complaining.

**Comment by gnif** [comment]
Not a LG issue, but AMD drivers/mesa issue. Please seek help elsewhere, perhaps the L1 Tech forums.
