### ISSUE TITLE
Using OpenGL renderer results in client displaying a black screen

### ISSUE THREAD

**Issue by logankonopatzke** [gnif/LookingGlass#238]
### Required information

Host CPU: i7 9700k
Host GPU: 9700k Integrated Graphics
Guest GPU: GTX 1080
Host Kernel version: 5.3.0-28-generic
Host QEMU version: QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.22)

Please describe what were you doing when the problem occurred. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do not include this information will be ignored and closed**

Running the looking glass client with the following `sudo ./looking-glass-client -s -F -g OpenGL` results in the client displaying a completely black screen (only showing the mouse).  
![Screenshot from 2020-02-17 13-53-27](https://user-images.githubusercontent.com/60406681/74682992-359de400-518d-11ea-9cb8-b767eb93f1c2.png)

Running the same command without the OpenGL flag works normally as shown below. 
![Screenshot from 2020-02-17 13-57-12](https://user-images.githubusercontent.com/60406681/74683085-70a01780-518d-11ea-9299-2ce324a19981.png)

The console outputs the following errors when running the client:
```
12670578108 [I]               main.c:178  | renderThread                   | Timer drift detected, 401359088 is > 4166666
12671411140 [I]               main.c:178  | renderThread                   | Timer drift detected, 2416334005 is > 4166666
12672245808 [I]               main.c:178  | renderThread                   | Timer drift detected, 2417975016 is > 4166666
12673078556 [I]               main.c:178  | renderThread                   | Timer drift detected, 2416062973 is > 4166666
12673911403 [I]               main.c:178  | renderThread                   | Timer drift detected, 416157271 is > 4166666
12674744843 [I]               main.c:178  | renderThread                   | Timer drift detected, 416755605 is > 4166666
12675578119 [I]               main.c:178  | renderThread                   | Timer drift detected, 416586567 is > 4166666
```

This was tested using host and client commit 582ed6b5. The B1 release works as expected and does *not* display a black screen, so I assume something changed to cause this.

(Full console output if needed):
```
12669655161 [I]               main.c:1564 | main                           | Looking Glass (B1-157-ge2adbaa5c1+1)
12669655204 [I]               main.c:1565 | main                           | Locking Method: Atomic
12669715722 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
12669715744 [I]               main.c:1248 | lg_run                         | Trying forced renderer
12669723892 [I]               main.c:1060 | try_renderer                   | Using Renderer: OpenGL
12669759431 [I]               main.c:1394 | lg_run                         | Using Clipboard: X11
12669764154 [I]             opengl.c:505  | opengl_render_startup          | Vendor  : Intel Open Source Technology Center
12669764166 [I]             opengl.c:506  | opengl_render_startup          | Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
12669764171 [I]             opengl.c:507  | opengl_render_startup          | Version : 3.0 Mesa 19.2.8
12669841399 [I]               main.c:1450 | lg_run                         | Host ready, starting session
12670578108 [I]               main.c:178  | renderThread                   | Timer drift detected, 401359088 is > 4166666
12671411140 [I]               main.c:178  | renderThread                   | Timer drift detected, 2416334005 is > 4166666
12672245808 [I]               main.c:178  | renderThread                   | Timer drift detected, 2417975016 is > 4166666
12673078556 [I]               main.c:178  | renderThread                   | Timer drift detected, 2416062973 is > 4166666
12673911403 [I]               main.c:178  | renderThread                   | Timer drift detected, 416157271 is > 4166666
12674744843 [I]               main.c:178  | renderThread                   | Timer drift detected, 416755605 is > 4166666
12675578119 [I]               main.c:178  | renderThread                   | Timer drift detected, 416586567 is > 4166666
12675964372 [I]               main.c:810  | eventFilter                    | Quit event received, exiting...
```

**Comment by gnif** [comment]
Firstly why do you want to use the Legacy OpenGL renderer?
Secondly why are you running LG as root? do not do this!

**Comment by logankonopatzke** [comment]
No reason. I was simply testing all of the features of looking glass to see what it was capable of and if anything wasn't working properly. I didn't realize the OpenGL renderer was legacy, my bad.

Yeah, I realize now that's a bad idea. I originally did it because I had an issue with insufficient permissions to access the shared memory, but I resolved the problem and just used the same command template. Thank you for pointing that out though.
