### ISSUE TITLE
errors starting looking glass (eglError: 0x3005) or (Couldn't find matching GLX visual)

### ISSUE THREAD

**Issue by spirritus** [gnif/LookingGlass#240]
The looking-glass client cannot start using VM to VM.

Host GPU1: ASPEED AST2500 (128MB)
Host GPU2: RX560 (4GB)

GPU2 is passed to the windows vm.
The Linux VM uses QLX. glxgears is working.

user@accessor:~$ looking-glass-client -f /dev/uio0 -L 32 -c 192.168.43.16 
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-6-gb979752989+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[I]              spice.c:197  | spice_connect                  | Remote: 192.168.43.16:5900
libEGL warning: DRI2: failed to authenticate
[E]                egl.c:428  | egl_render_startup             | Failed to create EGL surface (eglError: 0x3005)
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...

user@accessor:~$ looking-glass-client -f /dev/uio0 -L 32 -c 192.168.43.16 -g OpenGL
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-6-gb979752989+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]               main.c:1053 | run                            | Trying forced renderer
[I]               main.c:902  | try_renderer                   | Using Renderer: OpenGL
[E]               main.c:1100 | run                            | Could not create an SDL window: Couldn't find matching GLX visual

**Comment by gnif** [comment]
> [I] main.c:902 | try_renderer | Using Renderer: OpenGL

Why are you using OpenGL, it's legacy and has been replaced by EGL (OpenGL ES)

> Could not create an SDL window: Couldn't find matching GLX visual

Not a LG issue but an xorg/x11 issue. Failure at this point means that a simple empty 32-bit X window couldn't be created. Have you installed your video drivers?

**Comment by spirritus** [comment]
I tried OpenGL after EGL failed. Above is th output of both commands., first with EGL, that gives the error 0x3005. Second with OpenGL which gives the GLX visual error.

I'll try setting other permissons for the DRI2 when I am back at the computer on monday, however, glxgears is working with the current configuration.

If the driver would be xserver-xorg-video-qxl, then yes.

**Comment by spirritus** [comment]
Ok, did some further testing, es2gears runs.
When starting looking glass there is a window shown for a split second before it vanishes.

```
user@accessor:~$ es2gears
libEGL warning: DRI2: failed to authenticate
EGL_VERSION = 1.4
vertex shader info: 
fragment shader info: 
info: 
4196 frames in 5.0 seconds = 839.200 FPS
```


```
user@accessor:~$ es2_info 
libEGL warning: DRI2: failed to authenticate
EGL_VERSION: 1.4
EGL_VENDOR: Mesa Project
EGL_EXTENSIONS:
    EGL_KHR_cl_event2, EGL_KHR_config_attribs, EGL_KHR_context_flush_control, 
    EGL_KHR_create_context, EGL_KHR_create_context_no_error, 
    EGL_KHR_fence_sync, EGL_KHR_get_all_proc_addresses, EGL_KHR_gl_colorspace, 
    EGL_KHR_gl_renderbuffer_image, EGL_KHR_gl_texture_2D_image, 
    EGL_KHR_gl_texture_3D_image, EGL_KHR_gl_texture_cubemap_image, 
    EGL_KHR_image_base, EGL_KHR_no_config_context, EGL_KHR_reusable_sync, 
    EGL_KHR_surfaceless_context, EGL_EXT_pixel_format_float, 
    EGL_KHR_wait_sync, EGL_MESA_configless_context, EGL_MESA_drm_image
EGL_CLIENT_APIS: OpenGL OpenGL_ES 
GL_VERSION: OpenGL ES 3.0 Mesa 18.3.6
GL_RENDERER: llvmpipe (LLVM 7.0, 128 bits)
GL_EXTENSIONS:
    GL_EXT_blend_minmax, GL_EXT_multi_draw_arrays, 
    GL_EXT_texture_compression_s3tc, GL_EXT_occlusion_query_boolean, 
    GL_EXT_texture_compression_dxt1, GL_EXT_texture_format_BGRA8888, 
    GL_OES_compressed_ETC1_RGB8_texture, GL_OES_depth24, 
    GL_OES_element_index_uint, GL_OES_fbo_render_mipmap, GL_OES_mapbuffer, 
    GL_OES_rgb8_rgba8, GL_OES_standard_derivatives, GL_OES_stencil8, 
    GL_OES_texture_3D, GL_OES_texture_float, GL_OES_texture_float_linear, 
    GL_OES_texture_half_float, GL_OES_texture_half_float_linear, 
    GL_OES_texture_npot, GL_OES_vertex_half_float, GL_EXT_texture_sRGB_decode, 
    GL_OES_EGL_image, GL_OES_depth_texture, GL_OES_packed_depth_stencil, 
    GL_EXT_texture_type_2_10_10_10_REV, GL_OES_get_program_binary, 
    GL_APPLE_texture_max_level, GL_EXT_discard_framebuffer, 
    GL_EXT_read_format_bgra, GL_EXT_frag_depth, GL_NV_fbo_color_attachments, 
    GL_OES_EGL_image_external, GL_OES_EGL_sync, GL_OES_vertex_array_object, 
    GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
    GL_EXT_texture_rg, GL_EXT_unpack_subimage, GL_NV_draw_buffers, 
    GL_NV_read_buffer, GL_NV_read_depth, GL_NV_read_depth_stencil, 
    GL_NV_read_stencil, GL_EXT_draw_buffers, GL_EXT_map_buffer_range, 
    GL_KHR_debug, GL_KHR_texture_compression_astc_ldr, 
    GL_OES_depth_texture_cube_map, GL_OES_required_internalformat, 
    GL_OES_surfaceless_context, GL_EXT_color_buffer_float, 
    GL_EXT_separate_shader_objects, GL_EXT_shader_integer_mix, 
    GL_EXT_base_instance, GL_EXT_compressed_ETC1_RGB8_sub_texture, 
    GL_EXT_copy_image, GL_EXT_draw_buffers_indexed, 
    GL_EXT_draw_elements_base_vertex, GL_EXT_polygon_offset_clamp, 
    GL_EXT_texture_border_clamp, GL_KHR_context_flush_control, 
    GL_OES_copy_image, GL_OES_draw_buffers_indexed, 
    GL_OES_draw_elements_base_vertex, GL_OES_texture_border_clamp, 
    GL_OES_texture_stencil8, GL_EXT_blend_func_extended, GL_KHR_no_error, 
    GL_KHR_texture_compression_astc_sliced_3d, GL_OES_EGL_image_external_essl3, 
    GL_EXT_clip_cull_distance, GL_EXT_disjoint_timer_query, 
    GL_MESA_shader_integer_functions
```

**Comment by gnif** [comment]
`xserver-xorg-video-qxl` does not support the modes required for the RGBA texture, you need to use a real GPU. This is not a LG fault. Please stop posting to this issue, If you need further help please as instructed open a thread on the L1 tech forums for this.

**Comment by spirritus** [comment]
Awesome, thx for the info!
