### ISSUE TITLE
Games lagging through looking glass

### ISSUE THREAD

**Issue by D1Ck3n** [gnif/LookingGlass#242]
Hi,

Looking-Glass is going quite well for me so far, but I noticed that in games I have a lag every few seconds. When I run the VM directly over the Guest GPU everything is smooth.

My system:
Host CPU: Ryzen 5 2600X
Host GPU:Geforce GTX 1060
Guest GPU: AMD RX 570 4G
Host Kernel version: 5.4.18-1-MANJARO
Host QEMU version: 4.2.0-1

best regards
D1Ck3n

**Comment by gnif** [comment]
Issues are for bug reports only, this is a usability issue/problem, as instructed please ask in the L1 forums.
