### ISSUE TITLE
OBS Plugin - Distorted

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#244]
### Required information

Host CPU: AMD Ryzen 2600
Host GPU: AMD WX 2100 2GB
Guest GPU: NVIDIA GTX 1050 2GB
Host Kernel version: 5.3.0-40-generic
Host QEMU version: 4.2.0

I compiled the OBS plugin, copied it over, the plugin is recognised within OBS but what renders is actually just a distorted image.
The looking glass client is running as expected, no issues.
https://ibb.co/54kRsGV

**Comment by gnif** [comment]
did you upgrade the client and the host?

**Comment by 8BallBomBom** [comment]
Yes, both client and host are running the absolute latest.

**Comment by 8BallBomBom** [comment]
Sorry i should have put more info.
Seems to be using DXGI and the resolutions 1366x768 if i change it to something like 1920x1080 then it starts working on OBS, but it does work on the client at the 1366x768 resolution.

**Comment by gnif** [comment]
ok, this is a "stride" issue, 1366 is not memory aligned so the GPU actually allocates a bit of extra ram to align each row and OBS is not taking this extra padding into account and ignoring it. I will see what I can do.

**Comment by 8BallBomBom** [comment]
Thanks for the fix :)
