### ISSUE TITLE
Troubleshooting documentation 

### ISSUE THREAD

**Issue by dsjstc** [gnif/LookingGlass#25]
I felt the lack of a troubleshooting FAQ.  Here are a few minor documentation points that would've really helped me get going, as of Alpha-7, phrased for possible inclusion in a FAQ or troubleshooting guide.

- Any kind of permission error probably means your qemu process is running as other than your login user.  [This is documented.]
- Your guest GPU almost certainly supports DXGI.  The server-side (guest) probing error "Capture is not possible, unsupported device or driver" indicates NVidia duplication has failed, not that DXGI has failed.  You can make the error go away by specifying a "-c" option.
- The server log does not show any indication of client connections, so don't expect any.
- If your client hangs at "Waiting for host to signal it's ready...", you likely have a communication issue between the client and server.
- Display Spice is not strictly necessary, but without it, you cannot send mouse/keyboard from the host to the guest.

And one comment directly to the authors:

- The guest-side application is called "host".  This is confusing in the context of virtualization.  Suggest you change this nomenclature to "server" to make it clear that it pairs with the host-side client.

### Required information
Host CPU: i5-4690K
Host GPU: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
Guest GPU: Nvidia GTX 760
Host Kernel version:  4.13.0-19-generic 
Host QEMU version: QEMU emulator version 2.10.1(Debian 1:2.10+dfsg-0ubuntu3)

**Comment by gnif** [comment]
Would you be interested in authoring said FAQ on the website?

**Comment by dsjstc** [comment]
Sure, happy to help!

**Comment by gnif** [comment]
Closing as resolved as this is underway by @dsjstc
