### ISSUE TITLE
obs plugin does not build on looking-glass-2:B1/Does not display on latest commit

### ISSUE THREAD

**Issue by anthr76** [gnif/LookingGlass#250]
### Required information

Host CPU: 2560x
Host GPU: Radeon VII
Guest GPU: GTX 1080Ti 
Host Kernel version: 5.5.8-arch1-1
Host QEMU version: QEMU emulator version 4.2.0

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do not include this information will be ignored and closed**

Output on commit 163a2e5d0a1168637da2524717b1328165c3c0b0 (looking-glass-2:B1)

```
CMake Error: The source directory "/home/anthony/Downloads/LookingGlass/obs" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

Building looking glass OBS plugin on the latest master commit gives me a black screen on OBS. Assuming this is a compatibility issue

**Comment by anthr76** [comment]
My existing OBS plugin is just showing a black screen reading the shm

**Comment by gnif** [comment]
> Output on commit 163a2e5 (looking-glass-2:B1)

The OBS plugin doesn't exist in this version, it's too old.

> Building looking glass OBS plugin on the latest master commit gives me a black screen on OBS

Please check the output of OBS (run it on the console).

**Comment by gnif** [comment]
Closing due to lack of updates
