### ISSUE TITLE
c-host build on OpenSuse based VM fails

### ISSUE THREAD

**Issue by kolomansell** [gnif/LookingGlass#252]
### Required information

Host CPU:Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Host GPU: Intel® UHD Graphics 630
Guest GPU: 1050ti
Host Kernel version: 5.5.7-1-default
Host QEMU version: 4.2.0-5.1

Hello, I am trying to set up Linux hypervisor -> Linux VM, both Opensuse tumbleweed.
While compiling c-host I am getting following error during the build:

`tw1050ti:~/LookingGlass/c-host/build # cmake ..
-- The C compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- The following features have been enabled:

 * ENABLE_BACKTRACE, Backtrace support.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/LookingGlass/c-host/build
tw1050ti:~/LookingGlass/c-host/build # make
Scanning dependencies of target lg_common_platform_code
[  4%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/crash.c.o                                                                                     
[  8%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/sysinfo.c.o                                                                                   
[ 13%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/thread.c.o                                                                                    
[ 17%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/event.c.o                                                                                     
[ 21%] Building C object common/src/platform/linux/CMakeFiles/lg_common_platform_code.dir/ivshmem.c.o                                                                                   
[ 26%] Linking C static library liblg_common_platform_code.a
[ 26%] Built target lg_common_platform_code
Scanning dependencies of target lg_common
[ 30%] Building C object common/CMakeFiles/lg_common.dir/src/stringutils.c.o
[ 34%] Building C object common/CMakeFiles/lg_common.dir/src/stringlist.c.o
[ 39%] Building C object common/CMakeFiles/lg_common.dir/src/option.c.o
[ 43%] Building C object common/CMakeFiles/lg_common.dir/src/framebuffer.c.o
[ 47%] Linking C static library liblg_common.a
[ 47%] Built target lg_common
Scanning dependencies of target capture_XCB
[ 52%] Building C object platform/Linux/capture/XCB/CMakeFiles/capture_XCB.dir/src/xcb.c.o
/root/LookingGlass/c-host/platform/Linux/capture/XCB/src/xcb.c: In function ‘xcb_getFrame’:
/root/LookingGlass/c-host/platform/Linux/capture/XCB/src/xcb.c:223:21: error: incompatible type for argument 1 of ‘framebuffer_write’
  223 |   framebuffer_write(frame, this->data, this->width * this->height * 4);
      |                     ^~~~~
      |                     |
      |                     FrameBuffer {aka struct stFrameBuffer}
compilation terminated due to -Wfatal-errors.
make[2]: *** [platform/Linux/capture/XCB/CMakeFiles/capture_XCB.dir/build.make:63: platform/Linux/capture/XCB/CMakeFiles/capture_XCB.dir/src/xcb.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: platform/Linux/capture/XCB/CMakeFiles/capture_XCB.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
Thanks for help.

**Comment by gnif** [comment]
This is known, the Linux c-host is not being actively maintained at this point and needs some TLC.
