### ISSUE TITLE
Feature Request: Use remote host framebuffer via Thunderbolt3-DMA

### ISSUE THREAD

**Issue by renne** [gnif/LookingGlass#254]
### Required information

Host CPU: any current Intel
Host GPU: Intel/AMD/Nvidia
Guest GPU: Intel/AMD/Nvidia
Host Kernel version: 4.x+
Host QEMU version: 2.11+

### Feature Request
Thunderbolt3 docks for notebooks are quite expensive.

Connecting two hosts with with a passive Thundebolt3 cable allows DMA access between hosts. This can be used to write directly into the framebuffer of another host to use the VGA-heads of that host.

**Comment by gnif** [comment]
Sorry but this is outside the scope of what Looking Glass is trying to achieve.
