### ISSUE TITLE
proper way to close the LG client

### ISSUE THREAD

**Issue by fisherwise** [gnif/LookingGlass#256]
### Required information

Host CPU: Intel 9700k
Host GPU: Intel 630
Guest GPU: RTX 2080Ti
Host Kernel version: 5.5.10-200.fc31.x86_64
Host QEMU version: 4.1.1

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

I'm not sure if Ctrl+C is the proper way to close. I tried it on host(client) and it shows "Caught signal, shutting down..." and nothing else happened.

**Comment by gnif** [comment]
Ctrl+C is fine, as is just closing the window... it's just a debug message to confirm that it performs a proper shutdown.

**Comment by fisherwise** [comment]
Sorry I'm not making this clear. The window didn't close after I do ctrl+c or close the window directly. I've tried:
1. ctrl+c
2. close the window
3. close the terminal that runs linux client
4. Gnome says the window is not responding and asks to force quit that window and I clicked yes

None of them works.
What works for me is ```kill -9```

**Comment by gnif** [comment]
What version of LG are you running? and please show the client's output/log.
