### ISSUE TITLE
Client not refreshing

### ISSUE THREAD

**Issue by fisherwise** [gnif/LookingGlass#257]
### Required information

Host CPU: Intel 9700k
Host GPU: Intel 630
Guest GPU: RTX 2080Ti
Host Kernel version: 5.5.10-200.fc31.x86_64
Host QEMU version: 4.1.1

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

I'm using the latest version for host and client(both compiled from source) and I'm able to connect to my VM, but the client isn't refreshing. It's a bit weird that I can see the cursor in VM is moving but everything else isn't updating as it should be. The VM is using DXGI and the resolution is 2560x1440. My shared memory size is 64M.

**Comment by gnif** [comment]
Please ask for support on the L1Tech forums
