### ISSUE TITLE
Keyboard Capture Mode

### ISSUE THREAD

**Issue by gnif** [gnif/LookingGlass#26]
Investigate a way to implement a keyboard capture mode that captures hotkeys destined for the window manager.

Ref Issue: #21

**Comment by Vaporeon** [comment]
Can you add a exit or change VT hotkey?
If you have sdl2 built with --enable-video-kmsdrm you can run looking glass directly via KMS/GBM, however that leaves you with no host input at all and the client must be killed over SSH as there is no WM to interact with it.
Performance seemed noticeably better when running this way, by the way.

**Comment by zhLoser01** [comment]
c:\users\administrator\desktop\looking\lookingglass-a11\host\ivshmem.cpp(24): fatal error C1083: 无法打开包括文件: “vendor/kvm-guest-drivers-windows/ivshmem/Public.h”: No such file or directory

**Comment by InfinityMod** [comment]
From my understanding a keyboard/mouse hook via evdev ([link](https://www.reddit.com/r/VFIO/comments/61mf54/is_anyone_here_using_evdev_passthrough_to_share/), [qemu_source](https://github.com/qemu/qemu/blob/341b7186e7bf0ed94fbf9b7303dfe2fdf3b71ea6/ui/input-linux.c) like qemu and other visualization tools does it is possible. 

Matthewaveryusa wrote some nice gist to try the keyboard/mouse hooking out ([link](https://gist.github.com/matthewaveryusa/a721aad80ae89a5c69f7c964fa20fec1)).

I also tried both, the qemu implementation and the gist (on arch) and both run excellent. Probably this would be a chance to grab the keyboard/mouse inputs completely without getting reinterpreted by instances like the compositor or the desktop surface on the unix system.

**Comment by gnif** [comment]
it certainly is but is not a current goal of this project.

**Comment by rokups** [comment]
For what it's worth i get around this issue by creating custom kwin window rule that disables global shortcuts when looking-glass window is active. I use same trick for rdp as well.

**Comment by ohrly** [comment]
Well xfce do not support window dependent rules for all I know...
I can start looking-glass-client as "window manager":
`startx looking-glass-client -- :1 vt8`
and switch with [CTRL]+[ALT]+[F8] to the alternative Xsession.
Only problem now is, that the pulse audio VM output from xfce gets suspended, everything else works grate!
The only problem now is that the Pulse Audio VM output gets suspended when switching, everything else works fine!

**Comment by gnif** [comment]
This should be fixed as of 4a823d0e4fdada800743a4b02f9602af95e31b38. Can you please confirm?

**Comment by ohrly** [comment]
Yeah nice! Works for me with Xubuntu 20.04!
Many thanks! This makes it totally usable for gaming and everyday use!

For anyone who updates and has the problem with compiling the master there is a new lib requirement:
https://looking-glass.io/wiki/Installation#Installing_Build_Dependencies

**Comment by gnif** [comment]
Thanks, closing as fixed.
