### ISSUE TITLE
LG source freezes/turns black under OBS

### ISSUE THREAD

**Issue by lae** [gnif/LookingGlass#262]
### Required information

Host CPU: Intel Xeon E-2176G
Host GPU: onboard
Guest GPU: Radeon RX 480
Host Kernel version: 5.6.2-arch1-2
Host QEMU version: 4.2.0

This is my first time attempting to use the OBS plugin and I'm running into an issue where OBS will, after typically a few minutes (does not appear to be consistent) the source will freeze (or turn black if there is a transform like "Fit to Screen" applied to the source). So far the only way I'm able to reload the source *while* OBS is active is to go to the source's properties and click `Defaults`.

`obs --verbose --unfiltered_log` prints out the following whenever it happens:

```
138623355456 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
lgmpClientAdvanceToLast: LGMP_ERR_QUEUE_TIMEOUT
```

I'm not sure if that's a symptom of the CPU being overloaded or not, but I'll experiment a bit more and update if needed. I also noticed a `LGMP_ERR_QUEUE_UNSUBSCRIBED` error and I think that occurred when Secure Desktop was active (login screen), and once I'd logged in the source didn't come back. I'll have to double check this.

Anyway, I would expect that the normal behaviour in either of these situations (and other failures) is that the OBS plugin should try to reattach at regular intervals.

**Comment by gnif** [comment]
The OBS plugin is experimental and unsupported at this time, please do not open issues for it unless they are PRs to fix bugs or add features.
