### ISSUE TITLE
GetFramePointerShape may fail on desktop change

### ISSUE THREAD

**Issue by DataBeaver** [gnif/LookingGlass#264]
Host CPU: i7-6700k
Host GPU: GTX 660
Guest GPU: GTX 980
Host Kernel version: 5.2.14
Host QEMU version: 4.2

On one occasion the Looking Glass host terminated when an UAC prompt popped up and I found this in the log:

[E]               dxgi.c:795  | dxgi_capture                   | Failed to get the new pointer shape: 0x887a0026 (The keyed mutex was abandoned.)
[E]                app.c:536  | app_main                       | Capture interface reported a fatal error

It seems to be a very rare occurrence and I was not able to reproduce it, but it seems to me that the return value of IDXGIOutputDuplication_GetFramePointerShape could be handled more robustly.  Proposed patch here: http://www.tdb.fi/~tdb/tmp/0001-Improve-DXGI-error-handling.patch

The error occurred in a build with the patch from https://github.com/gnif/LookingGlass/issues/263 applied, but I think it's just a matter of extremely unfortunate timing and that patch has nothning to do with it.

**Comment by gnif** [comment]
Yes, it appears to be an unavoidable race condition on teardown, your proposed fix looks good and I will be reviewing this shortly.

**Comment by gnif** [comment]
I have managed to replicate this fairly easily simply by hitting Ctrl+Alt+Del and going back several times, this fix is certainly required.
