### ISSUE TITLE
Randomly Failed to map the shared memory file

### ISSUE THREAD

**Issue by BinaryAura** [gnif/LookingGlass#265]
### Required information

Host CPU: Ryzen 9 3950X
Host GPU: Nvidia RTX 1070
Guest GPU: Nvidia GTX 2070
Host Kernel version: 5.5.15-200
Host QEMU version: 4.1.1-1
Looking Glass version: B1-rc6-6-gb979752989+1

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

After logging in and launching my VM, I attempt to launch looking-glass-client and get the following output:
```
[jadunker@asteria ~]$ virsh --connect qemu:///system domstate Windows
running

[jadunker@asteria ~]$ looking-glass-client 
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-6-gb979752989+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[E]               main.c:871  | map_memory                     | Failed to map the shared memory file: /dev/shm/looking-glass
[E]               main.c:1212 | run                            | Failed to map memory
```

"/dev/shm/looking-glass" permissions are:

```
[jadunker@asteria ~]$ ls -l /dev/shm/looking-glass 
-rw-rw-r--. 1 jadunker jadunker 0 Apr 12 01:11 /dev/shm/looking-glass
```

I can not intentionally get this to reoccur. I know that restarting the computer fixes the problem. Relogging in does not. I was working on a script to handle USB Hotswapping, launching the VM, looking glass, and scream, and cleanly closing looking glass so that scream closes as well. I was constantly starting and stopping the VM, looking glass and scream.

Is there a way to get more information on this error so that if it happens again I can include that as well?
**Reports that do not include this information will be ignored and closed**

**Comment by Veriln** [comment]
Have you [installed the IVSHMEM driver](https://looking-glass.hostfission.com/wiki/Installation#Installing_the_IVSHMEM_Driver)?

**Comment by gnif** [comment]
not a LG issue but a VM/Qemu configuration issue, please ask for assistance on the L1Tech forums.
