### ISSUE TITLE
NvFBC doesn't handle Windows DPI scaling

### ISSUE THREAD

**Issue by fatalis** [gnif/LookingGlass#268]
### Required information

Host CPU: i7-8700k
Host GPU: RX 580
Guest GPU: 1070 Ti
Host Kernel version: 5.6.3-arch1-1-vfio
Host QEMU version :4.2.0

When using NvFBC and Windows scaling other than 100%, the screen is not scaled properly. DXGI does not have this problem.

**Comment by gnif** [comment]
NvFBC is not supported on your GPU, and it is deprecated by NVidia. Please do not ask for support for this feature here.

**Comment by fatalis** [comment]
why does NVFBC_PRIV_DATA exist?

**Comment by gnif** [comment]
I am not allowed to enable or educate people on how to enable NvFBC on non-professional GPUs, `NVFBC_PRIV_DATA` simply provides a way to provide unknown undocumented data to the API, what you do with it is entirely up to you.

**Comment by gnif** [comment]
Further to this, please see: https://developer.download.nvidia.com/designworks/capture-sdk/docs/NVFBC_Win10_Deprecation_Tech_Bulletin.pdf

> Windows 10 optimizes display mode changes to offer a smooth experience while
switching between full-screen applications or changing display resolution.
Information about these optimizations is not accessible by NVFBC, resulting in
incorrectly scaled or cropped captures.

**Comment by fatalis** [comment]
deleted my stupid comment, sorry about that
