### ISSUE TITLE
OBS Plugin - Black Output

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#269]
Required information
Host CPU: AMD Ryzen 2600
Host GPU: AMD WX 2100 2GB
Guest GPU: NVIDIA GTX 1050 2GB
Host Kernel version: 5.3.0-40-generic
Host QEMU version: 4.2.0

Ran into some other issues since re-compiling the plugin with the latest resolution fix.
After a while of use with OBS the plugin outputs nothing but black.
At the same time i was playing a random game using the client.
The client itself doesn't have any issues and continues to work flawlessly.
But the OBS plugin itself just dies.
It would seem to get it working again i need to stop the stream, close OBS and re-open it.

**Comment by netboy3** [comment]
Have you looked at the closed issues? Specifically #262?

**Comment by 8BallBomBom** [comment]
Ahhhh, nope, did not see that over a brief look. will close this.
