### ISSUE TITLE
Build Depending on Fedora 32

### ISSUE THREAD

**Issue by jagauthier** [gnif/LookingGlass#272]
Following the instruction to build from the git repository I ran into this:

`/usr/src/LookingGlass/client/src/main.c:40:10: fatal error: X11/extensions/XInput2.h: No such file or directory` 
I was able to resolve this by

`dnf install libXi-devel`

The cleared the build directory and reran cmake.

**Comment by gnif** [comment]
I will update the README to point to the wiki for the install instructions where this is covered, thanks.

https://looking-glass.hostfission.com/wiki/Installation
