### ISSUE TITLE
compile Looking Glass on Fedora 32

### ISSUE THREAD

**Issue by damphell** [gnif/LookingGlass#273]
Dear,
Required information
Host CPU: AMD FX8350
Host GPU: AMD Radeon HD 6670
Guest GPU: Nvidia GeForce GTX 1050Ti
Host Kernel version: 5.6.8-300.fc32.x86_64
Host QEMU version: qemu-kvm-4.2.0-7.fc32.x86_64

I try to compile "LookingGlass" and I get this error:

`LookingGlass-Release-B1/common/src/crash.linux.c:101:8: error: implicit declaration of function 'bfd_get_section_flags'; did you mean 'bfd_set_section_flags'? [-Werror=implicit-function-declaration]
  101 |   if ((bfd_get_section_flags(crash.fd, crash.section) & SEC_ALLOC) == 0)
      |        ^~~~~~~~~~~~~~~~~~~~~
      |        bfd_set_section_flags
compilation terminated due to -Wfatal-errors.`

My operating system is: "Fedora 32"
version compiled by "cmake":

` -- The C compiler identification is GNU 10.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for modules 'sdl2;x11'
--   Found sdl2, version 2.0.12
--   Found x11, version 1.6.9
-- GMP libs: /usr/lib64/libgmp.so /usr/lib64/libgmpxx.so
-- Found GMP: /usr/include  
-- Checking for modules 'spice-protocol;nettle;hogweed'
--   Found spice-protocol, version 0.14.1
--   Found nettle, version 3.5.1
--   Found hogweed, version 3.5.1
-- Checking for modules 'egl;wayland-egl;gl'
--   Found egl, version 1.5
--   Found wayland-egl, version 18.1.0
--   Found gl, version 1.2
-- Checking for modules 'gl;glu'
--   Found gl, version 1.2
--   Found glu, version 9.0.1
-- Checking for modules 'x11;xfixes'
--   Found x11, version 1.6.9
--   Found xfixes, version 5.0.3
-- Checking for modules 'SDL2_ttf;fontconfig'
--   Found SDL2_ttf, version 2.0.15
--   Found fontconfig, version 2.13.92
-- The following features have been enabled:

 * ENABLE_OPENGL, Legacy OpenGL renderer.
 * ENABLE_EGL, EGL renderer.
 * ENABLE_CB_X11, X11 Clipboard Integration.
 * ENABLE_BACKTRACE, Backtrace support.

-- Configuring done
-- Generating done`

Your help please.

**Comment by dg98** [comment]
This is due to a newer version of binutils in Fedora 32 and should have been fixed in 2440272. Did you try to build the newest version from git?

**Comment by gnif** [comment]
https://looking-glass.hostfission.com/wiki/Installation#Building
See the **NOTE**
