### ISSUE TITLE
Installer for host

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [gnif/LookingGlass#277]
I think the best option for an installer is [nsis](https://nsis.sourceforge.io/Main_Page). It is open source, and available on linux ([Debian package](https://packages.debian.org/buster/nsis)). It also looks like it [integrates with cmake](https://cmake.org/cmake/help/v3.17/cpack_gen/nsis.html). 

Items that should be required for the installer-
- Place Looking Glass c-host binary and GPL license to `%program files%\looking-glass` or similar
- Create the scheduled task to auto start.
- Uninstall cleanly. 

Nice to haves.
- Place a readme in the install directory. 
- Select the installation location. Requires changing the scheduled task.
- Install the IVSHMEM driver. There are some variations I can see on how to accomplish this, and more issues possible, so this should wait till other installer items are done. 

 To discuss-
- License acceptance page yes or no? 
- Desktop and/or start menu shortcuts. To have the option or not? Default to yes or no?

**Comment by gnif** [comment]
Yes, I have been considering using nsis also but have not yet looked into it. Whatever used will need to be able to build a cross platform package for windows as it will be executing on linux, nsis seems to fit the bill.

> Install the IVSHMEM driver.

This means we would have to distribute it, and I am not sure how legal that would be since it's built and signed by RedHat.

**Comment by Keridos** [comment]
> This means we would have to distribute it, and I am not sure how legal that would be since it's built and signed by RedHat.
Couldn't you make it so it downloads it from red hat on installation?

**Comment by gnif** [comment]
It would have to download the entire ISO for the one driver inside it. I think we can distribute it, I will just need to contact someone there to check first.

**Comment by TheCakeIsNaOH** [comment]
There should be no problem redistributing just the signed IVSHMEM driver. The [virtio-win10-prewhql-0.1-161.zip](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/virtio-win10-prewhql-0.1-161.zip) includes a license file, which is the BSD-3-Clause, the same license as for the source code, and the license explicitly allows redistribution of binaries. The only important restriction is a requirement to include the license file with the binary, which should not be a problem.
