### ISSUE TITLE
EGL Multisampling SDL failure (B2-rc1)

### ISSUE THREAD

**Issue by jonpas** [gnif/LookingGlass#281]
### Required information

Host CPU: Intel i5-4690K @ 4.3 GHz
Host GPU: Intel HD Graphics 4600 (integrated)
Guest GPU: NVIDIA GeForce GTX 1060 6GB
Host Kernel version: `5.6.13-zen1-1-zen`
Host QEMU version: `5.0.0`

EGL initialization selects multisampling with 4 samples by default and application does not start with below error message. This seems to be the same issue as #128, just for `B2-rc1`. Disabling EGL multisampling fixes it, older commits (a week or two ago) also worked.

```
$ looking-glass-client                                                                                                                                               ~
240911577819 [I]               main.c:1610 | main                           | Looking Glass (B1-209-g26eea64689+1)
240911577842 [I]               main.c:1611 | main                           | Locking Method: Atomic
240911577917 [I]             config.c:330  | config_load                    | Loading config from: /etc/looking-glass-client.ini
240911615691 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
240911641458 [I]                egl.c:189  | egl_initialize                 | Double buffering is off
240911647617 [I]                egl.c:203  | egl_initialize                 | Multisampling enabled, max samples: 4
240911647627 [I]               main.c:1070 | try_renderer                   | Using Renderer: EGL
240911647753 [E]               main.c:1307 | lg_run                         | Could not create an SDL window: Couldn't find matching GLX visual
```

**Comment by gnif** [comment]
Can't you just turn off multisample as per the option? `egl:multisample=off`

**Comment by jonpas** [comment]
Yes, that works of course. I thought I would report it going by #128 it seemed like the intention was to programmatically figure that out. I don't mind either way (maybe just a hint in the error message). :)

> Please provide the last version it was working in so I have something to compare.

dcce288a986f88b8adff99097a57917f6f3cf368 is what I was using until today. No configuration changes, but defaults may have changed, I wasn't really paying attention to that.

**Comment by gnif** [comment]
Nothing has changed in the init code for EGL with regards to multisample since B1 IIRC, it's likely your defaults.

**Comment by jonpas** [comment]
I might try again with an older version. I am not sure if the default was changed to EGL since then or something else.

**Comment by mwpastore** [comment]
Sorry to necro an old issue, but I'm having a similar problem on similar hardware and I might have some new information. Specifically...

Host CPU: Intel i7-4790K @ 4GHz
Host GPU: Intel HD Graphics 4600 (integrated)
Guest GPU: NVIDIA GeForce GTX 1030 2GB
Host Kernel version: 5.8.0-33-generic (ubuntu)
Host QEMU version: 5.0.0 (Debian 1:5.0-5ubuntu9.2)

Starting looking-glass-client (B2-78-g5802bfb5eb) in Xorg gives the same error:

```
$ looking-glass-client
  7138689253 [I]               main.c:1902 | main                           | Looking Glass (B2-78-g5802bfb5eb)
  7138689274 [I]               main.c:1903 | main                           | Locking Method: Atomic
  7138723432 [I]            ivshmem.c:121  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
  7138769302 [I]                egl.c:200  | egl_initialize                 | Double buffering is off
  7138776058 [I]                egl.c:214  | egl_initialize                 | Multisampling enabled, max samples: 4
  7138776068 [I]               main.c:1303 | try_renderer                   | Using Renderer: EGL
  7138776214 [E]               main.c:1568 | lg_run                         | Could not create an SDL window: Couldn't find matching GLX visual
```

I can work around it in one of three ways:

1. run `export SDL_VIDEO_X11_VISUALID=` before launching looking-glass-client
2. add `egl:multisample=no` to the looking-glass-client command
3. add `app:renderer=opengl` to the looking-glass-client command

Here's what's interesting: multi-sampling works just fine when I launch looking-glass-client in Xwayland!

```
$ looking-glass-client
```

(Of course, everything else is broken.) 

Not sure if this helps at all or is just more noise... and of course happy to open a new issue if that's appropriate. Just say the word.
