### ISSUE TITLE
LGMP_ERR_INVALID_VERSION with gmp 6.2.0-1

### ISSUE THREAD

**Issue by Philipose** [gnif/LookingGlass#282]
### Required information

Host CPU: Ryzen 1700x
Host GPU: NVIDIA GTX 1050Ti
Guest GPU: Radeon Vega 64
Host Kernel version: 5.6.14-arch1-1
Host QEMU version: 5.0.0-6
Host OS: Arch Linux

Hello!
I am trying to run looking-glass-client from B2-RC2 source. Build went fine. When executing (./looking-glass-client -s) I get the following error

3355379358 [I]               main.c:1583 | main                           | Looking Glass (B2-rc2-1-gbc7871f630+1)
3355379395 [I]               main.c:1584 | main                           | Locking Method: Atomic
3355441835 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
3355478509 [I]                egl.c:187  | egl_initialize                 | Double buffering is off
3355484689 [I]                egl.c:201  | egl_initialize                 | Multisampling enabled, max samples: 4
3355484712 [I]               main.c:1054 | try_renderer                   | Using Renderer: EGL
3355503346 [I]               main.c:1378 | lg_run                         | Using Clipboard: X11
3355505613 [E]              event.c:109  | lgWaitEventAbs                 | Timed wait failed
3355511245 [I]                egl.c:394  | egl_render_startup             | Supported extensions: EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_platform_x11 EGL_EXT_platform_device EGL_KHR_platform_wayland EGL_EXT_platform_wayland EGL_MESA_platform_gbm EGL_MESA_platform_surfaceless
3355511264 [I]                egl.c:400  | egl_render_startup             | use native: false
3355541377 [I]                egl.c:489  | egl_render_startup             | Vendor  : NVIDIA Corporation
3355541396 [I]                egl.c:490  | egl_render_startup             | Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
3355541399 [I]                egl.c:491  | egl_render_startup             | Version : OpenGL ES 3.2 NVIDIA 440.82
3355704882 [E]               main.c:1452 | lg_run                         | lgmpClientSessionInit Failed: LGMP_ERR_INVALID_VERSION

I looked at gmp and the version is 6.2.0-1

Is there a specific version of gmp I need to be on?
I've been following the project on and off and haven't had personal success but excited about this project nonetheless. This seems like the first issue that seems like I can actually address properly

**Comment by gnif** [comment]
GMP is not LGMP, they are different things.You did not upgrade the host application in Windows.
