### ISSUE TITLE
Windows Host Prebuilt Binary Flagged as Virus by Windows Defender

### ISSUE THREAD

**Issue by akissu** [gnif/LookingGlass#285]
### Required information

Host CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Host GPU: Intel Corporation UHD Graphics 630 (Mobile)
Guest GPU: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile] (rev a1)
Host Kernel version: 5.6.15-arch1-1
Host QEMU version: 5.0.0-7

Attempting to download prebulit release candidate commit hash d579705b from looking-glass.hostfission.com/downloads triggers Windows Defender, which immediately deletes the ZIP and flags the binary as `Trojan:Win32/Fuery.B!cl`. Is this a false-positive?

**Comment by gnif** [comment]
Yes, it's a false positive. It has already been reported to Microsoft and the flag was removed but it seems defender updates are not pushed out globally at the same time.

**Comment by christophschw** [comment]
This is still the case ... It is flagged as Win32/Zpevdo.B, using bleeding edge version from 2020-08-13 11:52:15.

Thanks for your work!

**Comment by gnif** [comment]
Sorry, there is nothing we can do, this has been reported about 12 times now to Microsoft and they keep false flagging it.
