### ISSUE TITLE
A few errors building on Solus [B2-rc2]

### ISSUE THREAD

**Issue by Khrona98** [gnif/LookingGlass#286]
### Required information

Host CPU: i7 8700k
Host GPU: RX 5700 XT
Guest GPU: GTX 1060
Host Kernel version: 5.6.18
Host QEMU version: 4.2.0

There seems to be at least two issues when trying to build Looking Glass on Solus:

## 1st Issue:
When executing `make` at the `/LookingGlass-B2-rc2/client/build` directory, this error appears at `61%`:
```
[ 61%] Building C object renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o
/home/jojo/Downloads/LookingGlass-B2-rc2/client/renderers/EGL/egl.c:34:10: fatal error: wayland-egl.h: No such file or directory
   34 | #include <wayland-egl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [renderers/EGL/CMakeFiles/renderer_EGL.dir/build.make:211: renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:540: renderers/EGL/CMakeFiles/renderer_EGL.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Commenting out the following lines inside `/LookingGlass-B2-rc2/client/renderers/EGL/egl.c` let the process continue without errors for a while:
```
Lines 33 - 35:

#if defined(SDL_VIDEO_DRIVER_WAYLAND)
#include <wayland-egl.h>
#endif
```
```
Lines 417 - 432:

#if defined(SDL_VIDEO_DRIVER_WAYLAND)
    case SDL_SYSWM_WAYLAND:
    {
      int width, height;
      SDL_GetWindowSize(window, &width, &height);
      if (!useNative)
        this->display = eglGetPlatformDisplay(EGL_PLATFORM_WAYLAND_KHR, wminfo.info.wl.display, NULL);
      else
      {
        EGLNativeDisplayType native = (EGLNativeDisplayType)wminfo.info.wl.display;
        this->display = eglGetDisplay(native);
      }
      this->nativeWind = (EGLNativeWindowType)wl_egl_window_create(wminfo.info.wl.surface, width, height);
      break;
    }
#endif
```
## 2nd Issue:
At `91%` through `make`, the following error appears:
```
[ 91%] Building C object CMakeFiles/looking-glass-client.dir/src/main.c.o
/home/jojo/Documents/Programs/LookingGlass-B2-rc2/client/src/main.c: In function ‘lg_run’:
/home/jojo/Documents/Programs/LookingGlass-B2-rc2/client/src/main.c:1447:19: error: implicit declaration of function ‘lgmpClientSessionInit’; did you mean ‘lgmpClientSessionValid’? [-Werror=implicit-function-declaration]
 1447 |     if ((status = lgmpClientSessionInit(state.lgmp, &udataSize, (uint8_t **)&udata)) == LGMP_OK)
      |                   ^~~~~~~~~~~~~~~~~~~~~
      |                   lgmpClientSessionValid
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/looking-glass-client.dir/build.make:83: CMakeFiles/looking-glass-client.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:371: CMakeFiles/looking-glass-client.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Commenting out the following lines inside `/LookingGlass-B2-rc2/client/src/main.c` also get rid of this error, this time letting the process fully finish without further errors appearing:
```
Lines 1447 - 1454:

if ((status = lgmpClientSessionInit(state.lgmp, &udataSize, (uint8_t **)&udata)) == LGMP_OK)
      break;

    if (status != LGMP_ERR_INVALID_SESSION && status != LGMP_ERR_INVALID_MAGIC)
    {
      DEBUG_ERROR("lgmpClientSessionInit Failed: %s", lgmpStatusString(status));
      return -1;
    }
```

**Comment by gnif** [comment]
> 1st Issue

Wayland is not supported officially, that said, install the wayland development headers on your system, this is not a LG issue.

> 2nd Issue

Update the project submodules.

**Comment by Khrona98** [comment]
>
> Wayland is not supported officially, that said, install the wayland development headers on your system, this is not a LG issue.
>

I forgot to put it on the original post, but Solus doesn't use Wayland, could it be something else that is giving this error?

> 
> Update the project submodules.
>

Thanks, I will do that, if I find any more problems I'll comment here.

**Comment by gnif** [comment]
Solus has clearly been build with libraries that support Wayland, such as SDL, otherwise, that ifdef would be false and you would not have this issue. You do not have the development headers installed which are required if you are building with SDL when it has wayland support.

**Comment by Khrona98** [comment]
Installing wayland-devel and libxfixes-devel fixes the issue like you said. And it looks like there is no more errors, thanks for the help!
