### ISSUE TITLE
AMD vs NVIDIA GPU recommendations?

### ISSUE THREAD

**Issue by dm17** [gnif/LookingGlass#287]
Based on various accounts reading online it seems both AMD & NVIDIA are fully supported - is that true? Is there an official GPU recommendation from looking glass devs?
Thanks a lot!

**Comment by gnif** [comment]
Issues are not for Q&A, use the advertised support channels, please.

**Comment by dm17** [comment]
Considering that googling has returned nothing on this topic from LookingGlass, I'd prefer it was in GitHub than non-searchable search channels :)

**Comment by gnif** [comment]
What about L1Tech the forum makes it not searchable? Issues on GitHub are as their name suggest, for "issues", this is not an issue but a question on the current hardware market, this answer could not possibly still be valid in 6-12 months or years from now as the hardware landscape changes.

https://forum.level1techs.com/c/software/lookingGlass

**Comment by dm17** [comment]
OK feel free to delete this thread.
