### ISSUE TITLE
Fedora 32: Requiring Sudo for tilebar, and naviagate window.

### ISSUE THREAD

**Issue by anthr76** [gnif/LookingGlass#288]
### Required information

Host CPU: Threadripper 2950X
Host GPU: Radeon VII
Guest GPU: GTX 1080 Ti
Host Kernel version: 5.7.7-200
Host QEMU version: 4.2.0

When attempting to run looking-glass-client as a regular user on Fedora 32(Wayland session) no tile-bar show's up for looking-glass-client

![image](https://user-images.githubusercontent.com/25143877/86857780-388e6800-c08d-11ea-807f-c623031d86f8.png)

Though when running as root this isn't an issue. 
![image](https://user-images.githubusercontent.com/25143877/86857836-5d82db00-c08d-11ea-8504-9109ad1c8179.png)

This doesn't appear to be a permission issue with `/dev/shm/looking-glass`

**Comment by anthr76** [comment]
Setting full-screen causes graphic glitching in the window.

**Comment by gnif** [comment]
Wayland is not supported at this time.

As LG uses SDL2 to create the window your issue is not related to 
looking glass but SDL2.

**Comment by anthr76** [comment]
Understood, so I'm assuming the best workaround this time would be to run in a X session? I can test if this is not an issue on X and report back later.

**Comment by gnif** [comment]
It is better supported, no idea if it will fix the issue for your system though as this is a Window Manager/SDL2 issue. As such this issue is invalid and is being closed.
