### ISSUE TITLE
Laggy client mouse movement when host screen isn't changing immediately after interaction with desktop

### ISSUE THREAD

**Issue by nomadiclizard** [gnif/LookingGlass#289]
Host CPU: Threadripper 1950X
Host GPU: AMD Vega FE
Guest GPU: Nvidia 2080 Ti
Host Kernel version: 5.4.0-40-generic Ubuntu
Host QEMU version: 4.2.0

On an empty and static windows desktop, pick up a window by its titlebar and drag it around in a few circles, note that on both the native output and the client window, that the movement is perfectly smooth. Stop dragging by releasing the left mouse button, but continue to move the mouse in circles at the same pace. Note that on the native output, the mouse cursor remains smooth and tracking, but on the client window, the mouse cursor stutters and takes between 0.25 and 0.5 seconds to catch up tracking.

This seems to suggest that the mouse movements are still being sent via spice to the host correctly, but on the client side, the pointer location isn't being moved for a little while. I don't know why this would be, but the effect disappears if the host screen is being updated. e.g. if you start playing a video in a corner which causes updates to the host screen, then do the same thing (drag a window about a bit, then release it but keep moving the mouse, on the client, the mouse continues to track smoothly)

I have narrowed the problem down between commit ae2ffd0a (B2-rc1) which is running smoothly, and d579705b (B2-rc2) which is running with lag

I bisected between them (using rc1 windows host client) and found:

f5da432d384df9f140f9ef5a8125138b2484e744 is the first bad commit
commit f5da432d384df9f140f9ef5a8125138b2484e744
Author: Geoffrey McRae <geoff@hostfission.com>
Date:   Fri May 22 18:39:19 2020 +1000

    [client] put back the fps correction from drift/skew

 VERSION           |  2 +-
 client/src/main.c | 42 ++++++++++++++++++++++++++++--------------
 2 files changed, 29 insertions(+), 15 deletions(-)

Replacing:
 state.frameTime = 1e9 / 60;
with the old code fixes it

**Comment by gnif** [comment]
Thanks for your work with the bisect, however, this is a known issue with B2, the change you made simply works around the issue, but is not the solution. It's actually an issue with the EGL renderer I am yet to find some time to resolve.

**Comment by gnif** [comment]
Sorry, didn't intend to close the issue, I will update this with the fix when it's available.

**Comment by gnif** [comment]
This should be resolved, can you please confirm?
If not, please provide the full console output from the client application, as well as the host application's log.

**Comment by nomadiclizard** [comment]
Tested with rc4 host+client, all good! No more stuttering.

**Comment by gnif** [comment]
Thanks, closing this.
