### ISSUE TITLE
Build error on F32 due to buildutils

### ISSUE THREAD

**Issue by JarradTait** [gnif/LookingGlass#293]
### Required information

Host CPU: Amd Ryzen 1700
Host GPU: Amd Radeon WX3100
Guest GPU: Amd Radeon 580
Host Kernel version: 5.7.11-200.fc32.x86_64
Host QEMU version: version 4.2.1 release 1.fc3

#241 is still a problem for me as I get the following when trying to build 2019-07-23 11:38:19 | 163a2e5d | B1 as downloaded from [https://looking-glass.hostfission.com/downloads](https://looking-glass.hostfission.com/downloads) Why does fix 2440272 not apply? Do you want a new pull using ifdefs to ensure the correct code is executing for f32 users?

`/LookingGlass-Release-B1/common/src/crash.linux.c:101:8: error: implicit declaration of function ‘bfd_get_section_flags’; did you mean ‘bfd_set_section_flags’? [-Werror=implicit-function-declaration]
  101 |   if ((bfd_get_section_flags(crash.fd, crash.section) & SEC_ALLOC) == 0)
      |        ^~~~~~~~~~~~~~~~~~~~~
      |        bfd_set_section_flags
compilation terminated due to -Wfatal-errors.`

**Comment by gnif** [comment]
2440272 is post B1... not an issue
