### ISSUE TITLE
DXGI fails to capture in headless Mode

### ISSUE THREAD

**Issue by ratneshs89** [gnif/LookingGlass#296]
### Required information

Host CPU: Intel 
Host GPU: Intel integrated Graphics
Guest GPU: Intel integrated Graphics
Host Kernel version: 5.4
Host QEMU version: 4.2

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do not include this information will be ignored and closed**

I am using SRIOV enabled system on Intel GPU.

a. Windows VM has 2 display adapter entries : MSBDA and Intel
b. Windows VM running in Qemu window and workload is being executed by CPU and not on GPU.
c. Running looking glass host is not able to capture the frame . It fails to initialize DXGI capture interface.

When I looked into code in DXGI.c file 

 status = CreateDXGIFactory1(&IID_IDXGIFactory1, (void **)&this->factory);
  if (FAILED(status))
  {
    DEBUG_WINERROR("Failed to create DXGIFactory1", status);
    goto fail;
  }

  const char * optAdapter = option_get_string("dxgi", "adapter");
  const char * optOutput  = option_get_string("dxgi", "output" );

  for(int i = 0; IDXGIFactory1_EnumAdapters1(this->factory, i, &this->adapter) != DXGI_ERROR_NOT_FOUND; ++i)  
  {
    if (optAdapter)
    {
      DXGI_ADAPTER_DESC1 adapterDesc;
      IDXGIAdapter1_GetDesc1(this->adapter, &adapterDesc);

      const size_t s = (wcslen(adapterDesc.Description)+1) * 2;
      char * desc = malloc(s);
      wcstombs(desc, adapterDesc.Description, s);

      if (strstr(desc, optAdapter) == NULL)
      {
        DEBUG_INFO("Not using adapter: %ls", adapterDesc.Description);
        free(desc);
        IDXGIAdapter1_Release(this->adapter);
        this->adapter = NULL;
        continue;
      }
      free(desc);

      DEBUG_INFO("Adapter matched, trying: %ls", adapterDesc.Description);
    }

    for(int n = 0; IDXGIAdapter1_EnumOutputs(this->adapter, n, &this->output) != DXGI_ERROR_NOT_FOUND; ++n)
    {
      IDXGIOutput_GetDesc(this->output, &outputDesc);
      if (optOutput)
      {
        const size_t s = (wcslen(outputDesc.DeviceName)+1) * 2;
        char * desc = malloc(s);
        wcstombs(desc, outputDesc.DeviceName, s);

        if (strstr(desc, optOutput) == NULL)
        {
          DEBUG_INFO("Not using adapter output: %ls", outputDesc.DeviceName);
          free(desc);
          IDXGIOutput_Release(this->output);
          this->output = NULL;
          continue;
        }

        free(desc);

        DEBUG_INFO("Adapter output matched, trying: %ls", outputDesc.DeviceName);
      }

      if (outputDesc.AttachedToDesktop)
        break;

      IDXGIOutput_Release(this->output);
      this->output = NULL;
    }

    if (this->output)
      break;

    IDXGIAdapter1_Release(this->adapter);
    this->adapter = NULL;
  }

  if (!this->output)
  {
    DEBUG_ERROR("Failed to locate a valid output device");
    goto fail;
  }

**While debugging this , found the code exits if the output adapter does not exists for enumerated adapter. . Seems it's looking for a display head and since the display adapter is headless in VM , DXGI is not capturing the frame.**

When I  used Remote desktop protocol to connect to my VM , I am able to capture the frame via DXGI and in LG app.

In this case I am getting output adapter for enumerated adapter.

Can I make LG host to capture frames in headless mode (QEMU display window) ?

**Comment by gnif** [comment]
This is a Microsoft DXGI limitation, it has nothing to do with Looking Glass directly I am sorry. Also please note that intel IGP GPUs are terrible with Looking Glass due to the fact that it shares the system RAM.

If you want to discuss this further please join the vfio discord server as many there have experimented with what you are asking for here.

Closing as not directly a Looking Glass issue.
