### ISSUE TITLE
My pointer loses Looking Glass window focus before reaching the end of my VM's screen.

### ISSUE THREAD

**Issue by rizzini** [gnif/LookingGlass#297]
I can make a video showing this, if I wasn't clear. I'm sensing that I wasn't.

**Comment by Keridos** [comment]
I experienced a similar thing when using a fullscreen window on wayland. Feels like there is some quirky desyncs between the actual position of the mouse pointer on the Hosts screen vs on the VM's screen.

**Comment by gnif** [comment]
This is a known issue, several things can cause this, such as resolution switching, or entering/exiting full-screen applications in the VM. Cursor guest -> host sync is a tricky thing and is not likely to ever be perfect.

>  fullscreen window on wayland

Wayland is not supported issues pertaining to it are ignored for now.
