### ISSUE TITLE
Host does not register --help when service is installed

### ISSUE THREAD

**Issue by JJRcop** [gnif/LookingGlass#298]
When the looking glass host is installed as a service, the `--help` or `-h` options do nothing.
If the host is not installed as a service, they work as normal.

https://paste.debian.net/1160242/

VERSION is `B2-rc3-33-gdc4d1d49fa+1`

**Comment by gnif** [comment]
This is because only one instance of the process is allowed at any time and it's terminating early. There is no quick solution to this due to the way Windows applications work, I will put this on the low priority bug list.

**Comment by Josh-MB** [comment]
Does this mean there is no way to run multiple hosts (for multiple monitors) with versions after the Service was added? Using an older version (https://github.com/gnif/LookingGlass/commit/c5ff8bd4ce2d08aabe20c606e43a93f4cf1ff440 works, haven't tried any others), I'm able to run 2 hosts with 2 clients (and 2 SHM pools) to have dual monitors from the guest. If we can't run two hosts, is there (or will there be) a way to utilise multiple shm devices from the one host instance?

(Not sure if this warranted a separate issue or not, can make a new one if this is too off-topic)

**Comment by gnif** [comment]
LG was never intended to have multiple host instances running at once, this is extremely inefficient. In short, you're misusing it. Multiple monitor support is on the long term feature list.
