### ISSUE TITLE
Failed to map the shared memory device: /dev/shm/looking-glass

### ISSUE THREAD

**Issue by northernlakeNL** [gnif/LookingGlass#299]
### Required information

Host CPU: Ryzen 5 3600
Host GPU: GTX 1050
Guest GPU: RX580
Host Kernel version: 5.7.12-200.fc32.x86_64
Host QEMU version: 2:4.2.1-1
Host OS: Fedora 32 (Workstation)

**Reports that do not include this information will be ignored and closed**

Please describe what were you doing when the problem occurred. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

I am new to Linux (specifically Fedora) and I am trying to install looking glass to ease the transition from Windows to the wonderful world of Linux paired with Looking glass.

I am using libvirtd to start the virtual machine and the VM works normally and is stable.
The GPU has been successfully passed-through to the virtual machine.
But now I am trying to connect/start looking glass client (on the Linux host) and i get the following error:

```
[northie@fedora-desk looking-glass]$ ./looking-glass-client-B2-rc2-0-gd579705b10
3747236652 [I]               main.c:1583 | main                           | Looking Glass (B2-rc2-0-gd579705b10)
3747236673 [I]               main.c:1584 | main                           | Locking Method: Atomic
3747304985 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
3747305029 [E]            ivshmem.c:235  | ivshmemOpenDev                 | Failed to map the shared memory device: /dev/shm/looking-glass
3747305031 [E]               main.c:1202 | lg_run                         | Failed to map memory
```

I have found an existing issue that appears to have the same problem (#265), where you stated that this is a VM/Qemu configuration issue and should look for the Level1Techs for help. I have searched the L1T forums but i couldn't find anything regarding this problem that would actually solve this problem. Can you give me some additional pointers?

If you need any additional information please let me know, I am willing to provide this if needed.

**Comment by gnif** [comment]
Not a bug, Issues are for bug reports only. Please ask for help on the forum or in #looking-glass in the VFIO discord server.
