### ISSUE TITLE
How is linux host support going ?

### ISSUE THREAD

**Issue by stuaxo** [gnif/LookingGlass#302]
### Required information

Host CPU:  Ryzen 2500u
Host GPU:  AMD
Guest GPU:    host
Host Kernel version:  5.6.19-20
Host QEMU version:  4.2.0

Hi,
    Will this project work in situations where there is just one physical GPU - i.e. on a laptop with an AMD API ?
It sounds like shared memory + the prioritisation work this project does could help? 

How is the Linux host support going ?     
Is the idea that this will eventually be a part of qemu ?

Apologies for all the questions :)

Cheers
S

**Comment by gnif** [comment]
Issues are not for questions, please ask on the forums or on VFIO discord
