### ISSUE TITLE
tearing issue after minimised/maximised with option: looking-glass-client -F

### ISSUE THREAD

**Issue by Willie131129** [gnif/LookingGlass#303]
### Required information

Host CPU:AMD Ryzen 7 3700X
Host GPU:NVIDIA GP108 [GeForce GT 1030]
Guest GPU:NVIDIA GP107 [GeForce GTX 1050 Ti]
Host Kernel version:Kernel: 5.4.0-42-generic x86_64 bits
Host QEMU version:QEMU emulator version 4.2.0 (Debian 1:4.2-3ubuntu6.3)

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do not include this information will be ignored and closed**

Hi,
if i start  looking-glass-client -F -s -k egl:vsync egl:doubleBuffer egl:multisample
it show windows Desktop/or Games with good speed and no tearing at all.
Then i decided to minimise the looking-glass windows int he host, to do some things.
Afterwards i click on the taskbar in Linux and the looking-glass windows opens again.
But no it produces at lot of tearing.
if i do the same procedure with the following :
looking-glass-client -s -d -T it does not show any tearing effects, but it does not minimise if it looses focus by clicking on another windows  on e.g.(secondary monitor). 
It would be fine if the -F function will never start tearing after been minimised.

**Comment by gnif** [comment]
> Afterwards i click on the taskbar in Linux and the looking-glass windows opens again.
> But no it produces at lot of tearing.

Sorry but this is not an issue that LG has any control over, it's up to your GPU and video drivers to be well behaved as LG follows the standard design patterns for EGL. If a task as simple as minimizing/restore causes tearing you have a bigger issue with your system.

Note: multi-head Nvidia setups are known to have tearing issues, especially when the 2nd monitor is not identical to the first.
