### ISSUE TITLE
Host does not capture cursor

### ISSUE THREAD

**Issue by Chiiruno** [gnif/LookingGlass#304]
### Required information

Host CPU: R7 3700X
Host GPU: RX 560
Guest GPU: RX 580
Host Kernel version: 5.8.1
Host QEMU version: 5.1.0

### Description

Everything is fine except the cursor not displaying on the client, whereas if I switch inputs on my monitor the cursor shows. (So it's definitely looking glass.)
I suspect this commit: 7e362050f7fde568f2c6347e8c328af3b20dd060, does not happen with commits before.
I looked through relevant options on both client and host, but no good.
I pass through my inputs via evdev: https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Passing_keyboard/mouse_via_Evdev
Perhaps if I was using spice the cursor would show?
Logs didn't show anything useful on both sides.

**Comment by Chiiruno** [comment]
I should mention, commit I'm using for both is 7d2b3905.

**Comment by gnif** [comment]
Spice is unrelated to the drawing of the cursor. If you run the client windowed and move the cursor in/out of the application does it resolve it?

**Comment by Chiiruno** [comment]
I'm afraid not, in, out, focus, non-focus, doesn't matter.

**Comment by gnif** [comment]
Thanks, are you using xorg or wayland? And what is your window manager? gnome, i3, etc.?

**Comment by gnif** [comment]
Oh wait, it is spice related in this instance... I am sorry I thought you were using spice. I will provide a patch to fix this shortly.

**Comment by Chiiruno** [comment]
Wayland, however I use `SDL_VIDEODRIVER=x11` env variable before so it uses X.
GNOME.

**Comment by Chiiruno** [comment]
Ok, thank you.
