### ISSUE TITLE
Expected KVMFR version 2, got 1

### ISSUE THREAD

**Issue by mfilipe** [gnif/LookingGlass#305]
Do you know why it's not getting the same version if I am using B2-rc2 in the client and in the host? I am attaching the logs to check: [looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/5140164/looking-glass-host.txt) and [looking-glass-client.txt](https://github.com/gnif/LookingGlass/files/5140175/looking-glass-client.txt).

### Required information

Host CPU: AMD Ryzen 5 3600 6-Core Processor
Host GPU: GeForce GTX 1070
Guest GPU: GeForce RTX 2080 Super
Host Kernel version: 5.8.0
Host QEMU version: 5.1.0

**Comment by gnif** [comment]
` I am using B2-rc2 in the client and in the host? `

You're not, KVMFR version 2 was tagged in B2-rc4.
