### ISSUE TITLE
Resize events not handled correctly on Wayland-EGL

### ISSUE THREAD

**Issue by Xyene** [gnif/LookingGlass#306]
### Required information

Host CPU: Ryzen 3900X
Host GPU: RX 480
Guest GPU: GTX 1060
Host Kernel version: 5.4.0
Host QEMU version: 5.0.0

It looks like the Wayland EGL renderer is swapping buffers in such a way that resize events aren't triggered, leading to the guest not being resized when running with `-a`.

![image](https://user-images.githubusercontent.com/1403503/91929495-84841480-ecac-11ea-8a54-99aeadc541fa.png)

I believe I've tracked down why this happens.

When SDL receives an `xdg_surface.configure` event, it hits [`handle_configure_xdg_shell_surface`](https://github.com/spurious/SDL-mirror/blob/96f1313583bb7bb03f4cd936d4aee5b2a29066a7/src/video/wayland/SDL_waylandwindow.c#L221).  If it's not the very first configure event, it hits [this](https://github.com/spurious/SDL-mirror/blob/96f1313583bb7bb03f4cd936d4aee5b2a29066a7/src/video/wayland/SDL_waylandwindow.c#L251-L253) bit of code:

```c
        if (!(window->flags & SDL_WINDOW_OPENGL)) {
            Wayland_HandlePendingResize(window);  /* OpenGL windows handle this in SwapWindow */
        }
```

The `SDL_WINDOW_OPENGL` is set for both OpenGL and EGL windows. `SwapWindow` for EGL surfaces is [defined](https://github.com/spurious/SDL-mirror/blob/69b8870c9c9a5e4bee56a6bae63bde4113749735/src/video/wayland/SDL_waylandopengles.c#L62-L77) like:

```c
int
Wayland_GLES_SwapWindow(_THIS, SDL_Window *window)
{
    SDL_WindowData *data = (SDL_WindowData *) window->driverdata;

    if (SDL_EGL_SwapBuffers(_this, data->egl_surface) < 0) {
        return -1;
    }

    // Wayland-EGL forbids drawing calls in-between SwapBuffers and wl_egl_window_resize
    Wayland_HandlePendingResize(window);

    WAYLAND_wl_display_flush( data->waylandData->display );

    return 0;
}
```

`Wayland_HandlePendingResize` is in charge of firing off `SDL_WINDOWEVENT_RESIZED`.

In other words, `SDL_WINDOWEVENT_RESIZED` events will not be generated by SDL on Wayland-EGL until `SwapWindow` is called.

Taking a quick look at `client/renderers/EGL/egl.c` (but without much knowledge of LookingGlass itself), it looks like it is [calling `eglSwapBuffers` directly](https://github.com/gnif/LookingGlass/blob/master/client/renderers/EGL/egl.c#L597). My understanding here is it should be calling `SDL_GL_SwapWindow`, the [same way `client/renderers/OpenGL/opengl.c` does](https://github.com/gnif/LookingGlass/blob/master/client/renderers/OpenGL/opengl.c#L666). It seems like it also eschews calling `SDL_GL_CreateContext` in favor directly calling `eglCreateContext`, so there's no SDL context to call `SDL_GL_SwapWindow` on to begin with.

As a bit of a workaround, passing `app:renderer=OpenGL` does correctly generate the resize events, allowing Wayland-native LookingGlass to work (it has other issues with mouse input, but I'm still looking into those).

**Comment by gnif** [comment]
> My understanding here is it should be calling SDL_GL_SwapWindow

We are eventually moving away from SDL, so no, this is being done right.

At this time Wayland is not supported and likely won't be until after version 1.0 is released at which point my focus will move to make ADL more feature-complete where we can actually target Wayland correctly.

That said if you want to make a PR to fix this behavior it will be accepted provided it doesn't use SDL methods and doesn't break Xorg.

**Comment by anthr76** [comment]
Possibly related https://github.com/gnif/LookingGlass/issues/288

**Comment by Xyene** [comment]
@gnif: thanks for the quick response. I understand your decision to focus your finite time on X11 support first, and would normally be happy to do the legwork for improving the Wayland situation myself. That said...

> ...provided it doesn't use SDL methods and doesn't break Xorg.

Unfortunately, I don't believe this would be possible. On Wayland-EGL, you *have* to process pending resizes after calling `eglSwapBuffers` and _before_  starting to draw the next frame. I think ADL would have to do this too, when its time comes. Since this is specific to Wayland-EGL, in SDL this is wired into `SDL_GL_SwapWindow`. Really, all we'd need is the call to `Wayland_HandlePendingResize`, but that symbol is not exported by SDL, nor are all the structs it operates on (so it can't just be copy/pasted into LookingGlass).

So, I think there's nothing that can be done for now, under those restrictions. That said, would you accept PRs:

* improving the Wayland detection logic ([the current one](https://github.com/gnif/LookingGlass/blob/8692e9af80dba4a79a2ffe81fa35bbab60e4b874/client/src/main.c#L1220) is not really robust, and misses some compositors -- this would be needed even post-SDL)
* changing the default renderer on Wayland to OpenGL (since it resizes correctly, albeit seems to degrade to 16-bit color + dithering on some(?) compositors)
* adding a note to the README.md explicitly saying only X11 is supported at this time (would have saved time tracking down this issue, at least)

@anthr76: #288 is not related, but is the same issue as #227. On X11 the window manager draws window decorations; on Wayland there is a split between client-side decorations and server-side (window manager) decorations. If an application claims support for CSDs, a server will not draw them and let the client draw them itself. SDL does not support CSDs, but it looks like your DE does not support SSDs either &mdash; so nothing gets drawn.

This really is an issue with GNOME Wayland, who [have been holding out on implementing SSDs](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). SDL could implement CSDs itself, and there's [a ticket](https://bugzilla.libsdl.org/show_bug.cgi?id=4845) for that but it hasn't been done yet.

When you run with `sudo`, what actually happens is the environment gets cleared and LookingGlass no longer starts under Wayland (presumably it no longer finds `XDG_SESSION_TYPE`), but actually as an X11 app running through Xwayland. Xwayland draws decorations.

You can tell from the logs: in your first screenshot, `SDL_VIDEODRIVER=wayland`. In the second it's not, and defaults to X11 through Xwayland.

**Comment by anthr76** [comment]
> @anthr76: #288 is not related, but is the same issue as #227. On X11 the window manager draws window decorations; on Wayland there is a split between client-side decorations and server-side (window manager) decorations. If an application claims support for CSDs, a server will not draw them and let the client draw them itself. SDL does not support CSDs, but it looks like your DE does not support SSDs either — so nothing gets drawn.
> 
> This really is an issue with GNOME Wayland, who [have been holding out on implementing SSDs](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). SDL could implement CSDs itself, and there's [a ticket](https://bugzilla.libsdl.org/show_bug.cgi?id=4845) for that but it hasn't been done yet.
> 
> When you run with `sudo`, what actually happens is the environment gets cleared and LookingGlass no longer starts under Wayland (presumably it no longer finds `XDG_SESSION_TYPE`), but actually as an X11 app running through Xwayland. Xwayland draws decorations.
> 
> You can tell from the logs: in your first screenshot, `SDL_VIDEODRIVER=wayland`. In the second it's not, and defaults to X11 through Xwayland.

Thanks for this information! I hope this can be approved upon in the near future. I actually also noticed I've been using the EGL renderer the whole time. Forcing openGL doesn't work as root, and same behaviour (no SSDs) as my regular user. 

Is their a 'hack' or 'workaround' to force `looking-glass-client` to fully operate on X11 without being in a full X session?

**Comment by Xyene** [comment]
Do you just want decorations on the LookingGlass without running as root? This should work:

```bash
$ unset XDG_SESSION_TYPE
$ unset SDL_VIDEODRIVER
$ looking-glass-client ...
```

LookingGlass will run under X11 [if `XDG_SESSION_TYPE` is not set to `wayland`](https://github.com/gnif/LookingGlass/blob/8692e9af80dba4a79a2ffe81fa35bbab60e4b874/client/src/main.c#L1220).

**Comment by gnif** [comment]
This issue is closed as per the above commits.
