### ISSUE TITLE
Client Error: lgmpClientProcess Failed: LGMP_ERR_QUEUE_TIMEOUT

### ISSUE THREAD

**Issue by igor9105** [gnif/LookingGlass#307]
### Required information

Host CPU:i7  7700t
Host GPU:GeForce GTX 1060 6GB
Guest GPU:GeForce GTX 1060 6GB (yes I using same gpu)
Host Kernel version: 5.8.6-1
Host QEMU version:5.1.0

Hi! I use client version of Looking Glass (B2-rc4-0-g969effedde), and permanently got error:
 **44158707125 [E]               main.c:406  | frameThread                    | lgmpClientProcess Failed: LGMP_ERR_QUEUE_TIMEOUT**
Sometimes this happens in 5-10 minutes.

****Some** logs below from terminal:**
 43922984635 [I]               main.c:1646 | main                           | Looking Glass (B2-rc4-0-g969effedde)
 43922984669 [I]               main.c:1647 | main                           | Locking Method: Atomic
 43923315335 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
 43923422009 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
 43923425996 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
 43923426011 [I]               main.c:1074 | try_renderer                   | Using Renderer: EGL
 43923481469 [I]               main.c:1399 | lg_run                         | Using Clipboard: X11
 43923546859 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_platform_x11 EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
 43923546877 [I]                egl.c:411  | egl_render_startup             | use native: false
 43923592359 [I]                egl.c:500  | egl_render_startup             | Vendor  : NVIDIA Corporation
 43923592374 [I]                egl.c:501  | egl_render_startup             | Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
 43923592380 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 NVIDIA 450.66
 43923848159 [I]               main.c:1530 | lg_run                         | Host ready, reported version: B2-rc4-0-g969effedde
 43923848174 [I]               main.c:1531 | lg_run                         | Starting session
 44151179981 [I]               main.c:1567 | lg_run                         | Waiting for the host to restart...
 44152180487 [I]               main.c:1530 | lg_run                         | Host ready, reported version: B2-rc4-0-g969effedde
 44152180502 [I]               main.c:1531 | lg_run                         | Starting session
 44153281830 [I]               main.c:1567 | lg_run                         | Waiting for the host to restart...
 44157281976 [I]               main.c:1530 | lg_run                         | Host ready, reported version: B2-rc4-0-g969effedde
 44157281999 [I]               main.c:1531 | lg_run                         | Starting session
 44158707125 [E]               main.c:406  | frameThread                    | lgmpClientProcess Failed: LGMP_ERR_QUEUE_TIMEOUT

I appreciate any advice.

**Comment by gnif** [comment]
This is a performance/timing related issue with your system configuration. For non-bug related help please ask on the L1Tech forums or #looking-glass on the VFIO discord.

**Comment by DocMAX** [comment]
happens to me to. can we increase the timeout limit somewhere?

**Comment by gnif** [comment]
The timeout is already several seconds, which is an enormous amount of time. Increasing it will not resolve your issue.
