### ISSUE TITLE
Docker GUI Support

### ISSUE THREAD

**Issue by godrays** [gnif/LookingGlass#310]
Hi,

I'm just wondering if this project can help creating a host GUI replay support for Docker GUI applications.

Imagine that a GUI application is running in Docker container and we use X11 server to visualize the GUI app on host machine. This certainly uses network and it's super slow. It can be amazing improvement if this project can support visualization on Host machine via shared buffer.

Can we discuss how this can be achieved and how much work are there to achieve this goal?

Thanks

**Comment by gnif** [comment]
Issues are for bug reports, please take this to #looking-glass on VFIO Discord, or the L1Techs forums.
