### ISSUE TITLE
SDL is not capturing dead keys

### ISSUE THREAD

**Issue by muriloglix** [gnif/LookingGlass#312]
The program can't identify the KEYDOWN/UP event when using a dead key such as the following characters:
´, á, à, ~, ^, ã, â...
On certain keyboards like ABNT2 these accented characters are identified only by the SDL_TEXTINPUT event.

**Comment by gnif** [comment]
It is likely a scancode issue. SDL doesn't give us real scancodes to map to hardware scancodes, as such we have to do a lookup. See: https://github.com/gnif/LookingGlass/blob/master/client/src/kb.h

As I do not have a keyboard that has these keys on I can not replicate it to resolve it, note however that on a standard US keyboard that `` ` ``, `~` and `^` work fine.

If you could provide the required translations we can add these to the lookup table.

**Comment by gnif** [comment]
Seems I may have misunderstood how dead keys work, I have never had to use or implement this before. From what I understand you type the sequence <kbd>\`</kbd><kbd>a</kbd> to get a `á` character. If this is the case then the window manager/x would be doing this translation to the character and SDL would not see the two keyboard events?

Can you please run `xev` and type some of these keys, providing the relevant output form the command?

**Comment by r4m0n** [comment]
I can help with that, here's an example:

```
KeyPress event, serial 37, synthetic NO, window 0x8200001,
    root 0x1ea, subw 0x0, time 3477998212, (-940,412), root:(891,2464),
    state 0x10, keycode 48 (keysym 0xfe53, dead_tilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

KeyRelease event, serial 37, synthetic NO, window 0x8200001,
    root 0x1ea, subw 0x0, time 3477998276, (-940,412), root:(891,2464),
    state 0x10, keycode 48 (keysym 0xfe53, dead_tilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x8200001,
    root 0x1ea, subw 0x0, time 3477998795, (-940,412), root:(891,2464),
    state 0x10, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: True

KeyPress event, serial 37, synthetic NO, window 0x8200001,
    root 0x1ea, subw 0x0, time 3477998795, (-940,412), root:(891,2464),
    state 0x10, keycode 0 (keysym 0xe3, atilde), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 2 bytes: (c3 a3) "ã"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x8200001,
    root 0x1ea, subw 0x0, time 3477998863, (-940,412), root:(891,2464),
    state 0x10, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False
```

Though for me, everything works fine through LookingGlass. I have an ABNT2 keyboard, it's set as such in Windows 10 and all keys and key compositing works just fine here.

**Comment by muriloglix** [comment]
> Seems I may have misunderstood how dead keys work, I have never had to use or implement this before. From what I understand you type the sequence `a to get a `á` character. If this is the case then the window manager/x would be doing this translation to the character and SDL would not see the two keyboard events?

That's right! When you press an accent and then a letter, it will appear with that particular accent. But I'm not sure how to determine if the problem is Window Manager/Xorg.

> 
> Can you please run `xev` and type some of these keys, providing the relevant output form the command? ie:
> 
> ```
> KeyPress event, serial 34, synthetic NO, window 0x2600001,
>     root 0x6cb, subw 0x0, time 150027320, (-253,676), root:(2951,1772),
>     state 0x10, keycode 38 (keysym 0x61, a), same_screen YES,
>     XLookupString gives 1 bytes: (61) "a"
>     XmbLookupString gives 1 bytes: (61) "a"
>     XFilterEvent returns: False
> 
> KeyRelease event, serial 34, synthetic NO, window 0x2600001,
>     root 0x6cb, subw 0x0, time 150027408, (-253,676), root:(2951,1772),
>     state 0x10, keycode 38 (keysym 0x61, a), same_screen YES,
>     XLookupString gives 1 bytes: (61) "a"
>     XFilterEvent returns: False
> ```

Yes, I can, the command output is attached.
[xev.output.txt](https://github.com/gnif/LookingGlass/files/5386487/xev.output.txt)


Xev can identify the KeyPress and KeyRelease of all keys.
In this file I did a test with all the vowels with and without an acute accent, upper and lower case.

I tested the Client to insert the tilde and mine did not work, maybe the layout of your keyboard does not interpret as dead key.

When testing several key combinations I found that pressing ALT_L + ACCENT and then any key I can forward the combination.

When adding
`default:
DEBUG_INFO("Event type: %x.\n", event->type);`
in [main.c:1102](https://github.com/gnif/LookingGlass/blob/0684ff401ff782b9b8c3989475bb5ee319aab00c/client/src/main.c#L1102) it triggers the value 0x303 that corresponds to the SDL_TEXTINPUT event in the SDL_events.h file by mapping the keystroke in UTF-8 string.

Notes: I am using Gentoo with KDE. I don't know if KDE could influence that.

**Comment by gnif** [comment]
We simply send the scancodes to the guest as they come in. If it's as I understand it, the issue is your windows configuration, not LG.

**Comment by muriloglix** [comment]
Problem solved in half.

You are right, the problem is in my system settings, if I apply the keyboard in "no dead keys" mode the LG works correctly, but unfortunately the rest of the system does not, the accent appears before the letter is pressed.

If you want you can close the problem, since KDE is doing this.

Thank's for your time!

**Comment by gnif** [comment]
4a823d0e4fdada800743a4b02f9602af95e31b38 may have fixed this, can you please confirm?

**Comment by gnif** [comment]
Closing due to lack of feedback, if this continues to be an issue I will re-open this.
