### ISSUE TITLE
minimizeOnFocusLoss no longer being respected in B2

### ISSUE THREAD

**Issue by anthr76** [gnif/LookingGlass#313]
When making looking-glass-client full screen and clicking on another window on another monitor looking-glass now minimizes.

**Comment by gnif** [comment]
This feature is controlled by `SDL` and your window manager:

```
if (params.fullscreen && !params.minimizeOnFocusLoss)                           
  SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0")
````

If it's not being honoured it's not a LG issue.

**Comment by anthr76** [comment]
Exporting `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` fixes this for me. Still unsure if that is the appropriate fix. Nevertheless thanks for your hard work.
