### ISSUE TITLE
[Website] The site ahead contains harmful programs (Google Chrome)

### ISSUE THREAD

**Issue by f0o** [gnif/LookingGlass#320]
Google Chrome thinks https://looking-glass.io/ is malware.

This is very off-putting for many people.

![image](https://user-images.githubusercontent.com/1656377/97984388-01c82480-1dd7-11eb-9f5e-72fefaf7b7a2.png)

**Comment by gnif** [comment]
This has been reported over a dozen times now and we are doing what we can to resolve it. AV vendors are false flagging on the host binary and as such Google thinks our website contains malware.

**Comment by f0o** [comment]
Glad to hear you're working on it!
however I couldnt find any similar report on Github, hence the issue.

At least now others might find this issue when they encounter this message.

**Comment by gnif** [comment]
yes, fair enough, thanks! :+1:
