### ISSUE TITLE
Cursor in guest not visible

### ISSUE THREAD

**Issue by jonpas** [gnif/LookingGlass#321]
Cursor from the mouse in the guest (Windows 10 VM) is not visible in the Looking Glass client. This started happening a bit before Beta 2, but I didn't have time to look into it at the time. It is still happening with https://github.com/gnif/LookingGlass/commit/b942085e6c635c68dc0cd7bccfc134621c0f948c.

Cursor through Looking Glass Spice works fine.

---

Host CPU: AMD Ryzen 7 3700X (16) @ 3.6 GHz
Host GPU: NVIDIA GeForce GT 710
Guest GPU: NVIDIA GeForce GTX 1060 6GB
Host Kernel version: `5.8.14-zen1-1-zen `
Host QEMU version: `5.1.0`

Looking Glass configuration:
```ini
[input]
escapeKey=109 ; SDL 'F18'

[spice]
host=/run/user/1000/spice.sock
port=0
```
I have also tried without SPICE in the past and it didn't change anything.

Client log:
```
./looking-glass-client                                                                                                 (master) ~/W/L/VFIO/LookingGlass/client/build
 11413314927 [I]               main.c:1789 | main                           | Looking Glass (B2-56-gb942085e6c)
 11413314952 [I]               main.c:1790 | main                           | Locking Method: Atomic
 11413315045 [I]             config.c:365  | config_load                    | Loading config from: /etc/looking-glass-client.ini
 11413386513 [I]            ivshmem.c:121  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
 11413404716 [I]                egl.c:196  | egl_initialize                 | Double buffering is off
 11413418893 [I]                egl.c:210  | egl_initialize                 | Multisampling enabled, max samples: 4
 11413418904 [I]               main.c:1191 | try_renderer                   | Using Renderer: EGL
 11413469542 [I]               main.c:1542 | lg_run                         | Using Clipboard: X11
 11413476570 [I]                egl.c:431  | egl_render_startup             | use native: false
 11413507904 [I]                egl.c:522  | egl_render_startup             | EGL       : 1.5
 11413507927 [I]                egl.c:523  | egl_render_startup             | Vendor    : NVIDIA Corporation
 11413507930 [I]                egl.c:524  | egl_render_startup             | Renderer  : GeForce GT 710/PCIe/SSE2
 11413507932 [I]                egl.c:525  | egl_render_startup             | Version   : OpenGL ES 3.2 NVIDIA 455.38
 11413507936 [I]                egl.c:526  | egl_render_startup             | EGL APIs  : OpenGL_ES OpenGL
 11413507939 [I]                egl.c:527  | egl_render_startup             | Extensions: EGL_EXT_buffer_age EGL_EXT_client_sync EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_MESA_image_dma_buf_export EGL_EXT_output_base EGL_EXT_stream_acquire_mode EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context_no_error EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update EGL_KHR_swap_buffers_with_damage EGL_KHR_no_config_context EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_post_sub_buffer EGL_NV_quadruple_buffer EGL_NV_stream_consumer_eglimage EGL_NV_stream_cross_display EGL_NV_stream_cross_object EGL_NV_stream_cross_process EGL_NV_stream_cross_system EGL_NV_stream_dma EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time EGL_NV_output_drm_flip_event EGL_NV_triple_buffer EGL_WL_bind_wayland_display EGL_WL_wayland_eglstream
 11413711608 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-56-gb942085e6c
 11413711620 [I]               main.c:1674 | lg_run                         | Starting session
 11413743148 [I]               main.c:481  | frameThread                    | Format: FRAME_TYPE_BGRA 2560x1080 2560 10240

```

Host log:
```
 10936716775 [I]           platform.c:329  | app_init                       | System timer resolution: 50.00 ns
 10936717606 [I]                app.c:438  | app_main                       | Looking Glass Host (B2-56-gb942085e6c)
 10936738406 [I]                app.c:454  | app_main                       | IVSHMEM Size     : 32 MiB
 10936739044 [I]                app.c:455  | app_main                       | IVSHMEM Address  : 0x2BE0000
 10936739847 [I]                app.c:456  | app_main                       | Max Pointer Size : 1024 KiB
 10936740564 [I]                app.c:457  | app_main                       | KVMFR Version    : 5
 10936741535 [I]                app.c:506  | app_main                       | Max Frame Size   : 13 MiB
 10936742193 [I]                app.c:521  | app_main                       | Trying           : NVFBC (NVidia Frame Buffer Capture)
 10936748166 [I]          wrapper.cpp:88   | NvFBCInit                      | NvFBC SDK Version: 112
 10936753853 [I]                app.c:521  | app_main                       | Trying           : DXGI
 10936822610 [I]               dxgi.c:393  | dxgi_init                      | Device Descripion: NVIDIA GeForce GTX 1060 6GB
 10936823314 [I]               dxgi.c:394  | dxgi_init                      | Device Vendor ID : 0x10de
 10936823868 [I]               dxgi.c:395  | dxgi_init                      | Device Device ID : 0x1c03
 10936824441 [I]               dxgi.c:396  | dxgi_init                      | Device Video Mem : 6052 MiB
 10936825009 [I]               dxgi.c:397  | dxgi_init                      | Device Sys Mem   : 0 MiB
 10936825609 [I]               dxgi.c:398  | dxgi_init                      | Shared Sys Mem   : 8189 MiB
 10936826199 [I]               dxgi.c:399  | dxgi_init                      | Feature Level    : 0xb100
 10936826757 [I]               dxgi.c:400  | dxgi_init                      | Capture Size     : 2560 x 1080
 10936827347 [I]               dxgi.c:401  | dxgi_init                      | AcquireLock      : enabled
 10936829247 [I]               dxgi.c:524  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
 10936830773 [I]                app.c:543  | app_main                       | Using            : DXGI
 10955089777 [I]                app.c:261  | captureStart                   | Capture Size     : 10 MiB (11059200)
 10955090435 [I]                app.c:263  | captureStart                   | ==== [ Capture  Start ] ====
 10955091178 [I]                app.c:113  | frameThread                    | Frame thread started
```

Since this was not reported by anyone else and I assume using barrier/Synergy or something similar to lock the mouse to the guest is not an out-of-the-ordinary use case, this could easily be isolated to something specific in my setup. Any information to help debug would be appreciated.

**Comment by gnif** [comment]
`B1-359-gb942085e6c` vs `B2-56-gb942085e6c`

Please update your client to the same version and test again. If it is still an issue please report the exact application/usage that causes it.

**Comment by jonpas** [comment]
Client is fresh-built as of today, commit IDs in those versions are also the same. Unless `B1` didn't get changed to `B2` for the client in source, I am unsure what else I could be doing wrong. Host is downloaded from the website.

Using https://github.com/debauchee/barrier is all that is required to cause it.

**Comment by gnif** [comment]
There is something wrong with your `cmake` build tree then, please re-create it as the mismatched versioning was fixed just after B2.

**Comment by jonpas** [comment]
There we go, problem with version that was I didn't have tags pulled from upstream, and CMake version script expects tags. This is not something Git does automatically, I wouldn't mind putting it in the documentation somewhere.

As for Barrier, I will try with Synergy and report back. If it works with Synergy I will open an issue with Barrier and this one can be closed. Thanks for the pointer regarding cursor shape feed!

**Comment by jonpas** [comment]
I tried with older Synergy again and it also doesn't work. ~~I am fairly positive that worked in the past.~~ Just realized it works fine if SPICE is disabled!

So it appears if SPICE is enabled and even though cursor is not being moved by it, Looking Glass client is not reading the client cursor.

Additionally, I discovered it actually works UNTIL the first time you move the mouse into the client (thus activating SPICE?).

**Comment by gnif** [comment]
LG does not do anything special to obtain the mouse cursor for display, it's simply using the shape provided by MS DXGI Desktop Duplication. Synergy/Barrier is a competing product that is not supposed to be used in tandem with SPICE, and clearly causes issues. This is not a bug.

**Comment by jonpas** [comment]
Maybe I was not clear enough, apologies.

**This is NOT an issue with Barrier/Synergy** or their specific compatibility. It happens by simply using the mouse directly inside the VM (Barrier/Synergy disabled) - for example a mouse passed through directly to the VM - it's cursor will not show up if you happen to move the host OS mouse into the Looking Glass client window. Is using a mouse directly attached to the VM also not supposed to be used in tandem with SPICE?

I believe my commit shows that Looking Glass is on purpose disabling drawing of the guest cursor when it probably doesn't have to. Why does SPICE have to touch anything mouse-related until mouse enters the client window, or why wouldn't it restore the state that allows both?

Sadly SPICE also doesn't cover the use-case of other machines, such as a laptop on the side, at least not through Looking Glass. Allowing this would solve both "low-latency" use-case (pass-through mouse) + productivity (SPICE) at once.

**Comment by gnif** [comment]
Ah ok, I understand sorry.

LG is designed to work as the mouse/cursor master, movement of the mouse outside of the LG window disables the draw code for the cursor itself as it would be confusing to have two mouse cursors on the screen at once (the guests and the hosts). Re-enablement of the cursor happens when the cursor is moved back within the window bounds at which point the host hardware cursor is hidden. This is a feature added to do this by design.

If you wish the cursor to remain visible at all times we can add an option for this, if I am understanding that this is indeed the issue?

**Comment by jonpas** [comment]
No issue, I went on a tangent with barrier/synergy being in a bit of a rush.

That makes sense, I can see how seeing 2 cursors could be confusing.
Correct, that is the issue. An option would be great and definitely solve my use-case without destroying the point of hiding it.

I can work on a PR for this soon if you'd like.

**Comment by Yeshey** [comment]
For someone coming here, you can run looking-glass with this option like this
`looking-glass-client spice:alwaysShowCursor`
