### ISSUE TITLE
RDP connection breaks LG host

### ISSUE THREAD

**Issue by rokups** [gnif/LookingGlass#322]
1. Boot VM and connect LG
2. Connect to a VM using RDP
   * LG client exits.
   * Restarting LG results in a crash.
3. Restart LG host service in a VM (RDP session is still active)
   * LG service enters a crash loop and spams system tray with LG icon.

[looking-glass-client.txt](https://github.com/gnif/LookingGlass/files/5529638/looking-glass-client.txt)
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/5529641/looking-glass-host.txt)

It used to be possible to mix RDP and LG sessions back when LG did not use a system service. RDP connection would send LG session into windows login screen. Logging in via LG would terminate RDP session.

Tested revision: b942085e6c635c68dc0cd7bccfc134621c0f948c (latest master, both client and host, including `looking-glass-module-dkms-git` package)

**Comment by gnif** [comment]
LG is not intended to be used with RDP, not will it ever work due to the design of the MS DXGI Desktop Duplication API.

> including looking-glass-module-dkms-git package

This is only for VM to VM configurations, do not use it if you are just using VM to Host.

**Comment by rokups** [comment]
It used to work, however. I am not suggesting that both RDP and LG sessions would work at the same time. I am merely suggesting that RDP should not crash LG host or throw it into the state where LG client can no longer reconnect.

**Comment by gnif** [comment]
The only thing I can see here that might be a cuase is the fact that you're using NvFBC, please use DXGI DD and see how things go. Please also note that NvFBC is deprecated by Nvidia and as a result will be removed from LG eventually also.

**Comment by rokups** [comment]
Tried disabling NVFBC.

1. Connected to VM using LG. That works.
2. Closed LG.
3. Connected to VM using RDP. RDP works.
4. Connecting to VM using LG no longer works. LG host service goes into crash loop.

[looking-glass-client.txt](https://github.com/gnif/LookingGlass/files/5536003/looking-glass-client.txt)
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/5536005/looking-glass-host.txt)

**Comment by anthr76** [comment]
I've been having RDP issues inside of my VM as I need it for work. I'm going to try disabling NvFBC

**Comment by rokups** [comment]
> I've been having RDP issues inside of my VM as I need it for work. I'm going to try disabling NvFBC

That does not help though.

**Comment by rokups** [comment]
@gnif can this be reopened? It is a crash in a supported configuration (with DXGI) after all..

**Comment by nairaner** [comment]
@rokups When switching RDP -> VM do you correctly switch to actual GPU? One way to do this is to run 
```tscon.exe 1 /dest:console```
which will log you out of RDP session

**Comment by rokups** [comment]
I do not do anything special since it used to work without extra steps. 
Logging in with RDP used to move LG to login screen and logging back in on 
LG used to disconnect rdp.

**Comment by gnif** [comment]
I will see about replicating this and debug, but it's pretty unlikely we can fix it due to Microsoft's desktop access control shenanigans.

**Comment by rokups** [comment]
There surely must be a way to terminate a session. Nothing else is needed.

**Comment by rokups** [comment]
I found a workaround to the crashloop. After RDP session is disconnected, i have to switch monitor input to VM GPU, then i can see login screen. Logging in that way and switching back to host allows LG to reconnect successfully.

**Comment by djesionek** [comment]
As it's possible to see and utilize the login screen through looking-glass now It would be great if someone could look into it again. Surely there must be a way to also show the login screen through looking-glass after it gets interrupted by RDP right?
