### ISSUE TITLE
Windows build classified as malware

### ISSUE THREAD

**Issue by epsilontheta** [gnif/LookingGlass#326]
The current bleeding edge windows build (Commit: db51acdd) is classified as malware / suspicious by > 50% of the antivirus scanners of virustotal (see [here](https://www.virustotal.com/gui/file/c1210763a7aeddb38525eef5feeb5c8850e3dd58da699411008b7f57c6a0f8cb/detection)).

Any idea what the problem is?
I know.. it's mostly snake oil, but the sheer number of red flags makes me wonder if there is a problem?

**Comment by mjarkk** [comment]
I think this is a duplicate of https://github.com/gnif/LookingGlass/issues/285

**Comment by gnif** [comment]
Duplicate of #285
