### ISSUE TITLE
Q: Is there any possibility to get looking glass as a Webcam device?

### ISSUE THREAD

**Issue by Bliss3d** [gnif/LookingGlass#330]
It would be very useful for my tensorflow Training. I have no clue about webcam drivers so my help would be limited...
Sorry for the long titel its the github apps fault...

**Comment by gnif** [comment]
Not sure I understand, are you asking for a webcam version of the OBS plugin for LG?

**Comment by Bliss3d** [comment]
Well my use case would be for tensorflow in python for object detection - however i just noticed that opencv would be a gigantic bottleneck if its accessed like a Webcam. So scrap that. 
I just need the a nice and most importantly fast way to get the LG image data in python with a typical lg Latency. I guess only option is a python package so I go and look into building something like that. the obs plug in seems to be a good place to start

**Comment by gnif** [comment]
Yes, OBS is a good simple example of how to subscribe to the LGMP stream and obtain the frames. Closing this issue as it's not really an issue or something we are planning to implement or support.
