### ISSUE TITLE
QEMU monitor sendkey sleep doesn't work w/ LG

### ISSUE THREAD

**Issue by alaricljs** [gnif/LookingGlass#338]
I had setup my VM so that using the qemu monitor I could 'sendley sleep' and that would trigger the VM to suspend.  With LookingGlass set up this no longer works.  Instead a \ is produced if an editor (or dialog box) is the active KB focus.  Other keys sent with the command work as expected, but I haven't tried any special keys.

No other output is observed anywhere else (client logs, host logs, ...)

**Comment by gnif** [comment]
This is not LG related, monitor commands completely bypass Looking Glass.
