### ISSUE TITLE
Plasma and LookingGlass

### ISSUE THREAD

**Issue by volvofixthis** [gnif/LookingGlass#34]
### Required information

Host CPU: i5 6600k
Host GPU: integrated graphics
Guest GPU: 1060 gtx
Host Kernel version: 4.14.11-1-ARCH
Host QEMU version: 2.11.0

Hello. I have strange problem with plasma and client application. As i uderstand sometimes when i switch off my virtual machine, my plasma window manager gets broken. Like i have no any window manager at all. All windows are working, but i can't for example switch between them. Maybe you know what it can be? I run Windows 10 guest, and Arch host.
I use such command:
~/Downloads/LookingGlass/client/bin/looking-glass-client -F -f /tmp/ivshmem_socket -s

**Comment by gnif** [comment]
Please provide the entire client output

**Comment by volvofixthis** [comment]
I found that i was not on last version, did not expect so fast development. I changed my configuration and looks like it become harder to reproduce bug. I can't switch windows so i can't copy information from client output. Now i wrote to log file, maybe i will lucky some day.

**Comment by gnif** [comment]
No worries, yes the development iterations are fast as this is still considered alpha software and I would like to see this project succeed.

I will close this for now, if the problem resurfaces feel free to reply to this issue, or open a new one :)
