### ISSUE TITLE
B2 stable - Windows host application crash immediatly after starting

### ISSUE THREAD

**Issue by maxdrash** [gnif/LookingGlass#344]
Hello.

I'm running the B2 stable for client and Windows host application.
The client stay purple, It waiting for the host application:
On the guest, the host application can't start. It crash immeditly after launching and don't provide log.
Otherwise, I have to stop the Looking glass service, if I don't, I get hundreds of looking glass purple icon in notification bar.

Windows Defender disabled.

How to get this working please ?

Tx !

**Comment by Skeen** [comment]
@maxdrash what did you find out

**Comment by gnif** [comment]
Issues are not for support! Go to the Looking Glass forum on L1Techs or #loooking-glass in VFIO on Discord
