### ISSUE TITLE
[Documentation] Allude to libvirt hooks as a way to manage /dev/shm/looking-glass-$VM_NAME automatically

### ISSUE THREAD

**Issue by XenonPK** [gnif/LookingGlass#35]
So I have finally found the time to take a look into the project, and ended up creating a [package](https://build.opensuse.org/package/show/home:xenonpk/looking-glass-client) in the Open Build Service for my own convenience.

Soon after I had it all working, however the requirement/suggestion to have /dev/shm/looking-glass be created upon boot or manually had me thinking.

Libvirt allows the use of hooks to run before VM startup/ after Shutdown, etc...

in the file: /etc/libvirt/hooks/qemu

```
#!/bin/bash
if [ "${1}" = "VM_NAME" ]; then
        if [ "${2}" = "start" ] || [ "${2}" = "reconnect" ]; then
                /bin/touch /dev/shm/looking-glass-${1}
                /bin/chown qemu:users /dev/shm/looking-glass-${1}
                /bin/chmod 660 /dev/shm/looking-glass-${1}
        fi
        if [ "${2}" = "stopped" ] || [ "${2}" = "reconnect" ]; then
                /bin/rm /dev/shm/looking-glass-${1}
        fi
fi
```

This can be defined any number of times, allowing multiple VMs to have their shared memory managed in an automated way.

**Comment by gnif** [comment]
Closing, this is not a Looking Glass bug or issue.
