### ISSUE TITLE
Failed to create EGL surface (eglError: 0x3003

### ISSUE THREAD

**Issue by ostapus** [gnif/LookingGlass#369]
looking-glass-client is exiting right after start. No issues when using opengl renderer (except the performance).

  2481029767 [I]               main.c:2270 | main                           | Looking Glass (B2-193-gb58176fcdb)
  2481029779 [I]               main.c:2271 | main                           | Locking Method: Atomic
  2481119634 [I]            ivshmem.c:121  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
  2481157808 [I]                egl.c:220  | egl_initialize                 | Double buffering is off
  2481160356 [I]                egl.c:234  | egl_initialize                 | Multisampling enabled, max samples: 4
  2481160360 [I]               main.c:1660 | try_renderer                   | Using Renderer: EGL
  2481207698 [I]               main.c:2011 | lg_run                         | Using Clipboard: X11
  2481211357 [I]                egl.c:455  | egl_render_startup             | use native: false
  2481219290 [E]                egl.c:532  | egl_render_startup             | Failed to create EGL surface (eglError: 0x3003)

Guest GPU: NVidia 1060
Host GPU: Quadro P620/PCIe
Driver: 455.45.01 (i tried with 460 version as well, same result)

**Comment by gnif** [comment]
> Failed to create EGL surface (eglError: 0x3003)

Something is wrong with your Mesa/EGL install.
