### ISSUE TITLE
Update for Ubuntu Build Instructions

### ISSUE THREAD

**Issue by YvanDaSilva** [gnif/LookingGlass#37]
OS: Ubuntu 17.10
Install state: Clean install + build-essential

### Problem Description:
The provided information on : [Compile LookingGlass from sources on ubuntu](https://looking-glass.hostfission.com/node/6) is missing some dependencies in order to compile properly LookingGlass from source.

### Errors + Solutions:
> Package libva was not found in the pkg-config search path.

`sudo apt-get install libva-dev`
> main.c:37:10: fatal error: libconfig.h: No such file or directory

`sudo apt-get install libconfig-dev`
> spice/spice.c:40:10: fatal error: spice/protocol.h: No such file or directory

`sudo apt-get install libva-dev`

### New one liner for the documentation
> sudo apt-get install git libsdl2-dev libsdl2-ttf-dev libssl-dev libspice-protocol-dev libfontconfig1-dev libx11-dev fonts-freefont-ttf libva-dev libconfig-dev build-essential

This new one liner should avoid people asking question why it doesn't compile :)

Feel free to close the issue if this doesn't apply for any reason.

**Comment by YvanDaSilva** [comment]
### An addition related to "/dev/shm/looking-glass" : 

On ubuntu apparmor will be an issue when trying to start the VM as it will complain Qemu doesn't have the rights to access the necessary /dev/shm

### Solution
`sudo vim /etc/apparmor.d/abstractions/libvirt-qemu` or Nano, or any other text editor
Add the following section
`   # for LookingGlass`
`   /dev/shm/looking-glass rw,`
`sudo service apparmor restart`

You can now start your VM

**Comment by namidairo** [comment]
> Package libva was not found in the pkg-config search path.

You are building off master instead of a tagged release.

**Comment by gnif** [comment]
Build a tagged release

**Comment by YvanDaSilva** [comment]
Oh I see, thank you :)

However you should then mention it on the documentation :)

> Cloning the Repository
To obtain the source simply clone the repository at github using the following command (or you may go to github and download the zip archive):
git clone https://github.com/gnif/LookingGlass.git .

You just ask to clone the repository. I've seen other people having the libva and libconfig issue on level1techs forums, hence this issue.

(Leave it close, just add something to the text).

Best regards.

**Comment by nazar-pc** [comment]
Faced the same issue, thanks @YvanDaSilva!
Why isn't this on website yet?

**Comment by grepwood** [comment]
@gnif Have you thought about putting this on launchpad.net?

**Comment by gnif** [comment]
@grepwood no, nor do I care to. If you wish to discuss looking glass please use the forums over at Level1Tech, this is not the place.
