### ISSUE TITLE
any plans for mouse/audio stuff?

### ISSUE THREAD

**Issue by crashtua** [gnif/LookingGlass#4]
Is there any plans for mouse/audio stuff?
Or this project will work only with video streaming?
Windows 10 has https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/virtual-hid-framework--vhf- 
and old project https://github.com/djpnewton/vmulti available. This can be used to emulate mouse and keyboard.

**Comment by gnif** [comment]
Issue's are not for asking questions...
No need to emulate anything, qemu already does.
