### ISSUE TITLE
Host/Client Cursor Render Issue

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#415]
Host CPU: AMD Ryzen 5 2600
Host GPU: AMD Radeon Pro WX2100
Guest GPU: NVIDIA Quadro P4000
Host Kernel version: 5.8.18-xanmod1
Host QEMU version: 5.0-5ubuntu6~ppa0

Unsure if i'm meant to be changing some of the start vars but now you always have the host cursor rendered on top of the client.
You can see interaction with the host cursor/client cursor below.

![Peek 2021-01-20 23-13](https://user-images.githubusercontent.com/3690196/105195177-53ca4c00-5b75-11eb-8814-ccfd57e2853a.gif)

**Comment by gnif** [comment]
are you using `captureOnly`? or is the window unfocused? in both cases, this is now by design.

**Comment by 8BallBomBom** [comment]
Changing input:captureOnly doesn't seem to make any difference as i'm not using spice and the window is running full screen with focus.

Is there an option to just entirely hide the host cursor? similar to how it was previously.

**Comment by gnif** [comment]
this is a bug then, the host cursor should not be shown at all in this case

**Comment by 8BallBomBom** [comment]
Thanks for the quick fix 😃
