### ISSUE TITLE
Ubuntu install issues

### ISSUE THREAD

**Issue by brianmadden** [gnif/LookingGlass#47]
I recently built on Ubuntu 17.10 and had to make some modifications to get the `Makefile` to work.

The following changes were necessary to the Makefile:

```
diff --git a/client/Makefile b/client/Makefile
index 00549d8..8100de1 100644
--- a/client/Makefile
+++ b/client/Makefile
@@ -1,5 +1,5 @@
 BINARY  = looking-glass-client
-CFLAGS  = -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING
+CFLAGS  = -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -I/usr/include/spice-1 -DDEBUG -DATOMIC_LOCKING
 LDFLAGS = -lrt
 
 CFLAGS  += -ffast-math
```

I also had to install `libva-dev` as the dependency was missing.

**Comment by gnif** [comment]
VAAPI is a work in progress, build a tagged release. Also `pkg-config` should be providing the include path for spice protocol, if not you need to find out what's missing/broken on your platform.
