### ISSUE TITLE
No Fullscreen/Borderless/Maximize [B3+]

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#474]
Host CPU: AMD Ryzen 9 3900X
Host GPU: AMD Radeon Pro WX2100
Guest GPU: NVIDIA Quadro P4000
Host Kernel version: 5.10.16-xanmod1
Host QEMU version: 5.2.0
Host OS: Kubuntu 20.10

Just been testing the latest master, everything seems to be functioning so far apart from the fullscreen, borderless and maximize options on the client no longer seem to work compared to the previous major release.
Haven't tested anything else as of yet.

**Comment by gnif** [comment]
Please no bug reports on the master branch with regards to window management, if you want to discuss this come into Discord. Master is going through some major changes that affect window management.

**Comment by 8BallBomBom** [comment]
Ahhh no worries 👍🏻
