### ISSUE TITLE
Client binary immediately crashes on Gentoo 

### ISSUE THREAD

**Issue by muke101** [gnif/LookingGlass#483]
I've just built the stable (B3) client on my Gentoo install following the guide on the wiki. When starting it with any command line options, the following error is printed:

```
  1298885512 [I]               main.c:2282 | main                           | Looking Glass (B3-0-g2973319bff)
  1298885546 [I]               main.c:2283 | main                           | Locking Method: Atomic
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  113
  Current serial number in output stream:  114
```

Have I misconfigured something or is it a problem with the client?

**Comment by gnif** [comment]
> integer parameter out of range for operation
Your GPU doesn't support the visual.

Please come to discord for support, issues are for bug reports only.
