### ISSUE TITLE
Notes on latest build [2021-02-22 17:25:07 (Commit: 30b5287c)]

### ISSUE THREAD

**Issue by Dave--G** [gnif/LookingGlass#493]
Here are my notes on the latest build.  This is just FYI and devs are welcome to just close the bug.
(Let me know if its not appropriate to post feedback here)

1. Client segfault on start seen in previous 'latest' builds is resolved. 👍
2. Viewing VM guest using client, the mouse cursor displays as a single white pixel.
3. This pixel appears to trigger WM_MOUSEOVER events in the guest (mouse-over window highlights, etc) but windows don't appear to respond to right or left button click events.
4. This may be trivial but there are nulls being output to the client log.  Excerpt from the log:

```
00000880  20 20 20 20 20 20 20 20  20 20 20 20 7c 20 54 69  |            | Ti|
00000890  6d 65 72 20 64 72 69 66  74 20 64 65 74 65 63 74  |mer drift detect|
000008a0  65 64 2c 20 32 38 33 30  31 35 33 30 20 69 73 20  |ed, 28301530 is |
000008b0  3e 20 38 33 33 33 33 33  33 0a 32 32 34 31 35 32  |> 8333333.224152|
000008c0  34 38 31 39 32 31 20 5b  57 5d 20 20 20 20 20 20  |481921 [W]      |
000008d0  20 20 20 20 20 20 20 20  20 6d 61 69 6e 2e 63 3a  |         main.c:|
000008e0  31 35 32 33 20 7c 20 6c  67 5f 72 75 6e 20 20 20  |1523 | lg_run   |
000008f0  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
00000900  20 20 20 20 20 20 7c 20  53 65 73 73 69 6f 6e 20  |      | Session |
00000910  69 73 20 69 6e 76 61 6c  69 64 2c 20 68 61 73 20  |is invalid, has |
00000920  74 68 65 20 68 6f 73 74  20 73 68 75 74 64 6f 77  |the host shutdow|
00000930  6e 3f 0a 00 00 00 00 00  00 00 00 00 00 00 00 00  |n?..............|
00000940  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00002a80  00 32 32 34 31 33 39 32  39 35 38 35 35 20 5b 45  |.224139295855 [E|
00002a90  5d 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |]               |
00002aa0  6d 61 69 6e 2e 63 3a 34  38 31 20 20 7c 20 73 70  |main.c:481  | sp|
00002ab0  69 63 65 54 68 72 65 61  64 20 20 20 20 20 20 20  |iceThread       |
00002ac0  20 20 20 20 20 20 20 20  20 20 20 20 20 7c 20 66  |             | f|
00002ad0  61 69 6c 65 64 20 74 6f  20 70 72 6f 63 65 73 73  |ailed to process|
00002ae0  20 73 70 69 63 65 20 6d  65 73 73 61 67 65 73 0a  | spice messages.|
00002af0
d
```
(sorry if that's a little mangled, but it's not difficult to see starting at offset 933)

**Comment by netboy3** [comment]
Distro? Specs? Are you using scream with ivshmem?

**Comment by Dave--G** [comment]
This is using Ubuntu 20.04.2/Wayland(GNOME 3.36.8) on an i7-8700K system with Intel 630 graphics for host (& lg client app) display and a GTX1080 GPU PCI attached to the client VM which uses spice not scream.

**Comment by netboy3** [comment]
Thank you. scream is an audio path solution and has nothing to do with spice. what are you using for audio path?

**Comment by Dave--G** [comment]
Audio is via a passthru PCI USB audio device.  Never was able to get other audio paths stable enough to reliably use - think it's a PulseAudio on Intel UHD/DisplayPort issue not anything looking-glass related though.

**Comment by netboy3** [comment]
Something is causing your ivshmem session to go corrupt. You may want to [join our Looking-Glass Discord](https://discord.gg/52SMupxkvt) server. Most users and all dev's are there and your issue will get a much better attention. The issue tracker in GitHub is pretty much a ghost town compared to Discord.

**Comment by Dave--G** [comment]
Thanks but as a developer myself who has worked for data brokers in the past I've seen how the sausage is made a little too vividly.  So I try to avoid filling in my social graph when avoidable.  And I try to avoid new distractions like social - to me the ROI isn't worth the productivity loss.

But I think you're right, there are other indications ivshmem is corrupting at times.  I'll look into it.  Feel free to close this bug or I'm happy to help here as I can.

**Comment by netboy3** [comment]
I'm just an active user that truly appreciate the product and try to assist others. The "support" channel on the Discord server is maintained in a similar spirit. I have never seen such an issue with other users. Unfortunately I do not have the ability to close issues on this repo. Gnif (the lead dev) have those powers. I hope you'll figure this out and if you change your mind, you're always welcome to ask in the support channel.

**Comment by gnif** [comment]
> Client segfault on start seen in previous 'latest' builds is resolved. +1
Great, but no idea what segfault you're referring to.

> Viewing VM guest using client, the mouse cursor displays as a single white pixel.

The cursor is intentionally a small white dot when the cursor is outside of the guest window. (ie, black edges, or showing the LG logo). If this is occurring when it should be showing a proper cursor, more information is needed on how to reproduce this.

> This pixel appears to trigger WM_MOUSEOVER events in the guest (mouse-over window highlights, etc) but windows don't appear to respond to right or left button click events.

Sounds like you left a tablet device attached to your VM.

> This may be trivial but there are nulls being output to the client log. Excerpt from the log:

Sounds like you have a hardware fault, LG just wraps `fprintf` for all prints and the lines where those nulls are there is no formatting as they are purely informational messages. The only way you could be getting nulls here is if you have some other issue with your system. I also just verified this on my two development systems, neither of which are writing nulls to the output. Overclocked RAM perhaps?

> So I try to avoid filling in my social graph when avoidable.

The LG Discord server is not a "social" server, it's devoted to supporting LG in real-time. We have an #off-topic channel for those that want to be social, but otherwise, it's used to diagnose and fix problems in real-time. You're more than welcome to leave again after you're issue(s) have been resolved.

If you do not wish to discuss your issues there, you can always join the L1 Forums where it's treated the same.
https://forum.level1techs.com/c/software/lookingGlass

**Comment by Dave--G** [comment]
This is just FYI, keep the bug closed:
I figured out at least part of the problem.  I start the client with:
looking-glass-client -F -S -p 5903 spice:captureOnStart=yes win:quickSplash=yes input:grabKeyboardOnFocus=no
hitting scroll-lock, the full cursor appears.  hitting it again properly goes into capture mode and everything works.
