### ISSUE TITLE
New X11 display still missing some init params

### ISSUE THREAD

**Issue by JJRcop** [gnif/LookingGlass#506]
[client/displayservers/X11/x11.c] is still missing the following functionality

`const LG_DSInitParams params =`
`{`

- [x] `    .center              = g_params.center,`
- [x] `    .resizable           = g_params.allowResize,`
- [x] `    .borderless          = g_params.borderless,`
- [x] `    .maximize            = g_params.maximize,`
- [x] `    .minimizeOnFocusLoss = g_params.minimizeOnFocusLoss,`

`};`

[client/displayservers/X11/x11.c]: https://github.com/gnif/LookingGlass/blob/a4290b290b76251b59298d954c851b3d715bd1eb/client/displayservers/X11/x11.c

**Comment by Moonlight63** [comment]
I have the same problem. Just updated to master, and my default launch script for maximized and borderless no longer works. Fullscreen also doesn't work, and setting size doesn't work.

**Comment by JJRcop** [comment]
Fullscreen is implemented in the new display, just broken on some desktop environments. This issue is about some functionality which is missing entirely. I recommend making a new issue for the fullscreen and size problems.

**Comment by JJRcop** [comment]
Repurposed issue for missing functionality

**Comment by Moonlight63** [comment]
Hmm, strange. well I don't use fullscreen mode myself, I prefer maximized borderless.....but it doesn't work! Hope this will be added back soon.

**Comment by gnif** [comment]
Thanks for this ToDo list @JJRcop  :)

**Comment by gnif** [comment]
This may be fixed by ab4d7cb, can you please verify?

**Comment by JJRcop** [comment]
@Moonlight63 Please try ab4d7cb94b like suggested for fullscreen and window size

**Comment by gnif** [comment]
Minimize on focus loss implemented for SDL and X11 as of 903cc9815f0d357d357d0518c76ac5f445899440, Wayland is pending the Wayland devs to add the code for this on their side.

**Comment by Krys88** [comment]
> Minimize on focus loss implemented for SDL and X11 as of [903cc98](https://github.com/gnif/LookingGlass/commit/903cc9815f0d357d357d0518c76ac5f445899440), Wayland is pending the Wayland devs to add the code for this on their side.

how to disable without rebuild? is there an option to disable this?

**Comment by JJRcop** [comment]
> how to disable without rebuild? is there an option to disable this?

Please check in `--help` for available options, you can see `win:minimizeOnFocusLoss`

**Comment by Krys88** [comment]
found it thnx allot
