### ISSUE TITLE
i3wm Capture issues

### ISSUE THREAD

**Issue by betstick** [gnif/LookingGlass#514]
Hi, I've updated to version B3 on the host and client. I'm running Arch Linux with Nvidia cards for both the host and the guest. Everything works perfectly except for the client window focus settings. I'm using the i3wm (more specifically the i3-gaps fork). This issue didn't happen on older versions. The release candidates were fine.  Also, I have to have input:grabKeyboardOnFocus=no otherwise I can't set fullscreen using my keyboard since the client eats all the inputs.

Here's one method to reproduce:
Launch client
Fullscreen (alt+f)
Move mouse out of the client window (to another monitor) then back in to the client window
Toggle capture on with Scrlk (does not work, mouse can leave the window), the "popup" shows that it should be locked

If I set input:grabKeyboard=yes, and do the above steps, the first capture toggle works, but after turning it off then on, it breaks.

Here's my output, no errors though:

178579386941 [I]               main.c:2282 | main                           | Looking Glass (a5194b94ac)
178579386965 [I]               main.c:2283 | main                           | Locking Method: Atomic
178579452011 [I]            ivshmem.c:127  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
178579470625 [I]                egl.c:214  | egl_initialize                 | Double buffering is off
178579470636 [I]               main.c:1655 | try_renderer                   | Using Renderer: EGL
178579470947 [I]                x11.c:104  | x11Init                        | X11 XInput 2.3 in use
178579496131 [I]                egl.c:538  | egl_render_startup             | Using eglGetPlatformDisplayEXT
178579503358 [I]                egl.c:568  | egl_render_startup             | Multisampling enabled, max samples: 4
178579512017 [I]                egl.c:619  | egl_render_startup             | Single buffer mode
178579546771 [I]                egl.c:635  | egl_render_startup             | EGL       : 1.5
178579546784 [I]                egl.c:636  | egl_render_startup             | Vendor    : NVIDIA Corporation
178579546786 [I]                egl.c:637  | egl_render_startup             | Renderer  : GeForce GTX 1070/PCIe/SSE2
178579546788 [I]                egl.c:638  | egl_render_startup             | Version   : OpenGL ES 3.2 NVIDIA 460.67
178579546793 [I]                egl.c:639  | egl_render_startup             | EGL APIs  : OpenGL_ES OpenGL
178579546798 [I]                egl.c:640  | egl_render_startup             | Extensions: EGL_EXT_buffer_age ETC ETC ETC
178579546809 [W]                egl.c:655  | egl_render_startup             | NVIDIA driver detected, ignoring broken DMA support
178579757187 [I]               main.c:2165 | lg_run                         | Host ready, reported version: B3
178579757199 [I]               main.c:2166 | lg_run                         | Starting session
178580022030 [I]               main.c:647  | frameThread                    | Format: FRAME_TYPE_BGRA 2560x1440 stride:2560 pitch:10240 rotation:0
^C178747907013 [I]               main.c:1620 | int_handler                    | Caught signal, shutting down...

**Comment by gnif** [comment]
ScrollLock+F doesnt work?

**Comment by betstick** [comment]
If I just hit ScrollLock+F, it goes fullscreen. From there, I can then press ScrollLock again and it will function the way that it used to where ScrollLock can toggle the lock. However, if the mouse leaves the client window while unlocked, the client will go back to being a regular sized window instead of being fullscreen. From there, to get it back to fullscreen and captured, I have to press ScrollLock+F twice, then ScrollLock. If I leave it in windowed mode it'll capture properly but not in fullscreen unless I do the previous combination.

**Comment by betstick** [comment]
Issue solved by building from master after commit 5bfb33c.
