### ISSUE TITLE
Mouse buttons 4 and 5 not working 

### ISSUE THREAD

**Issue by Synkstar** [gnif/LookingGlass#526]
I know its possible to get it to work by passing through the mouse too the vm directly but that removes the point of using looking glass if you have to like switch around. If anyone knows how to get them to work without evdev or usb passthrough with looking glass help would be greatly appreciated. Idk if you would have to implement this into looking glass or if it is something else I would have to do ?!? Thanks

**Comment by gnif** [comment]
Issues are for bug reports

https://github.com/gnif/LookingGlass#help-and-support
