### ISSUE TITLE
[client] Missing make dependencies Ubuntu

### ISSUE THREAD

**Issue by LoveMHz** [gnif/LookingGlass#54]
### Required information

Host CPU: NA
Host GPU: NA
Guest GPU: NA
Host Kernel version:  4.13.0-37-generic
Host QEMU version: NA

Hopefully this is the right place to report this, but the page _Building The Looking Glass Client from Source_ at 
https://looking-glass.hostfission.com/node/6 is missing two required dependencies libconfig-dev and libva-dev

**Comment by gnif** [comment]
Closing, you did not follow the instructions and build a tagged release.

**Comment by LoveMHz** [comment]
Where does it say to build a tagged release?

**Comment by gnif** [comment]
You are correct, I am sorry, it seems it was overlooked. I will correct the documentation to point people to a tagged release.
