### ISSUE TITLE
Rotations confuse and crash NvFBC capture

### ISSUE THREAD

**Issue by arcnmx** [gnif/LookingGlass#555]
Mixing NvFBC with a portrait rotation causes an endless crash loop in the host application, and no frames ever get through. I'm currently investigating / digging into it / trying to get logs, but am assuming it's trivially reproducible and that it's some mismatch between the capture vs monitor width/height. DXGI on the other hand seems to handle the rotation fine.

The host logs also claim that the capture frame size (and required ivshmem size) is significantly higher than what's normally reported when in landscape mode, possibly a sign that the frame stride size is wrong?

**Comment by gnif** [comment]
NvFBC rotation support was never tested or planned to be implemented as NvFBC has been deprecated by NVidia.

**Comment by arcnmx** [comment]
Oh, well I get very glitchy artifacting when using DXGI capture so am kinda stuck with it, guess I'll figure out how to fix it eventually :<

**Comment by gnif** [comment]
If you do find a solution feel free to make a PR to address the issue, however, please note that NvFBC support will be removed from LG at some point in the future when nvidia removes it from their drivers also.
