### ISSUE TITLE
Freezes when windows guest requires administrator privileges

### ISSUE THREAD

**Issue by Brickchef** [gnif/LookingGlass#56]
Host CPU: Intel Core i7-7700k @ 8x 4.5Ghz
Host GPU: GeForce GTX 1050
Guest GPU: GeForce GTX 1080
Host Kernel version:  x86_64 Linux 4.15.13-1-vfio (ACS override patch as explained in the arch wiki)
Host QEMU version: 2.11.1

When I try to install or uninstall a program on my Windows 10 guest, the looking-glass freezes in a black screen for about 1 minute. After that everything workes fine again. 
If I try the same thing while accessing the VM via virtmanager GUI, it works without problems.
The priority of the looking-glass-host is set to real-time.

Edit: This seems to happen everytime windows asks for administrator privileges.

I am using the latest version of the guest driver and the looking-glass-host.
The looking-glass-client comes from the AUR (https://aur.archlinux.org/packages/looking-glass/) and is started as follows: "looking-glass-client -s -w 1920 -b 1080 -k".

**Comment by gnif** [comment]
The secure desktop (UAC) is protected from being captured or interacted with. The host program does not freeze, it waits for the prompt to be answered. This is a known limitation and is not fixable.

**Comment by Programming4life** [comment]
You can use ALT+Y or ALT+N, and ENTER to get past it.
