### ISSUE TITLE
Feature request: auto-adapting resolution to the window size.

### ISSUE THREAD

**Issue by perHub** [gnif/LookingGlass#567]
Hello, I'd like to request an equivalent feature to the "Auto resize VM to window" under View->Scale Display in Virtual Manager which automatically adapts the VM resolution based on the window size. I'm aware this is probably a very-low priority thing to do but it would be nice to show the desktop without scaling it.

Now I'm thinking about it, it's actually pretty different from Virtual Manager since it manipulates the (for example) QXL display driver and, for this case, it would need to change the passed-though GPU resolution, although it's only a matter of using the OS API on the client side to do so (Windows in my case).

Would this be possible to implemented in the future?

**Comment by gnif** [comment]
It is possible but requires an enormous amount of work. Unless sponsorship covers my time to re-write the host application as an IDD this will not happen. Please see the goals here: https://github.com/sponsors/gnif
