### ISSUE TITLE
Does not compile on musl 

### ISSUE THREAD

**Issue by Ocean-Moist** [gnif/LookingGlass#568]
So the client will not compile on musl systems (alpine, void, etc).

I get this error:

```
/bin/ld: common/src/platform/linux/liblg_common_platform_code.a(crash.c.o): in function `printBacktrace':
crash.c:(.text.printBacktrace+0x33): undefined reference to `backtrace'
/bin/ld: crash.c:(.text.printBacktrace+0x50): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/looking-glass-client.dir/build.make:299: looking-glass-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:319: CMakeFiles/looking-glass-client.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

essentially ```printBacktrace``` in crash.c will not work because musl does not include the backtrace function or execinfo.h. 

Solution:

use a third party library like [libunwind](https://www.nongnu.org/libunwind/docs.html) or [libbacktrace](https://github.com/ianlancetaylor/libbacktrace) if the build system uses musl.

**Comment by quantum5** [comment]
I think the easiest solution is to just pass `-DENABLE_BACKTRACE=no` to `cmake`.

**Comment by Ocean-Moist** [comment]
Yes, but that is temporary. Backtrace would be a nice feature to work on all platforms.

**Comment by gnif** [comment]
If you wish to make a PR to use another compatible method you're welcome, we are however not interested at this point in directly supporting nonmainstream distros or variants of libc.
