### ISSUE TITLE
Feature Request: Support Hyper-V GPU partitioning use cases

### ISSUE THREAD

**Issue by andrewklamut** [gnif/LookingGlass#569]
I am looking to get a setup working perfectly using more or less the setup described here:

https://forum.level1techs.com/t/2-gamers-1-gpu-with-hyper-v-gpu-p-gpu-partitioning-finally-made-possible-with-hyperv/172234

Specifically, on my Windows gaming PC I want to run games in a local Windows VM. Using Set-VM and Set-VMGpuPartitionAdapter Powershell functions, it is very close to being possible. The issue is that I can't find a suitable streaming app to do it. Parsec comes the closest, but it still ends up looking blurry even though the VM is happily running max settings.

I'm not interested at all in the multi-client cases that Parsec supports, I just want high performance so that I can run certain games sandboxed on my own local VM. Parsec's image ends up looking blurry either because of the fact that it is using compression or doesn't play nicely with the GPU partitioning method. It seems like Looking Glass could be perfect for this use case since it is made for GPU passthrough.

I tried installing the windows host client on a GPU partitioned VM but it doesn't start due to "Failed to find the IVSHMEM device". It doesn't seem like you guys have a Windows client either. Anyway, I thought it wouldn't hurt to ask!

Thanks

**Comment by gnif** [comment]
Issues are for bug reports... use the advertised support channels if you have questions.
