### ISSUE TITLE
obs plugin: make install installs to wrong directory

### ISSUE THREAD

**Issue by babbaj** [gnif/LookingGlass#575]
`make install` will install to `share/obs/obs-plugins/` but the correct directory for plugin binaries is `lib/obs-plugins/`

**Comment by gnif** [comment]
Not for debian/ubuntu which is our target distro.

**Comment by babbaj** [comment]
Does OBS have this documented anywhere?

**Comment by gnif** [comment]
We are not particularly concerned about this, package maintainers will create a package for this plugin and install it into the correct location on the target distro, wherever that might be.

**Comment by babbaj** [comment]
It's not a problem but it does make it slightly more complicated to package for nix than every other plugin

**Comment by gnif** [comment]
Not sure how since the maintainer can simply set `CMAKE_INSTALL_DATADIR` to the location that best suits their distro.

**Comment by babbaj** [comment]
The cmake script also adds `${CMAKE_PROJECT_NAME}/bin/${OBS_PLUGIN_DIR}` the to `CMAKE_INSTALL_DIR` so just changing that probably wouldnt work but I haven't actually tried.
