### ISSUE TITLE
Host(windows) cursor not vissable / blinking 60% of the time (spice disabled)

### ISSUE THREAD

**Issue by FieryRider** [gnif/LookingGlass#578]
I use Windows as a host (in VM) and Linux as client of course.
**The problem is that Windows cursor is constantly blinking and is probably visible only like 40% of the time (through LG)** which is really annoying and barely usable.
* for mouse (and keyboard) input I use `evdev` because I find it the best solution for gaming apart from passing through another usb mouse and kb .
* `spice` is disabled (both in VM and LG) because I use `evdev` for input as mentioned. And I don't need it for display.
* I have `vnc server` enabled in the VM's config because I need to connect to it sometimes.

**The passed through GPU is Nvidia GTX 970**.
I'm currently using `B3` version on Windows and Linux.

**`.looking-glass-client.ini`**
```ini
[win]
botderless=yes
fullScreen=yes
position=1920x0
size=1920x1080
fpsLimit=60
noScreensaver=yes
[input]
hideCursor=no
[spice]
enable=no
alwaysShowCursor=yes
[opengl]
vsync=no

```
_I haven't had this problem before with old versions of LG. I haven't used LG since 2019 (`B1` maybe?) so I cannot tell when this thing started happening. And I can't build an old version to test because the build tools cannot build them anymore._

**Comment by netboy3** [comment]
@FieryRider,

As clearly stated on the projects web page, github issues are used solely for reporting bugs and not problems related to general support. You are welcome to contact the community support groups on:

- Discord: https://discord.com/invite/52SMupxkvt
- LG Forum: https://forum.level1techs.com/c/software/lookingglass/142
- IRC: #LookingGlass on [Libera IRC network](https://web.libera.chat/)

The discord community is very lively and has many seasoned users that are happy to assist.
