### ISSUE TITLE
Windows Xbox Game Bar not displayed

### ISSUE THREAD

**Issue by bang4562** [gnif/LookingGlass#589]
I do not know if this is a bug or lacking feature. However, when using looking glass I would notice that when attempting to activate game bar it would cause no response or display of the overlay, besides the misplacement of my mouse (a telltale sign that the overlay was activated). However when switching directly to the gpu input on my monitor Game Bar would be displayed on screen.

**Comment by 8BallBomBom** [comment]
https://github.com/gnif/LookingGlass/issues/290
Known issue with DXGI.

**Comment by gnif** [comment]
Nothing we can do sorry, Microsoft needs to fix their Capture API.

**Comment by bang4562** [comment]
Thank you for the help, I am going to write an angry letter to Microsoft.
