### ISSUE TITLE
Host application crashes when DPI is 150%

### ISSUE THREAD

**Issue by slis** [gnif/LookingGlass#6]
./looking-glass-client -s
[I] main.c:560 | run | Looking Glass (a3-2-g973ad5e2b0)
[I] main.c:636 | run | Initialized OpenGL
[I] ivshmem.c:153 | ivshmem_connect | RAM Size : 16777216
[I] main.c:762 | run | Waiting for host to signal it’s ready…
[I] main.c:766 | run | Host ready, starting session

On host with -f, crash:

Service.cpp:270 Cursor shape size exceeds buffer size

Changing DPI to 100% it works.

**Comment by slis** [comment]
It also crashes with dota2 for same reason.

**Comment by gnif** [comment]
@slis is it the same error?

**Comment by slis** [comment]
@gnif yes

**Comment by gnif** [comment]
Fixed by:
110aced7d154944e294a3b732de02277c63d95d9
8ae9f8464b37f72ebcaa78d7c02c884068786ce5
0948dda12f51f7fdfa78aaaf7209806939f39adb
