### ISSUE TITLE
VM freeze on connection (?!)

### ISSUE THREAD

**Issue by HoshiYamazaki** [gnif/LookingGlass#60]
### Required information

Host CPU: i5-6600
Host GPU: hd530 1gB
Guest GPU: rx480 4gB
Host Kernel version: 4.16.5-1-ARCH
Host QEMU version: /usr/bin/qemu-system-x86_64 --version

My log:
https://i.imgur.com/RjuVzUt.png
When I try to connect via Looking Glass client, system just freeze and I must restart Windows VM and there is no other way to get rid of it. I tried like multiple methods to fix that, I even compiled newest client or tried to tweak spice and nothing works.
https://i.imgur.com/9EW3kyK.png //It even sometimes works for like 2-4 seconds, I can move mouse and freeze. In that moment I can't even close looking-class-cient properly and I must xkill it.

**Comment by gnif** [comment]
Please post your log into this ticket, do not use services like imgur.

**Comment by HoshiYamazaki** [comment]
Someone on reddit said:  
`Mesa 18 bug, downgrade to 17.3.7 or use`
Solution:  
`-o opengl:preventBuffer=0`
