### ISSUE TITLE
Cursor does not update its shape in the game NosTale

### ISSUE THREAD

**Issue by HoshiYamazaki** [gnif/LookingGlass#61]
As title says, it basically stays mostly as Windows default cursor and it does not change in games.

**Comment by HoshiYamazaki** [comment]
Since my english is horrible, I will explain it different way.
See these photos.
In monitor plugged into GPU:
![GPU](https://cdn.discordapp.com/attachments/244187921228234762/442840724443234314/IMG_20180507_020943.jpg)
In Looking Glass:
![LG](https://media.discordapp.net/attachments/244187921228234762/442840843703812109/IMG_20180507_020935.jpg?width=495&height=663)

**Comment by gnif** [comment]
What game this this?

**Comment by polarathene** [comment]
The issue could depend on how looking glass is being used. @HoshiYamazaki just compares with a monitor plugged in and the other image just says with looking glass. Is the monitor still plugged in?

My 1070 can display a desktop without any inputs into the GPU, but will fail to render some things like the Unigine Heaven benchmark, and I've noticed the mouse to behave/render differently than if I have a monitor or edid dummy plug connected(At least with my client and the way I handle mouse).

If the GPU has an input connected(Display or dummy plug), then nevermind. Just something I've noticed in the past myself.

**Comment by gnif** [comment]
@polarathene It should not matter, the capture API provides the mouse shape and positional information, we literally draw the cursor over the captured frame in the client, so it is likely there is a problem here.

**Comment by gnif** [comment]
Confirmed, I can reproduce this, investigating.

**Comment by gnif** [comment]
This is now fixed
