### ISSUE TITLE
Looking Glass host application erroring out when fullscreening game or changing resolution

### ISSUE THREAD

**Issue by Celmor** [gnif/LookingGlass#62]
### Required information

Host CPU: Intel i7-6700K
Host GPU:  Intel HD Graphics 530 
Guest GPU: GTX 980 Ti
Host Kernel version: 4.16.4-1-MANJARO
Host QEMU version: 2.11.1
Guest Windows version: Windows 10 RS3/1709

Changing ingame resolution dramatically (e.g. 720p->1440p), starting game with different ingame resolution than desktop, alt-tabbing out of game or into game can cause Host error and prompt to exit, refer to the corresponding log file for console output and see for its file name name for a short sumarry of what I did. Either way the issue can't be reproduced reliably.
For example:

- Changing ingame resolution causes DXGI's DuplicateOutput to produce error 80070005 and Clients video freezes but spice keeps working
- switching Monitor input to guest GPU to see its desktop
- closing looking-glass-host (or in my case creating dump file via task manager first)
- starting looking-glass-host
- alt-tabbing back to game
- switching monitor input to host
- noticing looking-glass-host errored again
- switching monitor input to guest GPU to see its desktop
- starting looking-glass-host
- alt-tabbing back to game
- switching monitor input to host
- this time no error

I couldn't isolate what causes looking-glass-host/capturer to error and fullscreening a game is a gamble for if LG will correspond badly or continue working. Changing just desktop resolution doesn't cause this issue. Desktop resolution and refresh rate is usually lower than ingame's setting then when switching to Game it often causes this issue but not exclusively.
Games I tested with are GTA5 and Rainbow Six Siege.

**Comment by Celmor** [comment]
Logs/Dumps hosted in this Cloud Drive folder:
https://mega.nz/#F!4p0hWJZD!rzjzSmtLs20Oiqb6bDrS8w

**Comment by gnif** [comment]
I have been trying to replicate this using GTA5 and I can't generate a fault. Can you please give at least one exact resolution switch (including refresh) that causes the crash.

**Comment by gnif** [comment]
Right now I don't have a setup I can open these dumps in, but when I find some time I will get onto this one. Thanks for the detailed information.

**Comment by Celmor** [comment]
Reproduced issue on a new installation of Windows 10 with Redstone 4 update (1803). Dump and log are uploaded to same cloud directory but tagged accordingly.

**Comment by Celmor** [comment]
My current workaround is to have the host application restart automatically when exit code is 0 (which it does when the capturer exits), exit code is 1 if killed via task manager.
> Do { echo "lookin glass started"; $ps = Start-Process D:\tools\looking-glass-host.exe -Wait -PassThru } While ($ps.ExitCode -eq 0)

**Comment by gnif** [comment]
This is likely fixed as of b23c780

**Comment by gnif** [comment]
Closing as this has seen no updates, assuming fixed

**Comment by 8BallBomBom** [comment]
I had the changing resolution crash recently.
Seems if i change from 1440x900@75hz down to 1366x768@60hz then the host app crashes/ refuses to start again.

**Comment by gnif** [comment]
Is this on the latest master?

**Comment by 8BallBomBom** [comment]
Yeah.
How would i go about error log collecting?

**Comment by 8BallBomBom** [comment]
No worries, will do that now :)
