### ISSUE TITLE
Sluggish performance when playing games (advice needed)

### ISSUE THREAD

**Issue by Nexolight** [gnif/LookingGlass#63]
### Required Informations:
Host CPU: Ryzen 7 1800x
Host GPU: GTX 1080 (1 out of 2)
Guest GPU: GTX 1080 (1 out of 2)
Host Kernel version: 4.14.35_1
Host QEMU version: 2.11.1

### Additional Informations:
RAM: 4x F4-3300C14-8GTZR, Dual Channel, Unbuffered, 3066 MT/s
LookingGlass version: a10
Xorg version: 1.19.6
Distro: Void Linux (minimalistic, leading edge, rolling release one)
WM: cinnamon
Host GPU driver: Proprietary Nvidia with 2 Monitors in Mosaic mode.
CPU Governor; Performance

### Problem
Altough the Framerates are high, The displayed image is sluggish from time to time. Not exactly microstutter (less abrupt) but similar. This is only the case while gaming or maybe it's just the only situation where I notice it.

I ended up switching to the other Display Input where it runs smooth while the LookingGlass client runs in the background.

I previously build some packages on the same distro for qubes which uses a similar technique (via RAM) which required me to enable the CONFIG_TRANSPARENT_HUGEPAGE_MADVISE kernel option on the client (which was linux but anyway). Otherwise it crashed. Maybe it's related. It's disabled on the host of my current system.

**Comment by gnif** [comment]
It sounds like you're hitting memory bandwidth limits, perhaps the game/program is saturating the PCIe bus when LG needs to also grab the frame. Native (with the monitor) will always be smooth as there is no additional memory copy required.

**Comment by Nexolight** [comment]
The memory should be pretty fast. I could try to lower the timings and maybe bring it up to 3200. 

The PCIe bus has only 8 lanes. Can't do 16 each with a Ryzen 1800x on my board. But in this case wouldn't it be noticeable on the monitor as well? Note that I'm running the LG client in the background for the keyboard while I'm using the monitor directly.

How could I determine which one the problem is? For ram I could maybe do something about it.

**Comment by gnif** [comment]
It is not something you can address, it is a limitation of this method of frame copy. You might improve things a little but if the game you are using is heavy on streaming texture loads it will need that bandwidth just as much as Looking Glass does. Perhaps reduce your texture quality or turn of AA.

**Comment by YvanDaSilva** [comment]
@gnif Do you know if there is a way to monitor that bandwidth ?
I guess you know how much LG is using, but I also guess, it would be hard to get the guest os drivers/Api to tell you how much is currently in use.

That would be a nice information to provide tough, and interesting for stats.

**Comment by gnif** [comment]
There is no way to monitor PCI bus bandwidth without specialized hardware.

**Comment by YvanDaSilva** [comment]
We live in a sad world :D lol.
Thanks anyway @gnif

**Comment by gnif** [comment]
I have increased the maximum buffered textures in the client with the new work for AMD performance improvements, this may help smooth things out a bit.

**Comment by Nexolight** [comment]
I will definitely try it as soon as possible.
