### ISSUE TITLE
extrem mouse stuttering and input lag when catching mouse

### ISSUE THREAD

**Issue by caHocke** [gnif/LookingGlass#64]
As soon as I catch the courser, the mouse movement stops for some seconds, then stutters heavily.

This error gets printed:

>[E]              spice.c:826  | spice_mouse_motion             | mouse motion ringbuffer full!
>[E]               main.c:567  | eventThread                            | SDL_MOUSEMOTION: failed to send message

I tried differnent sizes for:
> #define SPICE_MOUSE_QUEUE_SIZE 32

setting higher values stopped the mouse movement for a longer time, then prints the error and stutters

setting lower values let the error occur sooner 

I use a10.
I also tried building the latest commit but the libraries on Debian are to outdated.
Looking-glass worked nearly flawlessly on my Arch installation.

### Required information

Host CPU: Intel Core i7-4770 CPU @ 3.9GHz
Host GPU: Mesa DRI Intel(R) Haswell Desktop
Guest GPU: NVIDIA GeForce 780ti
Host Kernel version: x86_64 Linux 4.9.0-6-amd64
Host QEMU version: version 2.8.1(Debian 1:2.8+dfsg-6+deb9u3)

**Comment by gnif** [comment]
This is due to a QEMU bug, please see:

http://patreon.com/posts/18658431
