### ISSUE TITLE
Spice over methods other than tcp/ip

### ISSUE THREAD

**Issue by cmdrkotori** [gnif/LookingGlass#67]
### Required information

Host CPU: AMD FX(tm)-8320 Eight-Core Processor
Host GPU: [AMD/ATI] Curacao XT / Trinidad XT [Radeon R7 370 / R9 270X/370X]
Guest GPU: [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E]
Host Kernel version: 4.16.8
Host QEMU version: QEMU emulator version 2.12.0

Accepting other methods has two benefits:

From a security perspective, letting a TCP server run without any form of authentication is a huge security risk, because visiting any website could run commands on your computer or crash your system by contacting the TCP socket.

From a speed perspective, the alternatives are simply faster. Unix sockets have less overhead than a tcp socket on a localhost address and implementing them should be only a few lines of code.
From https://blog.myhro.info/2017/01/how-fast-are-unix-domain-sockets

>The Unix socket implementation can send and receive more than twice the number of messages, over the course of a second, when compared to the IP one.

Fwiw, my system currently reports latency of around 20-50ms depending upon load when looking-glass is started.

Conceptually, the fastest method would be shovelling the data over ivshmem as well. But this is an avoidable increase in complexity when qemu is already capable of controlling the guest, so I wouldn't at all expect this to happen from a maintainability perspective just yet.

Cheers.

**Comment by gnif** [comment]
> From a security perspective, letting a TCP server run without any form of authentication is a huge security risk, because visiting any website could run commands on your computer or crash your system by contacting the TCP socket.

If you only bind to 127.0.0.1 this is a non issue. At this time LG is not about security but performance, the IVSHMEM interface itself is a huge hole in the VM's security model.

> From a speed perspective, the alternatives are simply faster. Unix sockets have less overhead than a tcp socket on a localhost address and implementing them should be only a few lines of code.

We are well aware, priority has not been on the spice protocol but rather the video interface, patches are welcome for this.

> Conceptually, the fastest method would be shovelling the data over ivshmem as well. But this is an avoidable increase in complexity when qemu is already capable of controlling the guest, so I wouldn't at all expect this to happen from a maintainability perspective just yet.

Actually it is not, as this would involve having to patch/hook the guest and inject mouse and keyboard events (see synergy's source), which is not only very hacky but a nightmare to maintain when we already have a solution that is far superior, hardware emulation.
