### ISSUE TITLE
License issues with Looking Glass

### ISSUE THREAD

**Issue by lhw** [gnif/LookingGlass#68]
After a pleasent experience getting this to run on debian I thought i might as well just package it. But there are some issues:
As it is right now technically Looking Glass can't be redistributed by distributions (looking at you Arch) or in any form really. With the software being licensed as GPL and the client linking against OpenSSL you run into the common licensing issue between the two. As they are not compatible without granting an exception.
Check out https://people.gnome.org/~markmc/openssl-and-the-gpl.html & https://lists.debian.org/debian-legal/2004/05/msg00595.html
You can simply add an exception to the current licensing, solving the issue.

Another licensing issue is the use of the vendor/getopt files. These don't really affect me and the debian packaging but also cause the host application to be impossible to be redistributed as the BSD-4-clause of the old minix project and GPL clash https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_"BSD_License")
This isn't really an issue though as you can just replace the getopt files with the current ones from the minix project which have been in public domain for quite a while. (https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/master/usr.bin/getopt/getopt.c)

**Comment by gnif** [comment]
Re OpenSSL, I was unaware of this issue, I will add the exception clause for now but ultimately I would like to correct it properly.

As for `getopt` I will look into this later, thanks for the heads up. The link you provided is the usage of the function, not the actual function.

**Comment by lhw** [comment]
The OpenSSL issue is really prevalent. And also the reason GnuTLS was written. But it's generally not an issue to just add the exception. We even have a shortcut for that specific license combination in the debian/copyright.

And yea sorry. meant to link you to the libc part of course: https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/master/lib/libc/stdlib/getopt.c Which you will note is almost identically. Except for the fourth clause in the license.
