### ISSUE TITLE
A lot of rendering bugs, and I cannot disable vsync

### ISSUE THREAD

**Issue by Perdouille** [gnif/LookingGlass#7]
Hello ! Thanks a lot for this amazing piece of software. It's really awesome.

I'm trying to make it work, and I get a lot of graphics bugs (Really fast blinking, half the screen black, ...). Is there anything to do ? I don't see anything in the logs

> lou@5820k_Arch ~ % looking-glass-client -m -s
[I]               main.c:560  | run                            | Looking Glass (a3-3-gcd54cb179b)
[I]               main.c:636  | run                            | Initialized OpenGL
[I]            ivshmem.c:153  | ivshmem_connect                | RAM Size : 67108864
[I]               main.c:762  | run                            | Waiting for host to signal it's ready...
[I]               main.c:766  | run                            | Host ready, starting session
[I]               main.c:235  | renderThread                   | Data Format: w=1920, h=1080, s=1920, p=7680, bpp=32
[I]             opengl.c:159  | lgr_opengl_configure           | Vendor  : NVIDIA Corporation
[I]             opengl.c:160  | lgr_opengl_configure           | Renderer: GeForce GTX 770/PCIe/SSE2
[I]             opengl.c:161  | lgr_opengl_configure           | Version : 4.6.0 NVIDIA 387.34

If I try to start looking-glass-client with -v, I'm getting an error saying v is an invalid option.

I installed everything from AUR. My GPU is a 770, and my Windows GPU is a 1080

Also, do you know if 144hz is working ? 

Thanks again

**Comment by gnif** [comment]
This question has been answered in the support forum, please don't open issues for general support requests, it's not what they are for.

**Comment by Perdouille** [comment]
Sorry, I didn't notice the support forum :(

Thanks !
