### ISSUE TITLE
Missing VCRedist2015 package causes host application to error

### ISSUE THREAD

**Issue by Celmor** [gnif/LookingGlass#70]
### Required information
Host CPU: Intel i7-6700K
Host GPU:  Intel HD Graphics 530 
Guest GPU: GTX 980 Ti
Host Kernel version: 4.16.4-1-MANJARO
Host QEMU version: 2.11.1
Guest Windows version: Windows 10 RS4/1803

## Issue
After a fresh install of Windows 10 Looking glass cannot run because of following _System Errors_:
> The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix the problem.

![systemerror missing-vcredit2015 vcruntime140 code_execution_cannot_proceed d2018-05-28](https://user-images.githubusercontent.com/9097551/40619287-c351d96c-6294-11e8-945e-0b2dc95ed879.png)
and 
> The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix the problem.

![systemerror missing-vcredit2015 msvcp140 code_execution_cannot_proceed d2018-05-28](https://user-images.githubusercontent.com/9097551/40619333-fcf9efb0-6294-11e8-94e3-c13eda4483d5.png)

## Solution
After downloading and installing of [Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026](https://www.microsoft.com/en-us/download/details.aspx?id=48145) the problem was fixed and looking-glass-host executable run fine. Uninstalling this package again confirms that this is indeed the change that fixed this issue.

## Recommendation
**Document** the _Microsoft Visual C++ 2015 Redistributable (x64)_ dependency.

**Comment by gnif** [comment]
Thanks for confirming this, documented in the "READ ME FIRST" [here](https://looking-glass.hostfission.com/node/7)
