### ISSUE TITLE
Cannot build a11

### ISSUE THREAD

**Issue by rmb938** [gnif/LookingGlass#72]
### Required information

Host CPU: Ryzen 2700x
Host GPU: AMD 580 8GB
Guest GPU: Nvidia 1080
Host Kernel version: 4.16.11-300.fc28.x86_64
Host QEMU version: 2.11.1

I cannot seem to build a11 it errors with the following logs:

```
Package nettle was not found in the pkg-config search path.
Perhaps you should add the directory containing `nettle.pc'
to the PKG_CONFIG_PATH environment variable
Package 'nettle', required by 'virtual:world', not found
Package 'hogweed', required by 'virtual:world', not found
cc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -Wfatal-errors -D USE_NETTLE  -DBUILD_VERSION='"a11-0-g97749b335a"' -o .build/main.o main.c
Package nettle was not found in the pkg-config search path.
Perhaps you should add the directory containing `nettle.pc'
to the PKG_CONFIG_PATH environment variable
Package 'nettle', required by 'virtual:world', not found
Package 'hogweed', required by 'virtual:world', not found
cc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -Wfatal-errors -D USE_NETTLE  -DBUILD_VERSION='"a11-0-g97749b335a"' -o .build/spice/rsa.o spice/rsa.c
spice/rsa.c:23:10: fatal error: spice/protocol.h: No such file or directory
 #include <spice/protocol.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:46: .build/spice/rsa.o] Error 1
```

However building a10 works perfectly fine:

```
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/libdrm -I/usr/include/spice-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid  -DBUILD_VERSION='"a10-0-g59fa025292-dirty"' -o .build/spice/spice.o spice/spice.c
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/libdrm -I/usr/include/spice-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid  -DBUILD_VERSION='"a10-0-g59fa025292-dirty"' -o .build/renderers/opengl.o renderers/opengl.c
gcc -o bin/looking-glass-client .build/main.o .build/lg-renderer.o .build/spice/spice.o .build/renderers/opengl.o -lrt -Wl,--gc-sections -lSDL2_ttf -lSDL2 -lGLU -lGL -lssl -lcrypto -lfontconfig -lfreetype -lX11 
```

Any ideas?

**Comment by rmb938** [comment]
Actaully nevermind. Forgot to install nettle-devel

**Comment by marcosscriven** [comment]
Just to add, on Ubuntu Xenial at least, the package needed is `nettle-dev`. Suggest updating package list at https://looking-glass.hostfission.com/quickstart/linux/build

**Comment by gnif** [comment]
You are not building A11, you built the latest from master. A11 has no dependency on nettle.

**Comment by wildtruc** [comment]
I tried to compile on Fedora 27. I've fix main.c, rsa.c and spice.c to spice proper path in include, but process terminated on error/warning on spiceThread main.c line.

Any idea?

(output is in french, sorry for that)
``
cc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -Wfatal-errors -D USE_NETTLE -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/libdrm -I/usr/include/spice-1 -I/usr/include/freetype2 -I/usr/include/libpng16  -DBUILD_VERSION='""' -o .build/main.o main.c
main.c: Dans la fonction « spiceThread »:
main.c:411:10: error: déclaration implicite de la fonction « spice_process »; vouliez-vous utiliser « spiceThread » ? [-Werror=implicit-function-declaration]
     if (!spice_process())
          ^~~~~~~~~~~~~
          spiceThread
compilation terminée en raison de -Wfatal-errors.
``

**Comment by gnif** [comment]
Don't ask questions here. This is well documented.
