### ISSUE TITLE
Feature request: Absolute mouse positioning

### ISSUE THREAD

**Issue by ShoelaceMan** [gnif/LookingGlass#73]
Hey,

I'm not sure how to word this properly, so it might get a bit confusing, but I've seen in the IRC channel that you prefer relative mouse positioning (for an understandable reason). However, can a feature of absolute positioning at least be added as a non-default argument? If the mouse in the guest moves for any reason, the host and guest cursors are no longer aligned (This means window snapping, evdev, passed through USB devices, etc. For example, right click the start button with the host cursor shown, the cursors will become slightly out of sync.) In cases of the two cursors being largely out of sync, looking glass is nearly unusable. I read that absolute positioning was "No longer needed" with a11, but I noticed immediately that this wasn't the case. I can't seem to get the guest cursor to snap to the edge of the screen that the window was entered on, but even if it did snap to the edge, the cursor could still become out of sync if the cursor snaps, which happens a lot since I have windows warp the cursor to the default button for all new windows.

**Comment by gnif** [comment]
This has already been answered and if you saw the conversation in IRC you would have noted that I stated it is NOT possible to swap between due to the way that Spice and Qemu is designed.
