### ISSUE TITLE
A11 kills compositor in kde plasma

### ISSUE THREAD

**Issue by ambershark-mike** [gnif/LookingGlass#78]
```

                   -`                    mike@megatron
                  .o+`                   -------------
                 `ooo/                   OS: Arch Linux x86_64                                                  
                `+oooo:                  Host: MS-7885 3.0                                                      
               `+oooooo:                 Kernel: 4.16.13-2-ARCH                                                 
               -+oooooo+:                Uptime: 25 mins
             `/:-:++oooo+:               Packages: 1371
            `/++++/+++++++:              Shell: bash 4.4.23                                                     
           `/++++++++++++++:             Resolution: 3840x2160                                                  
          `/+++ooooooooooooo/`           DE: KDE
         ./ooosssso++osssssso+`          WM: KWin
        .oossssso-````/ossssss+`         WM Theme: Oxygen                                                       
       -osssssso.      :ssssssso.        Theme: Breeze [KDE], Breeze [GTK2/3]                                   
      :osssssss/        osssso+++.       Icons: Breeze [KDE], Breeze [GTK2/3]                                   
     /ossssssss/        +ssssooo/-       Terminal: tmux
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-5820K (12) @ 3.800GHz                                    
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 1050 Ti                                        
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 970                                            
 .`                                 `/   Memory: 11617MiB / 32128MiB                                            

```
Host QEMU version: qemu 2.12.0-1

When opening looking-glass-client in KDE plasma (5.12.5-1) my compositor shuts off.  Any window with transparency goes opaque (show in the attached screenshots) and all advance compositing like cover flow alt+tab, desktop change effects, etc all turn off and revert to basic switcher, etc.

As soon as looking glass is closed everything comes back on.

A10 doesn't do this if that helps track down the change.  Let me know if I can provide any more information.

![screenshot_20180606_222647](https://user-images.githubusercontent.com/20294359/41080085-9cef5dfc-69d9-11e8-87da-76264bbbb74a.png)
![screenshot_20180606_222739](https://user-images.githubusercontent.com/20294359/41080086-9d0d3746-69d9-11e8-8159-e38ed176fdd5.png)

**Comment by ambershark-mike** [comment]
I reverted to A10 and tested again and it is doing the same thing.  So I either didn't notice it before or it's something else.  Leaving this open for now just in case someone knows what is causing it.  But it doesn't seem limited to A11.

**Comment by ambershark-mike** [comment]
Ok so I'm just going to chalk this up to Plasma's horrible compositor.  Even though it gets disabled when looking glass launches I can just re-enable it with a hotkey.  Closing this.

**Comment by cmdrkotori** [comment]
This is by design. Kwin can be told to ignore the window hint by unchecking the allow applications to disable compositing checkbox in system settings. This is in the screen where you select what backend kwin should use (xrender,gl2,gl3), I think it is under desktop behaviour or screen. I would post a screenshot but I'm on my phone.
