### ISSUE TITLE
Add Documentation for Vuln Disclosure

### ISSUE THREAD

**Issue by Dynamic-Gravity** [gnif/LookingGlass#79]
Proposition: Add a [security.txt](https://securitytxt.org/), to provide a transparent and easy way for any private disclosure of security vulnerabilities.

The current draft is for websites, but I think it would still be a good idea to incorporate its essence given the sensitive nature of this application.

**Comment by gnif** [comment]
At this point this project is not production ready, it is not even beta ready and the code is in an extreme state of flux. The idea is good but IMO it is premature.

**Comment by Dynamic-Gravity** [comment]
@gnif thanks for the feedback. I understand the application is still far from ready, I just felt like laying out the ground work.

**Comment by antoinet** [comment]
@gnif what's the best way to report a security vulnerability?

**Comment by gnif** [comment]
For the moment, best way would be to email me directly: geoff@hostfission.com
