### ISSUE TITLE
Triangle visible on upper right corner

### ISSUE THREAD

**Issue by Morvs** [gnif/LookingGlass#8]
looking-glass-client -s -M -k
[I]               main.c:560  | run                            | Looking Glass (a3-3-gcd54cb179b)
[I]               main.c:636  | run                            | Initialized OpenGL
[I]            ivshmem.c:153  | ivshmem_connect                | RAM Size : 67108864
[I]               main.c:762  | run                            | Waiting for host to signal it's ready...
[I]               main.c:766  | run                            | Host ready, starting session
[I]               main.c:235  | renderThread                   | Data Format: w=2560, h=1440, s=2560, p=10240, bpp=32
[I]             opengl.c:159  | lgr_opengl_configure           | Vendor  : X.Org
[I]             opengl.c:160  | lgr_opengl_configure           | Renderer: Radeon RX 550 Series (AMD POLARIS12 / DRM 3.18.0 / 4.13.12-1-vfio, LLVM 5.0.0)
[I]             opengl.c:161  | lgr_opengl_configure           | Version : 3.0 Mesa 17.2.6
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 204 (196), X11 KeySym 0x0 ((null)).

There is an "invisible" visible triangle in the upper right corner when you're moving a window through the area. While it's not a critical bug, if it actually is one, it's not nice to see.

Attached screenshots. I made a video where it's many times better to see it on but I don't know what the way to share it on github is.

![triangle_1](https://user-images.githubusercontent.com/6150983/34009859-cd0dd494-e10a-11e7-8ba2-7a7d8d74c7d8.png)
![triangle_2](https://user-images.githubusercontent.com/6150983/34009860-cd2b3430-e10a-11e7-8e66-9bb181102256.png)

**Comment by C0rn3j** [comment]
>I made a video where it's many times better to see it on but I don't know what the way to share it on github is.

I generally make it an unlisted youtube video and just link it.

**Comment by gnif** [comment]
This is hardware frame tearing, something I am still contending with. In theory the Vulkan renderer I am writing will fix this.

**Comment by Morvs** [comment]
Alright, good to know, both things. Thanks.
