### ISSUE TITLE
windows-host-v11 stops running immediatly

### ISSUE THREAD

**Issue by caHocke** [gnif/LookingGlass#82]
### Required information

Host CPU: Intel Core i7-4770 CPU @ 3.9GHz
Host GPU: Mesa DRI Intel(R) Haswell Desktop
Guest GPU: NVIDIA GeForce 780ti
Host Kernel version: x86_64 Linux 4.9.0-6-amd64
Host QEMU version: version 2.8.1(Debian 1:2.8+dfsg-6+deb9u3)

I tried upgrading from looking-glassv10 to v11. 
The windows host immediately stops running with the only output being:

> [I]     CaptureFactory.h:83   | CaptureFactory::DetectDevice   | Trying DXGI
> [I]     CaptureFactory.h:86   | CaptureFactory::DetectDevice   | Using DXGI
> [I]          Service.cpp:132  | Service::InitPointers          | Total Available :  16 MB
> [I]          Service.cpp:133  | Service::InitPointers          | Max Cursor Size :   1 MB
> [I]          Service.cpp:134  | Service::InitPointers          | Max Frame Size  :   7 MB
> [I]          Service.cpp:135  | Service::InitPointers          | Cursor          : 000001EB0D320080 (0x00000080)
> [I]          Service.cpp:136  | Service::InitPointers          | Frame 1         : 000001EB0D420080 (0x00100080)
> [I]          Service.cpp:137  | Service::InitPointers          | Frame 2         : 000001EB0DBA0000 (0x00880000)

**Comment by gnif** [comment]
How do you mean, "stops running", does the process terminate? and if so, is it immediate or when you run the client?
Where is your client log?
Did you upgrade the client?
Are you using a master build or a tagged release?
What resolution is your guest running at?

**Comment by caHocke** [comment]
I did not get to start the client, I just started the host application and after generating htis output it stopped running. I could not find it in the Taskmanger. I can't find any log files. I assume they get generated at the same spot the .exe is located? I started it at various  locations to make sure it has nothing to do with read/write protection.

**Comment by Lessaj** [comment]
What are you emulating as the guest CPU? Is it passthrough or some other kind such as core2duo?

**Comment by gnif** [comment]
The application requires SSE2 instructions, at current it will silently fail if you do not have them available to the guest. Please ensure your guest is running with a CPU that supports them, either use core2duo or better, such as host-passthrough.

**Comment by caHocke** [comment]
I changed the cpu mode to host-passthrough and it works now. Thank you :+1:
