### ISSUE TITLE
[Enhancement] Add option to disable (or minify) the "Capture Enabled" and "Capture Disabled" messages

### ISSUE THREAD

**Issue by 132ikl** [gnif/LookingGlass#83]
### Required information

Host CPU: i7-7700k
Host GPU: Intel HD Graphics 630
Guest GPU: NVIDIA GTX 980
Host Kernel version: 4.17.3-1-ARCH
Host QEMU version: 2.12.0-1

If you frequently switch between capture enabled and capture disabled, (for example, often switching between a camera and a menu frequently, where capture is needed for camera wrap and normal mouse sensitivity is needed for menu) the message that appears in the middle of the screen can be very distracting and get in the way of content. There should be a way to disable this message, or to minify it so that there is just a color in the corner of the application or something similar.

**Comment by gnif** [comment]
Good point, I will add a option to disable the overlay.

**Comment by 132ikl** [comment]
thanks :)
