### ISSUE TITLE
Failed to connect to spice server - no configuration file on host

### ISSUE THREAD

**Issue by vodanet** [gnif/LookingGlass#835]
Required information
**Host**
Host CPU: Intel Core i7
Host GPU: iGPU
Host Kernel version: Ubuntu 20.0.4.3 LTS
Host QEMU version: 4.2.1

**On Windows VM**
Intel UDH Graphics is installed
Rad Hat QXL Controller is disabled (since i disabled them, Intel UHD has an yellow exclamation mark)
IVSHMEM Device is installed

Description of problem:
On Linux, when i want to start the looking-glass-client it outputs:
`[I]   7597459223              main.c:1064 | main                           | Looking Glass (B4)
[I]   7597459277              main.c:1065 | main                           | Locking Method: Atomic
[I]   7597463179           ivshmem.c:127  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
[E]   7597464697              main.c:727  | lg_run                         | Failed to connect to spice server
`

On VM Windows 10 i installed looking-glass-host-B4. But the service doesn't start.
When i manually try to start looking-glass-host.exe it outputs: 
`[I] 1438736191 app.c:494 | app_main | Configuration file not found or invalid`

- looking-glass-host.ini is not present
- also not present are the log files

I uninstalled looking-glass an reinstalled, but it changed nothing.

Sorry, i am no expert at this. But i hope you can help me!
Daniel

**Comment by gnif** [comment]
Issues are for bug reports, not support requests. Please use one of the recommended channels to discuss this (Discord or Level1Tech Forums) as your issue is a configuration problem.

https://looking-glass.io/discord
https://level1techs.coml/lg
