### ISSUE TITLE
Looking-glass host kills GPU performance when client is connected. 

### ISSUE THREAD

**Issue by mathew2214** [gnif/LookingGlass#839]
when the LG client connects, the host application uses nearly all of the GPU and makes gaming impossible in this state. 
there is a forum post discussing this issue here: 
https://forum.level1techs.com/t/looking-glass-host-kills-guest-gpu-performance/175785
disconnecting the client drops the GPU usage of the host to 0 and i get gaming performance i would expect from navi10.
looking-glass b2 did not have this issue and i have made zero hardware or virsh XML changes since then, i have only upgraded to B4. 
i have tried using bleeding-edge verisons of B4, this did not change anything, so i reverted to stable. 
looking-glass host does not produce a log txt file for me to upload. at least, not in the location stated in the wiki.

**Comment by gnif** [comment]
Issues are for bug reports, not support requests. Please use one of the recommended channels to discuss this (Discord or Level1Tech Forums) as your issue is a configuration problem.

https://looking-glass.io/discord
https://level1techs.coml/lg
