### ISSUE TITLE
When I was using LG to connect to my Win10 Guest, I encountered quite a bit of mouse out of control.

### ISSUE THREAD

**Issue by daiaji** [gnif/LookingGlass#84]
Required information

Host CPU:AMD FX(tm)-6300 Six-Core Processor
Host GPU:[AMD/ATI] RV710/M92 [Mobility Radeon HD 4330/4350/4550]
Guest GPU:GTX1050Ti
Host Kernel version:Linux linux-lpr1 4.17.3-1-default #1 SMP PREEMPT Tue Jun 26 06:45:20 UTC 2018 (e8dc1b5) x86_64 x86_64 x86_64 GNU/Linux
Host QEMU version:QEMU emulator version 2.12.0 (openSUSE Tumbleweed)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named looking-glass-host.dmp and attach it to this bug report.

Reports that do no include this information will be ignored and closed
```
sudo -E ./looking-glass-client -F -o opengl:amdpinnedmem=0
[I]               main.c:705  | run                            | Looking Glass (a11-30-gb19518a1f8)
[I]               main.c:706  | run                            | Locking Method: Atomic
[I]               main.c:699  | try_renderer                   | Using Renderer: OpenGL
[I]               main.c:793  | run                            | Using: OpenGL
[I]              spice.c:159  | spice_connect                  | Remote: 127.0.0.1:5900
[I]               main.c:919  | run                            | Waiting for host to signal it's ready...
[I]              spice.c:367  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]             opengl.c:687  | pre_configure                  | Vendor  : X.Org
[I]             opengl.c:688  | pre_configure                  | Renderer: AMD RV710 (DRM 2.50.0 / 4.17.3-1-default, LLVM 6.0.0)
[I]             opengl.c:689  | pre_configure                  | Version : 3.0 Mesa 18.1.2
[I]             opengl.c:704  | pre_configure                  | GL_AMD_pinned_memory is available but not in use
[I]               main.c:939  | run                            | Host ready, starting session
[I]             opengl.c:737  | configure                      | Using decoder: NULL
```

https://bbs.archlinux.org/viewtopic.php?id=203826
Some reports claim that SPICE is not working on Win10.
After trying to connect to Guest with VNC, I was relieved.
I tried using master branch to build binary files, but it didn't work.

**Comment by gnif** [comment]
Spice has nothing to do with the version of windows, qemu simply emulates a standard i8042 controller with a PS/2 mouse attached, spice tells qemu what data to send over that emulated device. The guest OS is never aware of spice.

Since you are asking for help here this will be ignored, issues are for bug reports only. For assistance please ask the community on the official help thread on the Level1 Tech forums as mentioned in the project README.md.

https://forum.level1techs.com/t/looking-glass-guides-help-and-support/122387
