### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [gnif/LookingGlass#86]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [nal_initialize](https://github.com/gnif/LookingGlass/blob/8ccce5666c81036924709762b25da8af9698f181/client/parsers/nal.c#L62)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [load_config](https://github.com/gnif/LookingGlass/blob/60070e60765dc2d6913dba20d3f72556ec822690/client/main.c#L1154)

**Comment by gnif** [comment]
Sure! any patches that improve the robustness of the project would be appreciated,

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by gnif** [comment]
It would be best to do so.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by gnif** [comment]
For now I am not at all interested in changing the way the project is being developed.
