### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [gnif/LookingGlass#87]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [a function like “nal_deinitialize”](https://github.com/gnif/LookingGlass/blob/8ccce5666c81036924709762b25da8af9698f181/client/parsers/nal.c#L69 "Update candidate: nal_deinitialize()").

**Comment by gnif** [comment]
Noted, please make a PR to correct this and I will apply it.

**Comment by elfring** [comment]
How do you think about to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by elfring** [comment]
* Was [the affected function ever successfully compiled](https://github.com/gnif/LookingGlass/blob/8ccce5666c81036924709762b25da8af9698f181/client/parsers/nal.c#L69 "Update candidate: nal_deinitialize()") before?
* Would you like to [try the mentioned development tool out](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") when you fiddle with (Linux) software occasionally?

**Comment by gnif** [comment]
Yes it was. What's with the 20 questions? Please either contribute to the project or stop wasting my time.

**Comment by elfring** [comment]
Should the parameter “`this`” refer to a pointer data type for the affected function?

**Comment by gnif** [comment]
Read the source.

**Comment by elfring** [comment]
[The involved data type definition](https://github.com/gnif/LookingGlass/blob/8ccce5666c81036924709762b25da8af9698f181/client/parsers/nal.h#L296 "Definition for NAL") can trigger different imaginations, can't it?

**Comment by gnif** [comment]
You're picking at code that at current isn't even in use. Either contribute or go away.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/gnif/LookingGlass/commit/ef336d552c71ba73b64acdcd6e65148c63edb858 "[parser/nal] no need to check for null before free").
