### ISSUE TITLE
is there any support for macos guest?

### ISSUE THREAD

**Issue by jhonoryza** [gnif/LookingGlass#890]
is there any support for macos guest?, i know currently looking glass only support windows os as a guest

**Comment by netboy3** [comment]
There is no IVSHMEM driver in MacOS so Looking-Glass can not be used there. You are more than welcome to write a driver for the project. For any additional support questions, please try to follow the guidelines given to you when you first opened this issue:

### Issues are for Bug Reports and Feature Requests Only!

If you are looking for help or support please use one of the following methods

Create a New Topic on the Level1Tech's forum under the Looking Glass category:
* https://forum.level1techs.com/c/software/lookingGlass/142

Ask for help in the Looking Glass discord server
* https://discord.gg/52SMupxkvt

*Issues that are not bug reports or feature requests will be closed & ignored*

**Comment by shahyar** [comment]
Hey @gnif, hate to necro a dead thread, but not sure if you've seen that @vially started some work regarding this per this comment https://www.reddit.com/r/VFIO/comments/wzwq3c/comment/imaffel/

There's a preliminary driver at https://github.com/vially/ivshmem.dext
And the implementation into Looking Glass at https://github.com/vially/lookingglass/tree/macos-playground

It's not very performant, but maybe you can guide it into the right direction?

**Comment by Verequies** [comment]
Hey @shahyar 

I am actually currently working on macOS VM support and I gave a little demo on the dev channel on Discord.
Code hasn't been pushed to GitHub but I've been working on it when I'm not working and have gotten it pretty stable.
My aim is to get it ready for B7, and once I've pushed the code it would be great to get testers.

I would suggest joining the dev channel on Discord for more updates.

**Comment by shahyar** [comment]
Hey, that's awesome! Thanks a lot, I'll pop into the channel. Looking forward to the commits :)

**Comment by gnif** [comment]
> but not sure if you've seen that @vially started some work regarding this per this comment https://www.reddit.com/r/VFIO/comments/wzwq3c/comment/imaffel/

Thanks mate, yes we are aware and have been in contact in Discord, however @Verequies is much further along then @vially and is likely what will be merged.
