### ISSUE TITLE
Orange busy circle

### ISSUE THREAD

**Issue by Morvs** [gnif/LookingGlass#9]
looking-glass-client -s -M -k
[I]               main.c:560  | run                            | Looking Glass (a3-3-gcd54cb179b)
[I]               main.c:636  | run                            | Initialized OpenGL
[I]            ivshmem.c:153  | ivshmem_connect                | RAM Size : 67108864
[I]               main.c:762  | run                            | Waiting for host to signal it's ready...
[I]               main.c:766  | run                            | Host ready, starting session
[I]               main.c:235  | renderThread                   | Data Format: w=2560, h=1440, s=2560, p=10240, bpp=32
[I]             opengl.c:159  | lgr_opengl_configure           | Vendor  : X.Org
[I]             opengl.c:160  | lgr_opengl_configure           | Renderer: Radeon RX 550 Series (AMD POLARIS12 / DRM 3.18.0 / 4.13.12-1-vfio, LLVM 5.0.0)
[I]             opengl.c:161  | lgr_opengl_configure           | Version : 3.0 Mesa 17.2.6
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 204 (196), X11 KeySym 0x0 ((null)).

The, usually blue, busy circle of window is colored in orange. I can't make out any other color shifts so far. It's not color shifted on the guest monitor. Sorry for the crappy quality of the screenshot.

![orange_circle](https://user-images.githubusercontent.com/6150983/34010072-9baf7730-e10b-11e7-8f5b-f2dad78f4f95.png)

**Comment by gnif** [comment]
Seems it's getting sent through as RGB rather then BGR (Red and Blue swapped). Thanks, I will see waht I can find.

**Comment by kiljacken** [comment]
It's probably the opposite! Many parts of the windows graphics stack actually use BGR over RGB, so it's completely possible that the cursor shape is one of these cases.

**Comment by gnif** [comment]
Fixed in 3c61814
