### ISSUE TITLE
Feature Request - Add a Anti Aliasing filter option

### ISSUE THREAD

**Issue by t9999clint** [gnif/LookingGlass#908]
I just started using B5 with some older (mostly 90s era) video games and they look awesome with the new filters.
This is a great feature and I'm glad you guys added it.

I was wondering if you had any plans to add a Anti-Aliasing filter like FXAA or TAA to looking glass?
This would allow me to simulate AA and high resolutions with older games (or just bad console ports) that don't have the settings to allow for this.

The driver options in windows allow for me to add this as well, but that doesn't work for every game. Also it's easier to be able to change it on the fly.

Playing old DOS 3D games in dosbox with FSR upscaling and AA applied could be a lot of fun (I'm sure it'll look derpy A.F. but w/e)

**Comment by gnif** [comment]
Good topics for discussions, not for a GitHub issue. Issues are for bug reports.
