### ISSUE TITLE
Doesn't build with libdecor support enabled

### ISSUE THREAD

**Issue by JaneSmith** [gnif/LookingGlass#913]
I have manually built and installed `libdecor` via the instructions over at the [libdecor project page](https://gitlab.gnome.org/jadahl/libdecor).

I can see that `libdecor` is installed to `/usr/local`, with the file `libdecor0.so` existing in `/usr/local/lib64/`.

I followed the official build instructions for Looking Glass:

```
mkdir client/build
cd client/build
cmake -DENABLE_LIBDECOR=ON ../
```

This gives me the error:

```
-- BFD libs: /usr/lib/x86_64-linux-gnu/libbfd.so
-- BFD libs: /usr/lib/x86_64-linux-gnu/libbfd.so
-- Checking for module 'libdecor-0'
--   No package 'libdecor-0' found
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  displayservers/Wayland/CMakeLists.txt:15 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

Therefore there is an issue somewhere, either with the build system or the given instructions.

Also a bit of a rant, but I so wish this project would prioritise usability a bit more. I've been trying Looking Glass on and off since it was first released years ago, and it's always the same nightmare every time. No user-friendly package is provided to make it easy for users to install, and it's always this nightmare of setting up a build system to manually compile it. A modern Flatpak should be provided so end-users can just install and run it... The install instructions list Ubuntu dependencies with no clear Fedora equivalent, so I had to set up an entire Ubuntu VM to try to build this in. And it still isn't working... Also client-side decorations should be a core feature and not some experimental unsupported thing... Wayland doesn't say anything about needing server-side decorations. Wayland was designed to have client-side decorations! Wayland Protocols is not "standard" as the aggressively-worded FAQ seems to suggest...

**Comment by gnif** [comment]
1) The documentation targets Debian NOT Ubuntu.
2) The wiki has the dependency lists for other distros
3) It is not up to the developers to try to support and maintain XYZ distro packaging.
4) This is BETA software, the host and client versions MUST match, any distro that packages the client will be outdated as soon as any change is made to the host that alters the protocol as it is not yet stable.
3) It's not up to is to make a Flatpak, this is free open source software and development is done in our spare time, how much time do you think we have?
4) Client-side decorations don't work on GNOME, they work fine on every other window manager on both Xorg and Wayland. It's GNOME that have broken the standards and refuse to use the standard window decoration system that the rest of the world use.

**Comment by JaneSmith** [comment]
> The wiki has the dependency lists for other distros

Thanks, I found that now that you pointed it out. However it is extremely hidden! The "Wiki" link on GitHub just redirects to the main GitHub project page, and the website doesn't seem to have any link to the wiki that I could find. I literally had to do a Google search to find the wiki instead of just finding it naturally on the website.

> It is not up to the developers to try to support and maintain XYZ distro packaging.

> It's not up to is to make a Flatpak, this is free open source software and development is done in our spare time, how much time do you think we have?

I understand that you're offering this for free (although you are receiving donations and selling merchandise). I certainly don't mean to sound rude or entitled. You don't have to do anything at all. But I believe that what I said are perfectly valid and true criticisms. Requiring the project to be compiled manually is a very large barrier to users. Developers compile projects; end users just install and run them. Objectively, providing a package would significantly lower the entry barrier, and also probably stop people bothering you with issues such as this all the time.

Actually, it generally is expected that developers will package their own software. It's not up to other random people to package your software for you. Why are you even writing software, if you don't want people to be able to use it? Surely you do want it to be out there and for people to use it... and providing a package allows people to do this.

You say it's not up to you to make a Flatpak, but somebody did make an attempt (#168) to get the ball rolling on a Flatpak package and you shut it down. Instead of allowing them to make use of their free time to make it easier to people to use this software, you came in and specifically asked them not to publish it! For your information, beta software can be treated separately on Flathub if that's so important.

> It's GNOME that have broken the standards and refuse to use the standard window decoration system that the rest of the world use.

GNOME is the most popular Linux desktop environment. It is the standard. [Wayland was designed to use client-side decorations.](https://en.wikipedia.org/wiki/Client-side_decoration#Wayland) The "official Wayland standard" that you've linked to is a third-party thing. It's my understanding that it was started off by the author of Sway. If you look at the footer of the website you linked, it literally says "This website is not affiliated in any way with the official Wayland project."

> Ranting about a free open source project you didn't pay a dime for does nothing

How do you know that I haven't previously donated to this project?

> but make you look like a fool and make those of us who are pouring all our efforts into these projects want to completely ignore/disregard everything you have to say. You want things improved, instead of ranting be productive and get involved fixing things... if you're not willing to get involved, ask nice, and hope that we decide to work on YOUR issue.

From my perspective, I have said absolutely nothing insulting or disrespectful. I pointed out perfectly valid, objectively true weaknesses of the project. You are the one being rude here.

**Comment by gnif** [comment]
From my perspective, I have said absolutely nothing insulting or disrespectful.

> Also a bit of a rant

> I certainly don't mean to sound rude or entitled

> /rant/ - verb
> speak or shout at length in an angry, impassioned way.

> although you are receiving donations and selling merchandise

Which barely covers the cost of purchasing things FOR this project that we need, like hardware and software such as code signing certs, etc. How much do you think we are making here? This project has had well over $100,000 worth of development time put into it, we are certainly UNPAID.

> You say it's not up to you to make a Flatpak, but somebody did make an attempt (#168) to get the ball rolling on a Flatpak package and you shut it down

For exactly the reasons I just stated, this is experimental BETA software, it is NOT stable. We have enough grief from the Debian maintainer that decided to package the alpha client because people come asking for support for a package that is A) years old, B) is not paired with the right version of the host application. Our time is limited and until WE, the creators of this software decide the protocols are stable enough for packaging we do not want our time wasted on frivolous support requests due to bad packages.

> How do you know that I haven't previously donated to this project?

Donation to the project doesn't equate to purchase of the product, or implied support.

**Comment by JaneSmith** [comment]
So you're getting upset and defensive merely because I used the word "rant"? Here's a second definition for the word:

> To express at length a complaint or negative opinion

If I'm detailing negative experiences, is that not a rant? I said nothing rude or insulting. I did not berate you, call you names, insult the project or any contributors. I detailed the (objectively true) negative aspects of getting started with the software as an end user. It seems to me that you simply can't handle being told about weaknesses of the project... But no project is perfect. In my experience with any other open source project, speaking up about weaknesses is a good thing, as it allows them to then be discussed, and solutions to be figured out.

> Which barely covers the cost of purchasing things FOR this project that we need, like hardware and software such as code signing certs, etc. How much do you think we are making here? This project has had well over $100,000 worth of development time put into it, we are certainly UNPAID.

Why are you saying this? I never suggested that you have endless resources, so I'm confused as to what point you're trying to make.

> Donation to the project doesn't equate to purchase of the product, or implied support.

I never said it did. I was responding to you saying that I didn't pay a dime for the project.

> For exactly the reasons I just stated, this is experimental BETA software, it is NOT stable. We have enough grief from the Debian maintainer that decided to package the alpha client because people come asking for support for a package that is A) years old, B) is not paired with the right version of the host application. Our time is limited and until WE, the creators of this software decide the protocols are stable enough for packaging we do not want our time wasted on frivolous support requests due to bad packages.

I believe that at least at some point, i.e. when it is stable, there should be a provided package as that is objectively better for end-users. It's fine for you to have the opinion that the software is too fast-moving currently. But my opinion is that a Flatpak package wouldn't be that difficult to maintain, and if it was officially supported then there wouldn't be "bad packages" causing a flood of support requests. That's one of the (many) benefits of Flatpak... It's cross-distro and can function as the "one true" package for the app. Everyone using the Flatpak package gets the exact same environment, and so the software runs the same way regardless of what kind of setup the end-user has. This increases consistency of how the software runs, and therefore decreases support requests and makes troubleshooting easier. As for the mis-match between versions, I don't see how that's any different than the current situation. You'd just need to update the Windows host version after updating the client version.

**Comment by gnif** [comment]
> If I'm detailing negative experiences, is that not a rant? I said nothing rude or insulting. 

You open an issue about one topic, then go on to "rant" about unrelated issues, you tell me objectively how that looks?

> I detailed the (objectively true) negative aspects of getting started with the software as an end user.
> Requiring the project to be compiled manually is a very large barrier to users.

I reiterate, this project is not out of beta, and by definition that makes it not ready for general end-users. If you're not capable of building the client, you should not be using it yet. We expect people to have a certain level of technical ability (ie, knowing that building on Ubuntu wont provide a viable binary for Fedora) to provide good debug reports/logs and debug back-traces so that we can fix the issues.

> It seems to me that you simply can't handle being told about weaknesses of the project... But no project is perfect. 

It seems to me that we KNOW this project is not ready or perfect and that's why we take this stand.

> Why are you saying this? I never suggested that you have endless resources, so I'm confused as to what point you're trying to make.

Your statement in parenthesises implied that this work is paid for and we are making a profit, which is far from fact. Hopefully one day we will attract a large company willing to sponsor this work, but until then make no mistake, this project is operating at a complete loss.


>> Donation to the project doesn't equate to purchase of the product, or implied support.

> I never said it did. I was responding to you saying that I didn't pay a dime for the project.

That's just it, if you donated, you didn't pay "for the project", you assisted in funding my open source efforts on this project, or one of the other projects that I also pour time into (QEMU, PureSpice, the Linux kernel, etc.)

**Comment by gnif** [comment]
Note:
> Thanks, I found that now that you pointed it out. However it is extremely hidden! The "Wiki" link on GitHub just redirects to the main GitHub project page, and the website doesn't seem to have any link to the wiki that I could find. 

This will be fixed, this is indeed an oversight from when we moved from just the wiki to sphinx docs in the last release.
