### ISSUE TITLE
Client uses X11 primary clipboard

### ISSUE THREAD

**Issue by spencercw** [gnif/LookingGlass#918]
The Looking Glass client accepts data from by the PRIMARY and CLIPBOARD selections when pasting data to Windows. Debatable whether this qualifies as a bug since it's clearly working as intended, but for me the clipboard appeared to be behaving erratically. My workflow was looking something like this:

1. Copy text into clipboard on Linux.
2. (Sometimes) select previously copied text on Linux to overwrite it with the new text.
3. Paste new text on Linux.
4. Paste new text on Windows.

So it appeared that the Windows clipboard was randomly not being updated. Of course it just depended on whether I happened to do step 2 or not.

I think it might make sense to only use the CLIPBOARD selection by default with an option to also use the PRIMARY selection. Or perhaps just an option to not use the PRIMARY selection.

Thanks for this great project.

**Comment by gnif** [comment]
The issue is that not all applications handle the clipboard selections the same, and as such we have to handle both. This tool however might be helpful to you in keeping your clipboards in sync which fixes the randomness of the clipboard behaviour between different applications in my experience, https://www.nongnu.org/autocutsel/

**Comment by spencercw** [comment]
It was my impression that PRIMARY is used for whenever you select any text, and CLIPBOARD is used when you explicitly copy something (e.g., with Ctrl+C or the context menu). Are there some applications that buck this trend?

It's not so much of a problem now that I understand what's going on, but the behavior is a bit inconsistent with other applications. If I Ctrl+V into Windows via Looking Glass then I get either the contents of PRIMARY or CLIPBOARD, but if I Ctrl+V into any other application then I only get CLIPBOARD.

**Comment by quantum5** [comment]
For what it's worth, on Wayland we only use the clipboard and not the primary selection.

**Comment by spencercw** [comment]
Would you accept a patch to bring it in line with Wayland (i.e., don't use the primary selection), or have you got any other thoughts on how best to deal with this?

**Comment by gnif** [comment]
I agree that atm on wayland we are handling this more correctly so yes, a patch would be accepted to correct this, thanks
