### ISSUE TITLE
Single Application Mode Support

### ISSUE THREAD

**Issue by WillPower3309** [gnif/LookingGlass#919]
I know this is likely outside of the scope of the project, but would a per Application type mode be possible? Something like [winapps](https://github.com/Fmstrat/winapps) via lookingglass could be a really cool way to get relatively seamless windows software working in Linux, especially [since the winapps maintainer is now wanting to step away from the very popular project](https://github.com/Fmstrat/winapps/issues/269)

**Comment by WillPower3309** [comment]
[The levelonetechs remote app guide](https://forum.level1techs.com/t/how-to-seamlessly-run-windows-10-apps-in-a-vm-in-linux/170417) mentions:

> It is also possible for Looking Glass to support single-application modes, but we would want Nvidia’s blessing on opening up their API as they have with Steam. We can do this single-app looking glass thing with Quadro cards fairly easily, but not for geforce cards because that API is disabled. Unless you’re steam. Then it is enabled.

With Nvidia opening up their API recently is this a feature that already exists?

**Comment by gnif** [comment]
> but would a per Application type mode be possible
Not without a ton of funding, this is a very complex thing to do and as you stated, well outside the scope of LG.

> With Nvidia opening up their API recently is this a feature that already exists?

NVidia have not opened up any useful API to us, and in fact the entire Nvidia Capture API via NvFBC and NvIFR have been deprecated by nvidia.

**Comment by klownie** [comment]
Aww too bad this would have been amazing
