### ISSUE TITLE
make client error: spice/rsa.c:23:10: fatal error: spice/protocol.h: No such file or directory

### ISSUE THREAD

**Issue by cape** [gnif/LookingGlass#92]
### Required information

Host CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Host GPU: VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
Guest GPU: VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)
Host Kernel version: Linux  4.18.1-041801-generic #201808151233 SMP Wed Aug 15 16:39:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Host QEMU version: QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.4)

Hi, I tried to follow the instructions here:
https://looking-glass.hostfission.com/quickstart/linux/build
when I try to make the client I have this errror, maybe a dependency is missing?

> LookingGlass-a11/client# make 
> Package nettle was not found in the pkg-config search path.
> Perhaps you should add the directory containing `nettle.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'nettle' found
> Package hogweed was not found in the pkg-config search path.
> Perhaps you should add the directory containing `hogweed.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'hogweed' found
> make: git: Command not found
> cc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -DATOMIC_LOCKING -ffast-math -fdata-sections -ffunction-sections -Wfatal-errors -D USE_NETTLE  -DBUILD_VERSION='""' -o .build/spice/rsa.o spice/rsa.c
> spice/rsa.c:23:10: fatal error: spice/protocol.h: No such file or directory
>  #include <spice/protocol.h>
>           ^~~~~~~~~~~~~~~~~~

**Comment by cape** [comment]
I fixed one of the issues, I missread the dependencies, installing nettle-dev fix one of the issues.
the second one is that you need to have git installed

**Comment by gnif** [comment]
This has already been reported, also git is not required as you can download the tagged releases directly from github. Please stop opening bug report issues for documentation problems. LG is Alpha and as such the documentation takes back seat.
