### ISSUE TITLE
Buggy unicode SPICE clipboard synchronisation

### ISSUE THREAD

**Issue by kotarou3** [gnif/LookingGlass#925]
I've set up clipboard synchronisation following the instructions in [the FAQ](https://looking-glass.io/wiki/FAQ#How_to_enable_clipboard_synchronization_via_SPICE), and it seems to be working fine.

However, it only seems to work for ASCII text. If I try to copy unicode text such as τНꞮƨ🪞 (with Ctrl+C), any unicode letters get replaced by "?".
It also seems a bit inconsistent, in that sometimes it's replaced, and sometimes it gets copied fine.

This happens even if I'm just copying from host-to-host or guest-to-guest, and not even directly using the synchronisation feature.
Of course, if I close looking glass, this no longer happens.

I'm not completely sure if it's a bug in looking glass or SPICE itself.
My host runs Debian Linux while the guest runs Windows 10, so perhaps it might be related to Linux preferring to use UTF-8 and Windows preferring to use UTF-16?

### Steps to reproduce
1. Set up looking glass with clipboard sync, and start the application
2. Select and copy (Ctrl+C) any text containing unicode, such as: τНꞮƨ🪞
3. Wait a few seconds for clipboard to sync
4. Paste the text anywhere
5. If the unicode was not replaced by "?" characters, retry steps 2-4

### System Info
- **Host:** Linux Debian bookworm (5.15.0-2)
- **Guest:** Windows 10 Enterprise 1809
- **Looking Glass Version:** B5.0.1

**Comment by gnif** [comment]
Looking Glass simply provides the raw data, it does no processing nor cares about the type information, it just passes it on.

It sounds like you have some other issue with your system as I can copy & paste your example without fault and I am also running Debian (not bookworm though).

Are you running Xorg or Wayland?

**Comment by kotarou3** [comment]
I'm running Xorg with the `gnome-flashback` desktop environment.
Most packages are up-to-date with what's in the Debian bookworm/testing repos, but I'll fully update and report back if it made any differences

**Comment by spencercw** [comment]
For what it's worth, I regularly copy Japanese text to and from the host and it works no problem. Host is Manjaro Linux (X11, Xfce), guest is Windows 11.

**Comment by kotarou3** [comment]
I realised what might be a strange thing about my setup at the moment, that's probably the cause of the problem.

I run a VNC client to the same VM that looking glass is connecting to, and both have clipboard synchronisation features.

It turns out that the VNC clipboard synchronisation is doing the unicode mangling on the Linux→Windows path (it has no reverse synchronisation), not looking glass.
But once mangled by VNC, looking glass happily copies the mangled clipboard contents Windows→Linux, completing the loop and thus resulting in the Host→Host and Guest→Guest mangling that wasn't present prior to installing looking glass.

Disconnecting the VNC client seems to solve the problem, so this is not a bug in looking glass
