### ISSUE TITLE
git master at Aug 3, 2018: failed to read SpiceLinkHeader

### ISSUE THREAD

**Issue by dracwyrm** [gnif/LookingGlass#93]
### Required information

Host CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz GenuineIntel GNU/Linux
Host GPU: MSI AMD R7 260 OC 1GB DDR5 PCI-E Graphics Card
Guest GPU: MSI NVIDIA GTX 970 Gaming Twin Frozr HDMI DVI-I DP 4 GB PCI Express DDR5 256 Bit Graphics Card
Host Kernel version: 4.17.12-gentoo #2 SMP PREEMPT
Host QEMU version: 2.12.0-r4

I was starting looking-glass-client from the command line trying both as regular user and su. The full error as both types of users is:
```
~ $ looking-glass-client 
[I]               main.c:726  | run                            | Looking Glass ()
[I]               main.c:727  | run                            | Locking Method: Atomic
[I]               main.c:720  | try_renderer                   | Using Renderer: OpenGL
[I]               main.c:830  | run                            | Using: OpenGL
[I]              spice.c:159  | spice_connect                  | Remote: 127.0.0.1:5900
[E]              spice.c:757  | spice_read                     | incomplete write
[E]              spice.c:591  | spice_connect_channel          | failed to read SpiceLinkHeader
[E]              spice.c:167  | spice_connect                  | connect main channel failed
[E]               main.c:931  | run                            | Failed to connect to spice server
```

I have all the programs installed, and this is the ebuild I made to install everything:
https://github.com/dracwyrm/gentoo-ebuilds/blob/master/app-emulation/LookingGlass/LookingGlass-0_alpha12_pre20180803.ebuild (I would like to get a12 in the main tree when it's released, so practicing on the pre at the moment since it's CMake).

On the Windows machine, I used Visual Studio Community Edition to compile the host binary. The program compiled without errors and seems to run.

I then tried to start the client with the -s option, and it started. However, the image flickers -- it goes black for a second, then I see the desktop for a second, then black, and so on like this. Also, the mouse does not capture and can't do anything.
```
~ $ looking-glass-client -s
[I]               main.c:726  | run                            | Looking Glass ()
[I]               main.c:727  | run                            | Locking Method: Atomic
[I]               main.c:720  | try_renderer                   | Using Renderer: OpenGL
[I]               main.c:830  | run                            | Using: OpenGL
[I]               main.c:964  | run                            | Waiting for host to signal it's ready...
[I]             opengl.c:455  | opengl_render_startup          | Vendor  : X.Org
[I]             opengl.c:456  | opengl_render_startup          | Renderer: AMD BONAIRE (DRM 2.50.0, 4.17.12-gentoo, LLVM 6.0.1)
[I]             opengl.c:457  | opengl_render_startup          | Version : 3.1 Mesa 18.1.5
[I]             opengl.c:469  | opengl_render_startup          | Using GL_AMD_pinned_memory
[I]               main.c:984  | run                            | Host ready, starting session
[I]             opengl.c:890  | configure                      | Using decoder: NULL
```

Since I have the ebuild, it's very easy to try changes, so I can try to help as much as possible. :)

Thanks,
Jon

**Comment by gnif** [comment]
Custom builds of non tagged versions are NOT supported, if you insist on running one you're on your own. The Spice error indicates a problem with you Qemu configuration, ie, did you use VNC instead of Spice?
