### ISSUE TITLE
Windows Client & Linux Server support.

### ISSUE THREAD

**Issue by hobnob11** [gnif/LookingGlass#94]
### Required information

Host CPU: I7 6700k
Host GPU: I7 6700k iGPU
Guest GPU: GTX 1070
Host Kernel version:  4.17.9-200.fc28.x86_64
Host QEMU version: qemu-2.11.2-1.fc28

The lack of G Sync support, among other small issues are currently the only reasons I'm still using windows as my bare metal OS instead of windows in a VM, My use case would still be to primarily use windows as my daily desktop, while being able to "alt tab" to linux for things i need to do on there.

Why not use the system the other way around? let me have a looking glass client on my windows machine, using the display output from a passed through GFX card directly to a monitor, to interact with the host Linux system.

**Comment by daiaji** [comment]
It seems that LookingGlass requires some APIs from Nvidia GPUs to work.
Nvidia GPUs are inactive on the host after using VGA PCI Passthrough.

**Comment by hobnob11** [comment]
I would imagine those Nvidia API's are only for taking the frame buffer from Nvidia cards, in this set up the looking glass server would be grabbing the Intel iGPU's frame buffer, so I suspect they arn't needed in this use case.

**Comment by gnif** [comment]
It is indeed possible but at this time it is not the focus of this project. In figure please do not ask for general support in issues, instead use the actual support forum or IRC as mentioned in the `README.md`
