### ISSUE TITLE
What's the required feature level?

### ISSUE THREAD

**Issue by grepwood** [gnif/LookingGlass#96]
### Required information

Host CPU: AMD Ryzen 2700
Host GPU: Radeon 460
Guest GPU: GeForce 710
Host Kernel version: 4.16.7 (custom)
Host QEMU version: 2.12.1

I get a message that the interface or feature level is not available.
![obraz](https://user-images.githubusercontent.com/4225739/45269962-26ded800-b497-11e8-81af-dc7b8ee6feda.png)

Maybe it's the because my guest card gets code 43?

**Comment by grepwood** [comment]
Yeah, code 43

**Comment by D4Delta** [comment]
Hey, what do you mean by "Code 43" ? I got the same error (required feature level) but my card is recognized and working on windows (it ran an OpenGL benchmark + Nvidia DirectX demo).

**Comment by D4Delta** [comment]
Oh, sorry about that, I thought it classified as a bug.

**Comment by grepwood** [comment]
@D4Delta Code 43 means nVidia's evil driver has figured out that you're trying to run it on a hypervisor and therefore it's throwing a bitch fit.

**Comment by gnif** [comment]
@grepwood please do not continue this here, it has been discussed in detail over on the L1Tech forums, each time an issue is updated, even a closed issue I waste time checking it to see if it is really a bug report or not.
