### ISSUE TITLE
Can we have shortcuts which is like alt-tab, alt-f4, win-tab being sent to LG directly when the LG window is active?

### ISSUE THREAD

**Issue by xinminglai** [gnif/LookingGlass#978]
Hi,
Thanks for your amazing work.
Now it's the requirement tool in my work. But after upgraded to 5.0.0, I found that many shortcuts which is like alt-tab, alt-f4, win-tab are sent to the window manager directly, Which is counterintuitive.

I open many remote connections when I work, I need to switch between these windows frequently, with the xfreerdp window is active, I am sure that almost all shortcuts will be sent to remote machine rather than local window manager.

But now with LG 5.0.0, It's quite anonying that when I need to do alt-tab, I have to hit "Scroll Lock" first, then alt-tab, when I want to go to another window on host, I'll have to press "Scroll Lock" again to unlock the cursor, which I normally forgot, and the mouse cursor keeps in screen,
This is quite counterintuitive, When the window is open, and cursor is within the window, when we press alt-tab, we definitely want to switch app in the "remote" computer, but now, instead, I lose focus on the LG and go to other app, and countless times, when the LG window is active, I press alt-f4 to wishfully to close the remote app, The LG window itself is closed, and I have to open again.

So can we please change this behavior? if not, Can we add another capture mode which behaves like xfreerdp?

The new mode will automatically handle the all shortcuts behavior, Such as, when LG window is active, and cursor is captured, and cursor is in LG window, All shortcuts capturable will be sent to virtual machine directly, and when user moves cursor out of the LG window, then shortcuts will be sent to window manager, or maybe send to LG window too, and leave a few shortcuts for user to switch window.
The way vmware/virtualbox/xfreerdp have good experience on the shortcut behavior.

BTW, I know that Win-Alt-Tab behaves like Alt-tab in LG window, But to me, that's not handy either, as I always need to think wether I need to press Win along with Alt-tab, which gave the interruption experience of using LG. And most time, I switch to other app directly or close the window before I even think about the Win-Alt-Tab thing exists.

Thanks.

**Comment by gnif** [comment]
have you tried turning on `input:grabKeyboardOnFocus`?

**Comment by xinminglai** [comment]
That worked,
It's been quite a lot of pain to not use that option for over a month.

Thanks very much.
