### ISSUE TITLE
Directly expose Windows installer artifact without zipping to allow packaging it on winget-pkgs

### ISSUE THREAD

**Issue by PAI5REECHO** [gnif/LookingGlass#985]
I suppose this falls under the category of a feature request?

I install Looking Glass quite often each month for virtual machine work. It'd be nice to be able to automate installation of the host application so I opened an issue to get it into `winget-pkgs` (see https://github.com/microsoft/winget-pkgs/issues/58708). The only problem is that the host application artifact download nests the installer binary inside a zip along with the build log file which winget-pkgs doesn't like since it has to unzip it to get to the installer. Since the build file is already available from `https://looking-glass.io/artifact/{version}/log` would it be acceptable to have the installer binary directly available from the downloads page without zipping it?

**Comment by gnif** [comment]
We are not yet recommending any form of packaging of LG. This has been raised multiple times and at this time we will not be making changes to encourage packaging. When LG v1.0 is released at which point the LGMP & KVMFR protocols will be considered stable/final, then this stance will change.
