### ISSUE TITLE
[client] Add ability to include Windows hostname in client window titlebar

### ISSUE THREAD

**Issue by PAI5REECHO** [gnif/LookingGlass#986]
It'd be nice to have an option that would allow me to include the Windows hostname of each VM as part of the client window titlebar text so I can easily differentiate what is what at a glance in my window manager. For instance when I do kernel driver development I typically have 1 VM for running my debugger frontend and another test VM that's the debug target. I constantly switch focus between the two LG windows and my code. If each client window was labeled according to the computer hostname I could navigate to the correct client window more easily. Maybe being able to have `%h` in `win:title` be interpolated as the hostname of the VM would be the best way to add this feature?

**Comment by gnif** [comment]
There is no way to reliably support this as if spice is not use (which is for many) we never know the name of the guest VM. Also if libvirt is not in use and QEMU is instead used directly (or some other means) it's also not easily obtainable.

In future please discuss potential feature requests on Discord before opening a ticket. We will advise you there if it's something we will implement and if so then you will be directed to open a ticket.
