### ISSUE TITLE
Small mistake in the docu how you build the win host on linux

### ISSUE THREAD

**Issue by JSchmiegel** [gnif/LookingGlass#989]
Hey guys,

I am a big fan of your project. 

Just a small mistake I stumbled across while building the win host on linux.
In the docu (I am referring to [https://looking-glass.io/docs/B5.0.1/build/#host](https://looking-glass.io/docs/B5.0.1/build/#host)) the command for building a windows host on linux is `cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake ..`.
I think there is a typo. The right command should be (at least in my opinion) `cmake -CMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake ..`

Best regards and many thanks for the project
Jonas

**Comment by esibun** [comment]
This is correct as written in documentation, and generates a Windows 64-bit executable for me.  The second command will fail as everything past `-C` is interpreted as a target; -C doesn't take a parameter.  In general, Linux convention is that arguments with multiple characters are proceeded with two dashes, otherwise the rest of the argument is interpreted as a parameter to that argument if that makes sense.

**Comment by JSchmiegel** [comment]
Hi @esibun 
thanks for your quick reply. I played around a bit more with the command (should have done it before creating the issue).
Apparently you are right. The command works fine. 
But strangely, I can observe the following phenomenon (which is probably more a bug of cmake or so and less of looking-glass).

When I make a typo in the command (like forgetting the "E" of "..._FILE") the first run will end with a warning, that the `CMAKE_TOOLCHAIN_FIL` is not used. The following run (with the correct command) will get me the same mistake, and the try after this will be successful (no matter if the command has again a typo). (You can see this in the following image)

![image](https://user-images.githubusercontent.com/51242445/168452510-a05a6a95-2bec-445b-b400-1f6565697d94.png)


This really weird bug confused me and made me think that there is a mistake in the docu. Sorry for the confusion. I will close the issue now, as it is definitely not a looking-glass issue. 

Thanks again for your commitment and the great project.
